import type { Metadata } from "next";
import Link from "next/link";
import { toJsonLd } from "@/lib/schema";
import RelatedLinks from "@/components/RelatedLinks";

export const metadata: Metadata = {
  title: "Google Ads for Medical Practices — New Patients Fast | Primara",
  description:
    "Primara manages Google Ads for independent primary care and mental health practices. HIPAA-aware setup, LSA verification, and search campaigns built around new-patient intent. No long-term contracts.",
  alternates: { canonical: "https://primara365.com/services/google-ads" },
  robots: { index: true, follow: true },
  openGraph: {
    title: "Google Ads for Medical Practices — New Patients Fast | Primara",
    description:
      "HIPAA-aware Google Ads for independent primary care and mental health practices. LSA setup, search campaigns, and privacy-compliant call tracking.",
    type: "website",
    url: "https://primara365.com/services/google-ads",
    images: [{ url: "/opengraph-image", width: 1200, height: 630 }],
  },
  twitter: { card: "summary_large_image", images: ["/opengraph-image"] },
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: "https://primara365.com" },
    { "@type": "ListItem", position: 2, name: "Services", item: "https://primara365.com/services" },
    { "@type": "ListItem", position: 3, name: "Google Ads for Medical Practices", item: "https://primara365.com/services/google-ads" },
  ],
};

const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "Google Ads for Medical Practices",
  provider: {
    "@type": "LocalBusiness",
    name: "Primara",
    telephone: "+15612912681",
    address: {
      "@type": "PostalAddress",
      addressLocality: "West Palm Beach",
      addressRegion: "FL",
      addressCountry: "US",
    },
  },
  areaServed: { "@type": "Country", name: "United States" },
  serviceType: "Pay-Per-Click Advertising",
  description:
    "HIPAA-aware Google Ads management for independent primary care and mental health practices — Local Service Ads, search campaigns, and privacy-compliant conversion tracking.",
};

const adTypes = [
  {
    label: "Google Local Service Ads",
    tag: "Highest Intent",
    body: "LSAs appear above all other Google results — even organic search — with a \"Google Screened\" badge that signals verified credentials to prospective patients. For practices in primary care and mental health, this placement is the closest thing to a qualified referral at scale.",
    items: [
      "Healthcare vertical verification: license, malpractice insurance, and background check",
      "Profile setup: services, hours, service area, and photo upload",
      "Budget and bid management: pay per verified lead, not per click",
      "Dispute resolution workflow for leads that don't meet qualification criteria",
      "Review strategy to build the LSA profile rating patients see before clicking",
    ],
  },
  {
    label: "Google Search Campaigns",
    tag: "Immediate Visibility",
    body: "Search ads target patients at the exact moment they're searching for a provider. A correctly structured campaign appears when someone types \"primary care doctor accepting new patients\" or \"therapist near me\" — and stops spending when they search for something unrelated.",
    items: [
      "Keyword research built around new-patient intent — not brand terms you already own",
      "Negative keyword lists to exclude irrelevant searches and prevent wasted spend",
      "Ad copy reviewed for Google healthcare policy compliance: no outcome guarantees, no superlatives",
      "Geographic targeting by ZIP code, radius, and neighborhood — not broad metro areas",
      "Ad extension setup: call extensions, location, sitelinks, and structured snippets",
      "A/B testing on headline and description variants with statistical rigor",
    ],
  },
  {
    label: "Conversion Tracking",
    tag: "Privacy-Compliant",
    body: "Healthcare practices can't use standard Google Tag Manager configurations that capture URLs, form field content, or session data that might constitute protected health information. We build privacy-compliant conversion tracking from the start.",
    items: [
      "Call tracking: count inbound calls generated by ads without recording PHI",
      "Form-fill attribution: count new inquiry submissions without logging health-related content",
      "Google Ads + Search Console integration for full-funnel visibility",
      "Monthly performance report: cost per lead, lead volume, impression share, and quality score",
      "Budget pacing alerts to prevent unexpected overspend",
    ],
  },
];

const faqs = [
  {
    q: "How much does Google Ads cost for a medical practice?",
    a: "Ad spend varies by market, specialty, and competition. In most primary care markets, expect a minimum effective budget of $800–$1,500/month in ad spend plus Primara's management fee. Mental health markets are often less competitive. We provide a market analysis before recommending a budget.",
  },
  {
    q: "What's the difference between Google Ads and Local Service Ads?",
    a: "Standard Google Search Ads are text ads that appear when someone searches for keywords you bid on — you pay per click. Local Service Ads appear above Search Ads, show a Google Screened badge, and charge per verified lead (a phone call or message from a prospective patient). LSAs require credential verification but typically deliver higher-quality inquiries.",
  },
  {
    q: "Do Google Ads work for mental health practices?",
    a: "Yes — mental health is one of the highest-converting categories in healthcare search advertising because intent is clear: someone searching \"therapist near me accepting new patients\" is ready to book. Google has additional policy requirements for mental health advertising that we build around from the start.",
  },
  {
    q: "Should I run ads before my SEO is established?",
    a: "It depends on your timeline. Ads provide immediate placement while SEO matures over months. If you have a new practice or added a provider and need to fill your schedule quickly, running both simultaneously is the most effective path. If your organic and GBP presence is already strong, ads may be less urgent.",
  },
  {
    q: "Is HIPAA compliance an issue with Google Ads?",
    a: "It can be. Standard conversion tracking implementations can inadvertently capture search queries or URL parameters that contain health-related information, which may constitute PHI under HIPAA. Primara configures all tracking to count conversion events without capturing the content of those events.",
  },
  {
    q: "Is there a long-term contract?",
    a: "No long-term contracts. Month-to-month after initial campaign setup. Setup typically takes 7–10 days from signed agreement to first live ad.",
  },
];

// Derived from `faqs` above — single source of truth, so the schema can
// never drift out of sync with the visible Q&A content on the page.
const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

export default function GoogleAdsPage() {
  return (
    <main className="pt-16">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: toJsonLd(breadcrumbSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: toJsonLd(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: toJsonLd(faqSchema) }} />

      {/* Breadcrumb */}
      <nav aria-label="Breadcrumb" style={{ backgroundColor: "var(--surface)", borderBottom: "1px solid var(--wire)" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8 py-3">
          <ol className="flex items-center gap-2 flex-wrap" style={{ color: "var(--smoke)", fontSize: "0.8125rem" }}>
            <li><Link href="/" style={{ color: "var(--ash)", textDecoration: "none" }}>Home</Link></li>
            <li aria-hidden="true" style={{ color: "var(--wire)" }}>/</li>
            <li><Link href="/services" style={{ color: "var(--ash)", textDecoration: "none" }}>Services</Link></li>
            <li aria-hidden="true" style={{ color: "var(--wire)" }}>/</li>
            <li style={{ color: "var(--chalk)" }}>Google Ads</li>
          </ol>
        </div>
      </nav>

      {/* Hero */}
      <section
        style={{
          backgroundColor: "var(--void)",
          padding: "clamp(56px, 8vw, 96px) 0 clamp(40px, 6vw, 72px)",
          borderBottom: "1px solid var(--wire)",
        }}
      >
        <div className="mx-auto max-w-content px-6 lg:px-8">
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "8px",
              background: "rgba(201,168,76,0.12)",
              border: "1px solid rgba(201,168,76,0.3)",
              borderRadius: "3px",
              padding: "5px 14px",
              marginBottom: "32px",
              fontFamily: "system-ui, sans-serif",
              fontSize: "11px",
              letterSpacing: "0.14em",
              textTransform: "uppercase" as const,
              color: "var(--gold)",
            }}
          >
            Now Accepting New Clients
          </div>

          <h1
            style={{
              fontFamily: "var(--font-display), Georgia, serif",
              fontSize: "clamp(2.25rem, 5vw, 3.75rem)",
              fontWeight: 400,
              color: "var(--chalk)",
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
              maxWidth: "800px",
              marginBottom: "24px",
            }}
          >
            Google Ads for Independent Medical Practices
          </h1>

          <p
            style={{
              fontSize: "1.0625rem",
              color: "var(--ash)",
              lineHeight: 1.75,
              maxWidth: "640px",
              marginBottom: "40px",
            }}
          >
            Organic SEO takes months. Google Ads puts your practice at the top of search results
            immediately — while your long-term visibility is being built. Primara manages the
            full paid search stack: Local Service Ads, search campaigns, and HIPAA-aware
            conversion tracking.
          </p>

          <div style={{ display: "flex", gap: "16px", flexWrap: "wrap" }}>
            <a
              href="tel:+15612912681"
              style={{
                display: "inline-flex",
                alignItems: "center",
                backgroundColor: "var(--ember)",
                color: "#fff",
                fontWeight: 700,
                padding: "0 1.5rem",
                height: "52px",
                borderRadius: "6px",
                textDecoration: "none",
                fontSize: "1rem",
              }}
            >
              Call (561) 291-2681
            </a>
            <Link
              href="/the-audit"
              style={{
                display: "inline-flex",
                alignItems: "center",
                border: "2px solid var(--wire)",
                color: "var(--chalk)",
                fontWeight: 600,
                padding: "0 1.5rem",
                height: "52px",
                borderRadius: "6px",
                textDecoration: "none",
                fontSize: "1rem",
              }}
            >
              Get a Free Audit
            </Link>
          </div>

          <p
            style={{
              marginTop: "20px",
              fontSize: "0.8125rem",
              color: "var(--smoke)",
            }}
          >
            Liam Costello &amp; Gio LaRoche, Co-Founders · Independent practices only · No long-term contracts
          </p>
        </div>
      </section>

      {/* Why ads for a medical practice */}
      <section style={{ backgroundColor: "var(--surface)", padding: "clamp(48px, 7vw, 80px) 0", borderBottom: "1px solid var(--wire)" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8">
          <div style={{ maxWidth: "760px" }}>
            <p
              style={{
                fontFamily: "system-ui, sans-serif",
                fontSize: "10px",
                letterSpacing: "0.2em",
                textTransform: "uppercase",
                color: "var(--smoke)",
                marginBottom: "24px",
              }}
            >
              Why It Works
            </p>
            <h2
              style={{
                fontFamily: "var(--font-display), Georgia, serif",
                fontSize: "clamp(1.5rem, 3vw, 2.25rem)",
                fontWeight: 400,
                color: "var(--chalk)",
                lineHeight: 1.2,
                marginBottom: "24px",
              }}
            >
              The patient searching &ldquo;primary care doctor accepting new patients&rdquo; is ready to call. Google Ads puts your number in front of them first.
            </h2>
            <p style={{ fontSize: "1rem", color: "var(--ash)", lineHeight: 1.8, marginBottom: "20px" }}>
              Healthcare advertising is categorically different from retail or service business ads. The compliance
              requirements are stricter, the keyword intent patterns are more specific, and the cost-per-lead math
              works differently when a new patient has a lifetime value of $3,000–$15,000 to your practice. Most general
              ad agencies have never navigated Google&rsquo;s healthcare and medicines policy, the LSA verification
              process for the healthcare vertical, or HIPAA-aware conversion tracking requirements.
            </p>
            <p style={{ fontSize: "1rem", color: "var(--ash)", lineHeight: 1.8 }}>
              Primara runs campaigns exclusively for independent primary care and mental health practices. We know
              which campaign structures work in this vertical, which ad copy formulations pass Google&rsquo;s healthcare
              review without being watered down to uselessness, and how to attribute new patients to the right channels
              without creating compliance exposure.
            </p>
          </div>
        </div>
      </section>

      {/* ROI framing */}
      <section style={{ backgroundColor: "var(--void)", padding: "clamp(40px, 6vw, 64px) 0", borderBottom: "1px solid var(--wire)" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8">
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
              gap: "1px",
              backgroundColor: "var(--wire)",
              border: "1px solid var(--wire)",
              borderRadius: "4px",
              overflow: "hidden",
            }}
          >
            {[
              { stat: "~$400–$700", label: "Typical cost per new patient\nacquired via paid search" },
              { stat: "$3,000–$15,000", label: "Average lifetime value of a\nnew primary care patient" },
              { stat: "3–5 new patients", label: "Required to break even on a\n$1,500/month ad spend" },
              { stat: "7–10 days", label: "From signed agreement to\nfirst live ad" },
            ].map(({ stat, label }) => (
              <div
                key={stat}
                style={{
                  backgroundColor: "var(--surface)",
                  padding: "clamp(24px, 3.5vw, 40px)",
                }}
              >
                <div
                  style={{
                    fontFamily: "var(--font-display), Georgia, serif",
                    fontStyle: "italic",
                    fontSize: "clamp(1.5rem, 3vw, 2.25rem)",
                    color: "var(--gold)",
                    lineHeight: 1.1,
                    marginBottom: "10px",
                  }}
                >
                  {stat}
                </div>
                <p
                  style={{
                    fontFamily: "system-ui, sans-serif",
                    fontSize: "0.8125rem",
                    color: "var(--ash)",
                    lineHeight: 1.6,
                    margin: 0,
                    whiteSpace: "pre-line",
                  }}
                >
                  {label}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Three ad types */}
      <section style={{ backgroundColor: "var(--void)", padding: "clamp(48px, 7vw, 80px) 0" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8">
          <p
            style={{
              fontFamily: "system-ui, sans-serif",
              fontSize: "10px",
              letterSpacing: "0.2em",
              textTransform: "uppercase",
              color: "var(--smoke)",
              marginBottom: "48px",
            }}
          >
            What We Build
          </p>

          <div style={{ display: "flex", flexDirection: "column", gap: "0" }}>
            {adTypes.map((type, idx) => (
              <div
                key={type.label}
                style={{
                  borderTop: "1px solid var(--wire)",
                  padding: "clamp(32px, 5vw, 56px) 0",
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: "clamp(32px, 5vw, 80px)",
                }}
                className="seo-pillar-grid"
              >
                {/* Left */}
                <div>
                  <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "16px" }}>
                    <span
                      style={{
                        fontFamily: "system-ui, sans-serif",
                        fontSize: "10px",
                        letterSpacing: "0.14em",
                        textTransform: "uppercase" as const,
                        color: "var(--smoke)",
                      }}
                    >
                      0{idx + 1}
                    </span>
                    <span
                      style={{
                        fontFamily: "system-ui, sans-serif",
                        fontSize: "10px",
                        letterSpacing: "0.12em",
                        textTransform: "uppercase" as const,
                        color: "var(--gold)",
                        border: "1px solid rgba(201,168,76,0.3)",
                        borderRadius: "2px",
                        padding: "3px 8px",
                      }}
                    >
                      {type.tag}
                    </span>
                  </div>
                  <h2
                    style={{
                      fontFamily: "var(--font-display), Georgia, serif",
                      fontSize: "clamp(1.25rem, 2.5vw, 1.875rem)",
                      fontWeight: 400,
                      color: "var(--chalk)",
                      lineHeight: 1.15,
                      marginBottom: "16px",
                    }}
                  >
                    {type.label}
                  </h2>
                  <p style={{ fontSize: "0.9375rem", color: "var(--ash)", lineHeight: 1.75 }}>
                    {type.body}
                  </p>
                </div>

                {/* Right */}
                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "12px" }}>
                  {type.items.map((item) => (
                    <li key={item} style={{ display: "flex", gap: "12px", alignItems: "flex-start" }}>
                      <span aria-hidden="true" style={{ color: "var(--gold)", flexShrink: 0, marginTop: "3px", fontSize: "0.875rem" }}>▸</span>
                      <span style={{ fontFamily: "system-ui, sans-serif", fontSize: "0.875rem", color: "var(--ash)", lineHeight: 1.65 }}>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pull quote */}
      <section style={{ backgroundColor: "var(--surface)", borderTop: "1px solid var(--wire)", borderBottom: "1px solid var(--wire)", padding: "clamp(40px, 6vw, 64px) 0" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8">
          <blockquote style={{ maxWidth: "720px" }}>
            <p
              style={{
                fontFamily: "var(--font-display), Georgia, serif",
                fontStyle: "italic",
                fontSize: "clamp(1.1rem, 2.5vw, 1.5rem)",
                color: "var(--chalk)",
                lineHeight: 1.5,
                marginBottom: "16px",
              }}
            >
              &ldquo;We only recommend starting Google Ads after the GBP and website foundation are in place. An
              ad that clicks through to a slow, low-trust website is wasted spend. The order matters.&rdquo;
            </p>
            <cite
              style={{
                fontFamily: "system-ui, sans-serif",
                fontSize: "0.8125rem",
                letterSpacing: "0.1em",
                textTransform: "uppercase" as const,
                color: "var(--smoke)",
                fontStyle: "normal",
              }}
            >
              — Liam Costello &amp; Gio LaRoche, Co-Founders, Primara
            </cite>
          </blockquote>
        </div>
      </section>

      {/* FAQ */}
      <section style={{ backgroundColor: "var(--void)", padding: "clamp(48px, 7vw, 80px) 0", borderBottom: "1px solid var(--wire)" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8">
          <p
            style={{
              fontFamily: "system-ui, sans-serif",
              fontSize: "10px",
              letterSpacing: "0.2em",
              textTransform: "uppercase",
              color: "var(--smoke)",
              marginBottom: "40px",
            }}
          >
            Common Questions
          </p>
          <div style={{ maxWidth: "720px", display: "flex", flexDirection: "column", gap: "0" }}>
            {faqs.map((faq, idx) => (
              <div
                key={idx}
                style={{
                  borderTop: "1px solid var(--wire)",
                  padding: "24px 0",
                }}
              >
                <h3
                  style={{
                    fontFamily: "var(--font-display), Georgia, serif",
                    fontSize: "1.0625rem",
                    fontWeight: 400,
                    color: "var(--chalk)",
                    marginBottom: "12px",
                    lineHeight: 1.3,
                  }}
                >
                  {faq.q}
                </h3>
                <p style={{ fontFamily: "system-ui, sans-serif", fontSize: "0.9375rem", color: "var(--ash)", lineHeight: 1.75, margin: 0 }}>
                  {faq.a}
                </p>
              </div>
            ))}
            <div style={{ borderTop: "1px solid var(--wire)" }} />
          </div>
        </div>
      </section>

      {/* Internal links */}
      <section style={{ backgroundColor: "var(--surface)", borderBottom: "1px solid var(--wire)", padding: "clamp(32px, 4vw, 48px) 0" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8">
          <p style={{ fontSize: "0.875rem", color: "var(--smoke)", marginBottom: "16px" }}>
            Related services
          </p>
          <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
            {[
              { href: "/services/seo", label: "SEO for Medical Practices" },
              { href: "/services/ai-seo", label: "AI SEO" },
              { href: "/services/google-business-profile", label: "Google Business Profile" },
              { href: "/services/medical-practice-website-design", label: "Website Design" },
              { href: "/services/online-reputation-management", label: "Reputation Management" },
              { href: "/results", label: "See the Results" },
            ].map(({ href, label }) => (
              <Link
                key={href}
                href={href}
                style={{
                  fontSize: "0.875rem",
                  color: "var(--ash)",
                  border: "1px solid var(--wire)",
                  borderRadius: "4px",
                  padding: "6px 14px",
                  textDecoration: "none",
                }}
              >
                {label}
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Related links (contextual internal linking) */}
      <RelatedLinks
        eyebrow="Related"
        heading="Related Services & Resources"
        items={[
          { href: "/services/patient-acquisition-ads", label: "Patient Acquisition Ads", description: "Paid search and Maps ads for practices that want patients faster than organic SEO alone." },
          { href: "/services/seo", label: "SEO", description: "The full SEO service — technical, on-page, and content — behind every specialty page like this one." },
          { href: "/specialties/trt-clinics", label: "TRT Clinics", description: "Marketing built specifically for independent TRT clinics competing with national telehealth brands." },
          { href: "/locations/google-ads-management-west-palm-beach", label: "Google Ads Management in West Palm Beach", description: "Google Ads management for practices in our home market." },
          { href: "/locations/google-ads-management-florida", label: "Google Ads Management in Florida", description: "Statewide Google Ads management for Florida practices, Miami to Jacksonville." },
          { href: "/locations/google-ads-management-lakeland", label: "Google Ads Management in Lakeland", description: "Search campaigns and Local Service Ads for practices in Lakeland and Polk County." },
        ]}
      />
      <section style={{ backgroundColor: "var(--color-primary)", borderTop: "3px solid var(--ember)" }}>
        <div className="mx-auto max-w-content px-6 lg:px-8 py-16 text-center">
          <h2
            style={{
              fontFamily: "var(--font-display), Georgia, serif",
              fontSize: "clamp(1.5rem, 3vw, 2.25rem)",
              fontWeight: 400,
              color: "var(--chalk)",
              marginBottom: "1rem",
            }}
          >
            Ready to Start Filling Your Schedule?
          </h2>
          <p style={{ color: "var(--ash)", marginBottom: "2rem", fontSize: "1rem" }}>
            We start with a free audit of your Google presence before recommending any ad spend.
          </p>
          <div style={{ display: "flex", justifyContent: "center", gap: "1rem", flexWrap: "wrap" }}>
            <a
              href="tel:+15612912681"
              style={{
                display: "inline-flex",
                alignItems: "center",
                backgroundColor: "var(--ember)",
                color: "#fff",
                fontWeight: 700,
                padding: "0 1.5rem",
                height: "52px",
                borderRadius: "6px",
                textDecoration: "none",
                fontSize: "1rem",
              }}
            >
              Call (561) 291-2681
            </a>
            <Link
              href="/the-audit"
              style={{
                display: "inline-flex",
                alignItems: "center",
                border: "2px solid #fff",
                color: "#fff",
                fontWeight: 700,
                padding: "0 1.5rem",
                height: "52px",
                borderRadius: "6px",
                textDecoration: "none",
                fontSize: "1rem",
              }}
            >
              Get My Free Audit
            </Link>
          </div>
          <p className="mt-6 text-sm" style={{ color: "rgba(255,255,255,0.5)" }}>
            Independent primary care &amp; mental health practices only · No long-term contracts ·{" "}
            <Link href="/services" style={{ color: "rgba(255,255,255,0.6)", textDecoration: "underline" }}>
              All Services
            </Link>
          </p>
        </div>
      </section>
    </main>
  );
}
