// ── Guides batch 8 — 2026-10-05 ────────────────────────────────────────────
// 10 guide/AEO rows from the Command Center queue (ids 635-644), built by the
// daily page factory. Built to ~/Primara-Clients/PAGE-STANDARD.md: answer box,
// 5 FAQs at 40-80 words marked up FAQPage, schema graph generated by
// app/guides/[slug]/page.tsx, outbound citations (Google / W3C / DOJ only).
// Inbound editorial links are planted as inline [text](/guides/slug) links in
// the body prose of existing guides (renderInline).

import type { Guide } from "@/lib/guides";

export const guidesPartEleven: Guide[] = [
  {
    slug: "what-ai-overviews-mean-for-a-medical-practices-organic-traffic",
    keyword: "what AI Overviews mean for a medical practice's organic traffic",
    category: "Playbook",
    title: "What Google AI Overviews Mean for a Medical Practice's Organic Traffic",
    metaTitle: "AI Overviews and Your Medical Practice's Traffic",
    metaDescription: "How Google AI Overviews change organic clicks for a medical practice, what to measure, and what to do about it. Call (561) 291-2681.",
    answer: "AI Overviews are Google's generated summaries at the top of some search results. They answer part of a question before anyone clicks, so informational searches can send fewer visitors to your site. Searches with local or booking intent, like 'family doctor near me,' depend far more on your Google Business Profile and a clear service page.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "What an AI Overview actually is"
      },
      {
        "type": "p",
        "text": "An AI Overview is a short generated summary that Google places above the normal results for some searches. It pulls together an answer from several web pages and shows links to the sources beside or beneath it. Google documents how its AI features choose pages in its Search Central guidance, and the main point for a practice owner is simple: the page that gets cited is the same kind of page that already ranks well, not a special format you have to buy."
      },
      {
        "type": "p",
        "text": "These summaries show up most often on broad, informational questions, such as what a symptom or a procedure involves, how a screening works, or how two treatment options differ. They show up far less often on searches where the person clearly wants a nearby provider, because the best answer to 'urgent care open now' is a map, not a paragraph."
      },
      {
        "type": "h2",
        "text": "Which of your searches are exposed, and which are not"
      },
      {
        "type": "p",
        "text": "Sort the searches that bring people to your site into two piles. The first pile is informational: 'what is a nerve block,' 'how long does a physical take.' Those are the searches where a summary can satisfy the reader without a click, so expect softer click-through there over time. The second pile is local and transactional: 'dermatologist near me,' 'primary care accepting new patients,' 'book a telehealth visit.' Those searches are decided by the map pack, your reviews, your hours, and a page that makes booking obvious. A summary does not replace any of that. You can control how some AI products use your pages, as our guide on [AI crawlers for a medical practice](/guides/should-a-medical-practice-allow-or-block-ai-crawlers) explains."
      },
      {
        "type": "p",
        "text": "For most independent practices the second pile is where new patients actually come from. A blog post that earned traffic from a general health question was never your best source of booked appointments, so a dip in that traffic is a smaller business problem than it looks on a chart."
      },
      {
        "type": "h2",
        "text": "How to measure whether it is hurting you"
      },
      {
        "type": "ol",
        "items": [
          "Open Google Search Console and compare the last 28 days to the same 28 days a quarter ago, filtered to your informational pages only.",
          "Look at impressions and clicks together. Impressions holding steady while clicks fall is the pattern you would expect when a summary answers the question above you.",
          "Separately, look at your Google Business Profile calls, direction requests, and website clicks. Those are the numbers that track booked patients.",
          "Check GA4 for form submissions and tracked phone calls. If those are flat or rising, the traffic you lost was not the traffic that paid you."
        ]
      },
      {
        "type": "p",
        "text": "Do not read a single week. Search traffic moves with seasons and with Google's own updates, so judge the change over a full month at minimum, and judge it against conversions rather than visits. Our guide on [measuring marketing ROI for a medical practice](/guides/how-to-measure-roi-on-medical-practice-marketing) walks through that setup."
      },
      {
        "type": "h2",
        "text": "What to do about it"
      },
      {
        "type": "ul",
        "items": [
          "Make informational pages worth citing: a clear answer in the first two sentences, specific details, a named author, and a real date. Google's own advice for AI features is the same advice it gives for ordinary ranking, so there is no separate trick.",
          "Put your effort into the pages that book patients: service pages, location pages, and a complete Google Business Profile. See [how to write a medical service page that ranks](/guides/how-to-write-a-medical-service-page-that-ranks).",
          "Write FAQ answers in plain sentences that stand alone, since short, direct answers are what summaries and voice assistants quote. Details are in [how to write patient FAQs that answer AI search](/guides/how-to-write-patient-faqs-that-answer-ai-search).",
          "Keep your name, address, phone number, and hours identical everywhere, because generated answers draw on listings as well as web pages.",
          "Never copy a generated answer onto your site as clinical advice. Anything medical on your pages should be reviewed and signed off by a licensed clinician on your team."
        ]
      }
    ],
    faqs: [
      {
        "q": "Will AI Overviews take all of my practice's website traffic?",
        "a": "No. They appear on some searches, mostly broad informational ones, and appear less on searches for a nearby provider. Traffic from informational questions may soften over time, while local and booking searches keep depending on your map listing, reviews, and service pages."
      },
      {
        "q": "Can I opt my practice out of AI Overviews?",
        "a": "Not as a separate switch. Google's published guidance says pages must be indexed and eligible for a snippet to be used in AI features, and the standard snippet controls apply. Blocking snippets also reduces how your pages appear in regular results, so most practices should not."
      },
      {
        "q": "Do I need to publish special content for AI Overviews?",
        "a": "Google states that no special optimization is required beyond good search practice. Pages that are helpful, clearly written, technically sound, and backed by real expertise are the ones with a chance of being cited, so improve those pages rather than inventing a new format."
      },
      {
        "q": "How do I know if I am being cited in an AI Overview?",
        "a": "There is no dedicated report today. Search your own key questions, scroll the summary and its source links, and note whether your pages appear. Search Console counts AI feature clicks within overall Search performance, so look for shifts there, not a separate line."
      },
      {
        "q": "Should I stop writing health information articles?",
        "a": "No, but expect them to bring awareness more than appointments. Keep publishing accurate, clinician-reviewed pages that answer real patient questions, and make sure each one leads to a clear next step, such as a service page, a booking link, or a tracked phone number."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "AI features and your website",
        "href": "https://developers.google.com/search/docs/appearance/ai-features"
      },
      {
        "publisher": "Google Search Central",
        "label": "Creating helpful, reliable, people-first content",
        "href": "https://developers.google.com/search/docs/fundamentals/creating-helpful-content"
      }
    ],
    links: [
      {
        "href": "/guides/get-a-medical-practice-into-ai-search-answers",
        "label": "Get a Medical Practice into AI Search Answers",
        "description": "The other side of this topic: earning the citation."
      },
      {
        "href": "/guides/how-to-write-patient-faqs-that-answer-ai-search",
        "label": "How to Write Patient FAQs That Answer AI Search",
        "description": "The answer format that summaries and voice assistants quote."
      },
      {
        "href": "/guides/how-to-measure-roi-on-medical-practice-marketing",
        "label": "How to Measure ROI on Medical Practice Marketing",
        "description": "Judge a traffic change by conversions, not visits."
      },
      {
        "href": "/services/ai-seo",
        "label": "AI SEO for Medical Practices",
        "description": "The service built around AI answer visibility."
      },
      {
        "href": "/locations/ai-seo-west-palm-beach",
        "label": "AI SEO in West Palm Beach",
        "description": "AI answer visibility applied to one real market."
      },
      {
        "href": "/locations/ai-seo-florida",
        "label": "AI SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "mobile-first-indexing-explained-for-a-medical-practice-website",
    keyword: "mobile-first indexing explained for a medical practice website",
    category: "How-to",
    title: "Mobile-First Indexing, Explained for a Medical Practice Website",
    metaTitle: "Mobile-First Indexing for a Medical Practice Site",
    metaDescription: "What mobile-first indexing means, how a practice site fails it, and a short checklist to fix it. Call (561) 291-2681.",
    answer: "Mobile-first indexing means Google reads the mobile version of your pages to decide how to index and rank them. If your phone version hides text, drops structured data, or blocks images that the desktop version shows, Google may never see that content. A medical practice site should show the same core content on both.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "What 'mobile-first' really means"
      },
      {
        "type": "p",
        "text": "Mobile-first indexing is about which version of your page Google crawls and stores, not about whether your site looks good on a phone. Google's crawler now primarily visits pages as a smartphone user would, and the content it finds that way is what gets indexed. If a paragraph, a table, or a block of markup exists only in the desktop layout, it is effectively invisible to the index. If you have not chosen a platform yet, read our comparison of [WordPress, Squarespace, Wix and Webflow](/guides/wordpress-vs-squarespace-vs-wix-vs-webflow-for-a-medical-practice) first."
      },
      {
        "type": "p",
        "text": "Google has applied this to the web for years, so almost every site is already evaluated this way. The practical question for you is not 'should I switch' but 'does my phone version contain everything I want to rank for.'"
      },
      {
        "type": "h2",
        "text": "How a practice website usually fails it"
      },
      {
        "type": "ul",
        "items": [
          "Content trimmed for small screens: a service page that shows three paragraphs on a laptop and a short blurb on a phone, with the rest removed rather than collapsed.",
          "Hidden or lazy-loaded sections that never load for a crawler, such as an FAQ that only appears after a script runs on tap.",
          "Structured data or meta tags present on the desktop template but missing on the mobile one, which happens when a site serves two separate versions.",
          "Images and video without crawlable tags or alt text on the mobile layout.",
          "A separate mobile subdomain with different content, different titles, or missing redirects between the two versions."
        ]
      },
      {
        "type": "p",
        "text": "Collapsed accordions are fine when the text is in the page's HTML and the content is not removed. The problem is text that is not in the HTML at all until a visitor does something."
      },
      {
        "type": "h2",
        "text": "A ten-minute check you can run yourself"
      },
      {
        "type": "ol",
        "items": [
          "Open your most important service page on your phone and read it top to bottom. Compare it to the desktop page and note anything missing.",
          "In Google Search Console, run the URL Inspection tool on that page and view the crawled page. Confirm your headings and main paragraphs appear in the rendered HTML.",
          "Check that your title, meta description, canonical tag, and schema match between versions.",
          "Confirm that your phone number is a tappable link and your booking button works with a thumb, because a page can be indexed perfectly and still lose the patient."
        ]
      },
      {
        "type": "p",
        "text": "Mobile usability and speed are separate topics. Page speed on phones is covered in our [Core Web Vitals checklist](/guides/core-web-vitals-checklist-for-a-medical-practice-website), and markup in our guide to [schema for a medical practice website](/guides/schema-markup-for-a-medical-practice-website-explained)."
      },
      {
        "type": "h2",
        "text": "What to do if you find gaps"
      },
      {
        "type": "p",
        "text": "The cleanest fix is a responsive design, one set of HTML that adapts to screen size, so there is only one version of each page to keep correct. If your site still serves a separate mobile version, put identical primary content, titles, and structured data on both, and keep the redirects between them accurate. If your site was built on an older theme, a rebuild on a responsive framework is often cheaper than patching two versions. Our [medical practice website design](/services/medical-practice-website-design) service starts from this requirement. Whichever version Google crawls should load securely over HTTPS; see [HTTPS, SSL certificates and mixed-content warnings on a medical practice website](/guides/https-ssl-certificates-and-mixed-content-warnings-on-a-medical-practice-website) for how to check it."
      }
    ],
    faqs: [
      {
        "q": "Is mobile-first indexing the same as having a mobile-friendly site?",
        "a": "No. Mobile-friendly describes how usable your page is on a phone. Mobile-first indexing describes which version Google reads to index it. A page can look fine on a phone and still lose rankings if the phone version contains less content than the desktop one."
      },
      {
        "q": "Does mobile-first indexing mean desktop visitors no longer matter?",
        "a": "No. It affects what Google crawls, not who visits. Plenty of patients still browse on desktops, especially for insurance and forms. Build one responsive site that serves both, rather than optimizing for one device and neglecting the other. Build one responsive site and test both views."
      },
      {
        "q": "Will an accordion or tabbed FAQ hurt my rankings?",
        "a": "Generally not, as long as the text is present in the page's HTML and not removed. Google's guidance says content hidden for usability reasons is acceptable. The risk is content that only loads after a user interaction, so test with the URL Inspection tool."
      },
      {
        "q": "How do I know Google is indexing my mobile version?",
        "a": "Search Console's page indexing information and the URL Inspection tool show the crawler Google used. Most established sites are already on smartphone crawling. If your property still reports a desktop crawler, treat that as a signal to review your setup."
      },
      {
        "q": "Do I need a separate mobile website?",
        "a": "No, and most practices should avoid one. A single responsive site is simpler, has no redirect problems, and keeps content and markup identical. Separate mobile URLs are a legacy approach that adds ways for the two versions to drift apart."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Mobile-first indexing best practices",
        "href": "https://developers.google.com/search/docs/crawling-indexing/mobile/mobile-sites-mobile-first-indexing"
      }
    ],
    links: [
      {
        "href": "/guides/core-web-vitals-checklist-for-a-medical-practice-website",
        "label": "Core Web Vitals Checklist",
        "description": "Mobile speed is a separate test from mobile indexing."
      },
      {
        "href": "/guides/schema-markup-for-a-medical-practice-website-explained",
        "label": "Schema Markup for a Medical Practice Website",
        "description": "The markup that must match on both versions."
      },
      {
        "href": "/guides/medical-website-launch-seo-checklist",
        "label": "Medical Website Launch SEO Checklist",
        "description": "Run this on any new or rebuilt site."
      },
      {
        "href": "/services/medical-practice-website-design",
        "label": "Medical Practice Website Design",
        "description": "Responsive build with one version of every page."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "Technical SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "nap-consistency-what-breaks-it-and-how-to-fix-it",
    keyword: "NAP consistency: what breaks it and how to fix it across the web",
    category: "Checklist",
    title: "NAP Consistency: What Breaks It and How to Fix It Across the Web",
    metaTitle: "NAP Consistency for a Medical Practice: Fix Guide",
    metaDescription: "What breaks name, address, and phone consistency for a medical practice and how to audit and fix it. Call (561) 291-2681.",
    answer: "NAP stands for name, address, and phone number. Consistency means your practice shows the same three details everywhere it is listed: Google, Apple Maps, Bing, insurance directories, and social profiles. Mismatches confuse Google about which listing is real, so find each one, choose one correct version, and correct the rest.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "What NAP consistency is and why it matters"
      },
      {
        "type": "p",
        "text": "Search engines build a picture of your practice by matching details across many sources. When the name, address, and phone number agree, the picture is clear. When one directory says 'Suite 200' and another says 'Ste. 2', or one lists a former phone number, the sources look like they describe different businesses, and a patient can land on the wrong one. A change of provider is one of the common causes of drift, so use our guide to [what to update when a provider joins or leaves a practice](/guides/what-to-update-when-a-provider-joins-or-leaves-a-medical-practice) as a checklist."
      },
      {
        "type": "p",
        "text": "This is mostly about trust and accuracy, not a secret ranking lever. Google's own guidelines for representing a business ask for the real-world name, address, and phone, and an inaccurate public listing sends patients to the wrong door, which is a worse problem than any ranking effect. The same matching rule applies to the map apps patients carry, and our guide on [Apple Business Connect and Bing Places](/guides/apple-maps-and-bing-places-for-a-medical-practice) explains how to claim them."
      },
      {
        "type": "h2",
        "text": "What usually breaks it in a medical practice"
      },
      {
        "type": "ul",
        "items": [
          "A move or suite change, where the website and Google are updated but older directories keep the old address.",
          "A rebrand or a name change after a partnership or acquisition, leaving the previous name on third-party sites.",
          "Several providers, each with their own listing under a different phone number or address.",
          "A tracking phone number on the website that differs from the number on Google. Dynamic number swapping is fine only when the main number is still listed everywhere as the primary.",
          "Small formatting differences like 'Dr.' versus 'MD,' abbreviations, or a legal name that differs from the signage name.",
          "Duplicate listings created by data aggregators, which keep a closed listing alive."
        ]
      },
      {
        "type": "h2",
        "text": "How to audit it in an afternoon"
      },
      {
        "type": "ol",
        "items": [
          "Write down the one correct version of your name, address, suite, and primary phone, exactly as it appears on your door and your Google Business Profile.",
          "Search your practice name and your phone number, both in quotes, and open the first several pages of results, not only page one.",
          "List every listing you find in a sheet: the site, the URL, the name shown, the address shown, the phone shown, and whether you control it.",
          "Mark every row that differs from your master version, even by punctuation, then sort by how many patients are likely to see it."
        ]
      },
      {
        "type": "p",
        "text": "Start with the sources patients actually use: your Google Business Profile, Apple Business Connect, Bing Places, your health system and insurer directories, and your major social profiles. If you need the full list of places that matter, see our [local citation building checklist](/guides/local-citation-building-checklist-for-a-medical-practice)."
      },
      {
        "type": "h2",
        "text": "Fixing mismatches without making it worse"
      },
      {
        "type": "p",
        "text": "Fix the sources you control first by logging in and editing the details. For listings you cannot edit, use the site's claim or suggest-an-edit process, and keep a record of what you submitted and when. Do not create a new listing to replace a wrong one, because that makes a duplicate. For Google specifically, follow our guide to [fixing duplicate Google Business Profile listings](/guides/fix-duplicate-google-business-profile-listings), and review changes Google suggests with [how to handle suggested edits](/guides/how-to-handle-google-business-profile-suggested-edits)."
      },
      {
        "type": "p",
        "text": "Then put a date on the calendar. Recheck every quarter, and recheck within a week of any move, rebrand, or phone change."
      }
    ],
    faqs: [
      {
        "q": "Does NAP consistency directly raise my Google ranking?",
        "a": "Google does not publish it as a standalone ranking factor. Accurate details help Google confirm which listing is yours and keep patients from reaching the wrong location, so the benefit is clarity and trust. Fix mismatches because they cost you patients, not as a ranking trick."
      },
      {
        "q": "Do small differences like 'Suite' versus 'Ste.' matter?",
        "a": "Minor abbreviations are usually understood, but use one consistent format everywhere so there is nothing to interpret. Differences that change the meaning, such as a different suite number, an old street, or another phone number, are the ones to correct first."
      },
      {
        "q": "What if a directory will not let me edit our listing?",
        "a": "Use its claim or report-a-problem process and keep screenshots of what you submitted. Some directories take weeks to update. Prioritize the sites patients actually use, and do not spend your time chasing obscure listings that nobody reads. Record each attempt so you can follow up later."
      },
      {
        "q": "Can a call-tracking number break NAP consistency?",
        "a": "It can if the tracking number replaces your real number on listings. Keep your main practice number as the primary on Google and directories, and use tracking numbers only on the website or in specific campaigns, with the main number still visible."
      },
      {
        "q": "How often should I check my listings?",
        "a": "Check quarterly as routine, and again right after a move, a rebrand, a new provider, or a phone change. Our monthly profile maintenance checklist covers the Google side. Directory mismatches tend to reappear slowly, so a calendar reminder beats a one-time cleanup."
      }
    ],
    citations: [
      {
        "publisher": "Google Business Profile Help",
        "label": "Guidelines for representing your business on Google",
        "href": "https://support.google.com/business/answer/3038177"
      },
      {
        "publisher": "Google Business Profile Help",
        "label": "Tips to improve your local ranking on Google",
        "href": "https://support.google.com/business/answer/7091"
      }
    ],
    links: [
      {
        "href": "/guides/local-citation-building-checklist-for-a-medical-practice",
        "label": "Local Citation Building Checklist",
        "description": "Where your listings should exist."
      },
      {
        "href": "/guides/fix-duplicate-google-business-profile-listings",
        "label": "Fix Duplicate Google Business Profile Listings",
        "description": "What to do when a mismatch becomes a duplicate."
      },
      {
        "href": "/guides/monthly-google-business-profile-maintenance-checklist",
        "label": "Monthly GBP Maintenance Checklist",
        "description": "The recurring check that catches drift."
      },
      {
        "href": "/services/google-business-profile",
        "label": "Google Business Profile Management",
        "description": "The service that keeps your primary listing accurate."
      },
      {
        "href": "/locations/gbp-optimization-west-palm-beach",
        "label": "GBP Optimization in West Palm Beach",
        "description": "Listing management applied to one real market."
      },
      {
        "href": "/locations/gbp-optimization-florida",
        "label": "GBP Optimization in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "how-to-migrate-a-medical-practice-website-to-a-new-domain",
    keyword: "how to migrate a medical practice website to a new domain without losing SEO",
    category: "Checklist",
    title: "How to Migrate a Medical Practice Website to a New Domain Without Losing SEO",
    metaTitle: "Move a Medical Practice Website to a New Domain",
    metaDescription: "A step-by-step plan to move a practice website to a new domain: redirects, Search Console, timing, and what to monitor. Call (561) 291-2681.",
    answer: "To move a medical practice website to a new domain without losing rankings, map every old URL to its closest new page, set permanent 301 redirects, keep the content the same during the move, tell Google through Search Console, and update your listings. Expect a temporary dip, and watch it for several weeks.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 7,
    sections: [
      {
        "type": "h2",
        "text": "Decide whether you really need to move"
      },
      {
        "type": "p",
        "text": "A domain change is a high-risk edit. Every ranking, link, and bookmark your site has earned is attached to the old address, and the move only works if you carry all of it across. Good reasons to move include a rebrand, a merger, or a long, hard-to-spell name. Weak reasons include a mild preference for a different ending. If the case is marginal, stay put. If you are also deciding how many sites to run, read our guide on [one site versus several for a multi-provider practice](/guides/single-site-vs-multiple-sites-for-a-multi-provider-practice) first."
      },
      {
        "type": "h2",
        "text": "Before launch: build the map"
      },
      {
        "type": "ol",
        "items": [
          "Crawl the old site and export every URL that returns a page, including blog posts, provider bios, and PDFs people link to.",
          "Pull your top pages from Search Console and your analytics so you know which URLs carry the most traffic and links.",
          "Create a spreadsheet matching each old URL to one new URL with the closest content. Avoid sending everything to the homepage, since Google treats blanket redirects like errors.",
          "Keep the structure, titles, headings, and copy as close to identical as you can. Redesign and move as two separate projects, not one.",
          "Set up the new domain with HTTPS, a sitemap, and a robots file that allows crawling. Confirm it is not blocked by a leftover staging setting."
        ]
      },
      {
        "type": "p",
        "text": "Our [medical website launch SEO checklist](/guides/medical-website-launch-seo-checklist) covers the pre-launch technical checks that apply to the new site as well."
      },
      {
        "type": "h2",
        "text": "Launch day: redirects and notification"
      },
      {
        "type": "p",
        "text": "Set a server-side 301 redirect from every old URL to its mapped new URL, and test a meaningful sample by hand, then every URL by script. A 301 tells search engines the move is permanent, so the old address's signals can pass to the new one. Avoid chains where one redirect points to another, and avoid temporary 302 redirects, which signal that the old address will return. If you are still deciding on the name itself, read our guide to [choosing a domain name for a medical practice](/guides/how-to-choose-a-domain-name-for-a-medical-practice) before you buy anything. Alongside the redirects, check that each new page names itself as canonical, a step covered in our guide on [canonical tags and duplicate content](/guides/canonical-tags-and-duplicate-content-on-a-medical-practice-website)."
      },
      {
        "type": "p",
        "text": "Then verify the new domain as a property in Google Search Console and use the Change of Address tool on the old property, as Google's site-move documentation describes. Submit the new sitemap. Update internal links so they point to the new domain directly rather than relying on redirects. After launch, keep checking for dead links with our guide to [finding and fixing broken links and 404 errors](/guides/how-to-find-and-fix-broken-links-and-404-errors-on-a-medical-practice-website). After the move, confirm the new domain serves every page over HTTPS and that no old http resources remain, as in our guide to [HTTPS, SSL certificates and mixed-content warnings](/guides/https-ssl-certificates-and-mixed-content-warnings-on-a-medical-practice-website)."
      },
      {
        "type": "h2",
        "text": "Everything outside the website"
      },
      {
        "type": "ul",
        "items": [
          "Update your Google Business Profile website field and re-check your name, address, and phone listings while you are in there, as covered in our [NAP consistency guide](/guides/nap-consistency-what-breaks-it-and-how-to-fix-it).",
          "Change the domain in Google Analytics and Google Ads landing page URLs, and confirm conversion tracking still fires on the new pages.",
          "Update business email if it uses the old domain. Keep the old domain's email working until nothing important depends on it.",
          "Contact the sites that link to you most, such as hospitals, associations, and directories, and ask them to update.",
          "Renew the old domain for at least a year, ideally indefinitely, and keep the redirects live."
        ]
      },
      {
        "type": "h2",
        "text": "What to expect and how to monitor"
      },
      {
        "type": "p",
        "text": "Rankings often fluctuate for a few weeks as Google reprocesses the move, and larger sites can take longer. Check Search Console daily at first for crawl errors and coverage, then weekly. Compare clicks and impressions for your top twenty pages against the pre-move baseline. If a page drops sharply and stays down, check its redirect first, because a wrong or missing redirect is the most common cause."
      }
    ],
    faqs: [
      {
        "q": "How long will rankings be affected after a domain move?",
        "a": "Many sites see a temporary dip while Google processes the redirects, often settling within a few weeks. Larger or more complex sites can take longer. Your outcome depends on how cleanly the redirects, content, and internal links were carried over, so a precise number cannot be promised."
      },
      {
        "q": "Should I redirect every old page or just the main ones?",
        "a": "Redirect every old URL that has a meaningful equivalent, not only the top pages. Smaller pages carry links and traffic too. For a page with no equivalent, a clear 404 or 410 is better than redirecting it to an unrelated page."
      },
      {
        "q": "Do I need to keep the old domain after the move?",
        "a": "Yes. Keep it registered and keep the 301 redirects live, ideally permanently. Letting the old domain expire lets someone else buy it and removes the redirects that send visitors and link value to your new site. Check the redirects with a crawl after launch to confirm they still work."
      },
      {
        "q": "Can I change the design and the domain at the same time?",
        "a": "It is better not to. Changing both at once makes it hard to tell what caused a ranking change. Move first with content and structure kept the same, confirm stability, then redesign on the new domain as a separate project."
      },
      {
        "q": "What is the Change of Address tool in Search Console?",
        "a": "It is a Google tool that tells Google your whole site has moved from one verified domain to another. It supports, but does not replace, correct 301 redirects. Use it after redirects are live, as Google's site-move guidance describes. Neither one replaces the other, so use both."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Site moves with URL changes",
        "href": "https://developers.google.com/search/docs/crawling-indexing/site-move-with-url-changes"
      },
      {
        "publisher": "Google Search Console Help",
        "label": "Change of Address tool",
        "href": "https://support.google.com/webmasters/answer/9370220"
      }
    ],
    links: [
      {
        "href": "/guides/medical-practice-rebrand-seo-checklist",
        "label": "Medical Practice Rebrand SEO Checklist",
        "description": "The rebrand side of a name and domain change."
      },
      {
        "href": "/guides/medical-website-launch-seo-checklist",
        "label": "Medical Website Launch SEO Checklist",
        "description": "Technical checks for the new site."
      },
      {
        "href": "/guides/single-site-vs-multiple-sites-for-a-multi-provider-practice",
        "label": "One Site or Several for a Multi-Provider Practice",
        "description": "Decide the domain structure before you migrate."
      },
      {
        "href": "/services/medical-practice-website-design",
        "label": "Medical Practice Website Design",
        "description": "Build or rebuild with the migration plan included."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "google-core-updates-how-to-tell-if-your-practice-site-was-hit",
    keyword: "what a Google core update is and how to tell if your practice site was hit",
    category: "How-to",
    title: "Google Core Updates: How to Tell if Your Practice Site Was Hit",
    metaTitle: "Google Core Update: Was Your Practice Site Hit?",
    metaDescription: "What a Google core update is, how to confirm your practice site was affected, and what to do next. Call (561) 291-2681.",
    answer: "A Google core update is a broad change to how Google's systems rank pages, announced a few times a year. To tell if your practice was hit, compare Search Console clicks and impressions for the two weeks after the rollout finishes against the two weeks before. A lasting drop that begins during the rollout window is the signal.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 7,
    sections: [
      {
        "type": "h2",
        "text": "What a core update is, and what it is not"
      },
      {
        "type": "p",
        "text": "Google makes small changes to search every day and larger, broad changes called core updates a few times a year. A core update is not a penalty aimed at your site. It reassesses how well pages meet what searchers are looking for, and some pages move up while others move down. Google publishes each one on its Search Status Dashboard with start and end dates, and Google's core update guidance says plainly that a drop does not mean something is broken."
      },
      {
        "type": "p",
        "text": "That matters for a practice owner, because a ranking dip during a rollout is usually a relative change. Other pages became more helpful to Google's systems than yours, rather than yours being flagged."
      },
      {
        "type": "h2",
        "text": "How to confirm it is the update and not something else"
      },
      {
        "type": "ol",
        "items": [
          "Find the rollout dates on the Google Search Status Dashboard. Wait until the update is marked complete, since results move during the rollout.",
          "In Search Console, compare the two full weeks after completion to the two weeks before the start, using the same days of the week.",
          "Filter by page and by query. A broad drop across many pages points to a core update. A drop on one page points to a page-level cause.",
          "Rule out your own changes: a site edit, a plugin update, a redirect, a robots change, or a template change in that window.",
          "Check the Security issues and Manual actions reports in Search Console. A manual action is a different problem with a different fix."
        ]
      },
      {
        "type": "p",
        "text": "Search is also seasonal. A cosmetic practice dips in some months, and a flu-related page spikes in others, so compare against the same period last year, not only the weeks before."
      },
      {
        "type": "h2",
        "text": "What to do once you are sure"
      },
      {
        "type": "p",
        "text": "Do not make rushed sitewide changes. Google's guidance for sites that dropped is to evaluate your content against its helpful, people-first content questions, not to chase a single factor. Look at the pages that lost the most and ask honestly: is this page thin, outdated, or generic, does a real clinician stand behind it, and does it answer the question better than the pages now ranking above it? Before you can investigate a dip, the site needs to be verified in Search Console; our guide on [how to set up and verify Google Search Console for a medical practice website](/guides/how-to-set-up-and-verify-google-search-console-for-a-medical-practice-website) covers the steps."
      },
      {
        "type": "ul",
        "items": [
          "Improve the pages that lost most: add original detail, current facts, a named author, and a visible date.",
          "Merge pages that cover the same intent, and remove the ones that add nothing.",
          "Strengthen the evidence of expertise, using our guide to [E-E-A-T for medical practices](/guides/what-is-eeat-and-why-it-matters-for-medical-practices).",
          "Review links pointing to your site, since low-quality link schemes carry risk, as covered in [backlinks for a medical practice](/guides/backlinks-for-a-medical-practice-safe-vs-penalized)."
        ]
      },
      {
        "type": "h2",
        "text": "Recovery takes patience"
      },
      {
        "type": "p",
        "text": "Google's guidance indicates that improvements may not show up until a later core update, since the systems reassess over time, and that recovery can take months. Record what you changed and when, so the next comparison is clean. Meanwhile, protect the channels that do not depend on this: your Google Business Profile and your reviews, covered in our [GBP patient acquisition guide](/guides/how-to-get-more-patients-from-google-business-profile)."
      }
    ],
    faqs: [
      {
        "q": "How often does Google run core updates?",
        "a": "Google has run them several times a year, announced with dates on its Search Status Dashboard. The timing is not fixed, and each rollout can take a couple of weeks. Check the dashboard rather than relying on a rumor, a blog post, or a social media post."
      },
      {
        "q": "Is a ranking drop after a core update a penalty?",
        "a": "No. Google says a core update is not a penalty and not a response to something a site did wrong. It reassesses relative page quality. A penalty is a manual action, which Search Console reports separately and notifies you about directly."
      },
      {
        "q": "Can I recover before the next core update?",
        "a": "Sometimes small gains appear sooner, but Google's guidance indicates that lasting recovery may need to wait for a later core update, as its systems reassess over time. Spend the interval improving real content quality instead of waiting for a particular date."
      },
      {
        "q": "Which pages should I fix first after a drop?",
        "a": "Start with pages that lost the most clicks and that also bring in patients, such as service and location pages. A lost informational article matters less than a lost service page. Use Search Console to rank pages by clicks lost."
      },
      {
        "q": "Should I hire someone to run a core update audit?",
        "a": "It can help if the loss is large and the cause is unclear, because an outside review spots patterns an owner is too close to see. Start with the free steps here, and bring in help if a clear, sustained decline remains unexplained."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Google Search core updates",
        "href": "https://developers.google.com/search/updates/core-updates"
      },
      {
        "publisher": "Google",
        "label": "Google Search Status Dashboard",
        "href": "https://status.search.google.com/"
      },
      {
        "publisher": "Google Search Central",
        "label": "Creating helpful, reliable, people-first content",
        "href": "https://developers.google.com/search/docs/fundamentals/creating-helpful-content"
      }
    ],
    links: [
      {
        "href": "/guides/what-is-eeat-and-why-it-matters-for-medical-practices",
        "label": "What Is E-E-A-T and Why It Matters",
        "description": "The quality signals that matter after an update."
      },
      {
        "href": "/guides/backlinks-for-a-medical-practice-safe-vs-penalized",
        "label": "Backlinks for a Medical Practice",
        "description": "Which links help and which put you at risk."
      },
      {
        "href": "/guides/how-to-run-a-local-seo-audit-for-a-medical-practice",
        "label": "How to Run a Local SEO Audit",
        "description": "A structured way to review the site."
      },
      {
        "href": "/services/seo",
        "label": "Medical SEO Services",
        "description": "Ongoing monitoring and content quality work."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-lakeland",
        "label": "Medical SEO in Lakeland",
        "description": "SEO applied to a second real market."
      }
    ],
  },
  {
    slug: "ada-web-accessibility-for-a-medical-practice-website",
    keyword: "ADA web accessibility for a medical practice website: what the law requires",
    category: "Checklist",
    title: "ADA Web Accessibility for a Medical Practice Website: What the Law Requires",
    metaTitle: "ADA Website Accessibility for Medical Practices",
    metaDescription: "What the ADA means for a medical practice website, what WCAG is, and a practical accessibility checklist. Call (561) 291-2681.",
    answer: "The Americans with Disabilities Act applies to medical practices as places of public accommodation, and the Department of Justice says it covers web content too. The law does not name one technical standard for private practices, but the Web Content Accessibility Guidelines (WCAG) are the usual benchmark. Aim for WCAG 2.1 Level AA, and have counsel confirm your obligations.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 7,
    sections: [
      {
        "type": "h2",
        "text": "What the law says, in plain language"
      },
      {
        "type": "p",
        "text": "Title III of the ADA requires businesses open to the public, including medical practices, to give people with disabilities equal access to their services. The Department of Justice's web guidance states that this applies to websites, not only buildings. At the same time, that guidance notes the ADA does not set out a specific technical standard for private businesses' websites, so you will not find a line in the statute that says 'use this exact rule.'"
      },
      {
        "type": "p",
        "text": "In practice, courts, regulators, and settlement agreements point to WCAG, the guidelines published by the W3C, and most commonly to Level AA. Some rules for state and local government websites name a specific WCAG version. Separately, healthcare providers that receive federal health funding may face disability rules from the Department of Health and Human Services that reference WCAG. The details and dates have changed over time, so ask your attorney which rules apply to your practice. This page is general information, not legal advice."
      },
      {
        "type": "h2",
        "text": "Why a medical practice is a likely target"
      },
      {
        "type": "p",
        "text": "Patients use your site to find a doctor, read about conditions, book, and pay. That includes people who are blind, have low vision, are deaf or hard of hearing, have motor limitations, or have cognitive differences. If your booking form cannot be used with a keyboard, or your PDF intake forms cannot be read by a screen reader, those patients cannot become patients. Demand letters and lawsuits over inaccessible sites are a known risk for small businesses, and a clean site is the cheapest protection. Alt text is one of the most concrete fixes, and we explain how to write it in our guide to [image SEO and alt text for a medical practice](/guides/image-seo-and-alt-text-for-a-medical-practice-website). Captions and transcripts for video are part of the same obligation to be usable, and our guide on [video on a medical practice website](/guides/video-on-a-medical-practice-website-transcripts-captions-and-video-schema) explains how to add them."
      },
      {
        "type": "h2",
        "text": "A practical checklist"
      },
      {
        "type": "ul",
        "items": [
          "Text alternatives: every meaningful image has descriptive alt text, and decorative images have empty alt text.",
          "Color contrast: body text and buttons meet WCAG's minimum contrast ratios against their background.",
          "Keyboard access: every link, menu, form, and button works without a mouse, and the focus outline is visible.",
          "Forms: every field has a visible label, errors are described in text, and required fields are marked in words, not only color.",
          "Headings and structure: one H1, headings in logical order, and descriptive link text rather than 'click here.'",
          "Video and audio: captions on videos and a transcript for audio.",
          "Documents: intake forms and PDFs are tagged and readable, or offered as accessible web forms.",
          "No auto-playing media, and pop-ups that can be closed by keyboard."
        ]
      },
      {
        "type": "h2",
        "text": "Overlays are not a fix"
      },
      {
        "type": "p",
        "text": "Accessibility 'overlay' widgets that promise instant compliance with one line of code do not fix the underlying markup, and sites that use them have still been sued. Fix the template itself. Then test with a keyboard, with a screen reader such as the one built into your phone, and with an automated checker, knowing that automated tools catch only part of the problems."
      },
      {
        "type": "p",
        "text": "Accessibility and technical SEO overlap, because clean headings, labeled forms, and alt text help search engines too. When you build a new site, make it a requirement, as in our [medical practice website design](/services/medical-practice-website-design) approach, and include it in your [website launch checklist](/guides/medical-website-launch-seo-checklist). Heading order is one of the simplest accessibility wins, and our guide on [heading structure from H1 to H3](/guides/heading-structure-h1-to-h3-for-a-medical-practice-web-page) shows how to outline a page so screen reader users can jump through it."
      }
    ],
    faqs: [
      {
        "q": "Does the ADA require my practice's website to be accessible?",
        "a": "The Department of Justice's guidance says the ADA applies to the web content of businesses open to the public, which includes medical practices. It does not prescribe one technical standard for private websites, so practices usually follow WCAG 2.1 Level AA as the working benchmark."
      },
      {
        "q": "What is WCAG?",
        "a": "WCAG, the Web Content Accessibility Guidelines, is a set of testable criteria from the W3C covering things like text alternatives, contrast, keyboard use, and clear forms. It has three conformance levels, A, AA, and AAA, and Level AA is the one most commonly referenced."
      },
      {
        "q": "Can I fix accessibility with a plugin or overlay?",
        "a": "Not reliably. Overlays do not repair the underlying code, and businesses using them have still received complaints. Fix alt text, contrast, labels, and keyboard access in the site itself, and treat any tool as a checker, not a cure. Retest after every site update, since new content can reintroduce old problems."
      },
      {
        "q": "Do my PDF intake forms have to be accessible too?",
        "a": "Yes, content you publish for patients should be usable by people with disabilities. Offer a tagged, screen-reader-friendly PDF or, better, an accessible web form. Keep PHI out of any form that is not secured, and ask your attorney about requirements."
      },
      {
        "q": "How do I test my site without special software?",
        "a": "Try navigating with only the Tab and Enter keys, zoom the page to two hundred percent, and turn on your phone's built-in screen reader for a page. Then run an automated checker. These steps will not prove compliance, but they surface the largest barriers."
      }
    ],
    citations: [
      {
        "publisher": "U.S. Department of Justice",
        "label": "Guidance on Web Accessibility and the ADA",
        "href": "https://www.ada.gov/resources/web-guidance/"
      },
      {
        "publisher": "W3C Web Accessibility Initiative",
        "label": "Web Content Accessibility Guidelines (WCAG) overview",
        "href": "https://www.w3.org/WAI/standards-guidelines/wcag/"
      }
    ],
    links: [
      {
        "href": "/guides/medical-website-launch-seo-checklist",
        "label": "Medical Website Launch SEO Checklist",
        "description": "Add accessibility to your pre-launch checks."
      },
      {
        "href": "/guides/hipaa-safe-tracking-for-a-medical-website",
        "label": "HIPAA-Safe Tracking for a Medical Website",
        "description": "The privacy side of a compliant site."
      },
      {
        "href": "/guides/how-to-write-a-medical-service-page-that-ranks",
        "label": "How to Write a Medical Service Page That Ranks",
        "description": "Clear structure that helps readers and search engines."
      },
      {
        "href": "/services/medical-practice-website-design",
        "label": "Medical Practice Website Design",
        "description": "Accessibility built into the template."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "google-knowledge-panel-for-a-medical-practice",
    keyword: "what a Knowledge Panel is and whether a medical practice can get one",
    category: "How-to",
    title: "What a Google Knowledge Panel Is and Whether a Medical Practice Can Get One",
    metaTitle: "Google Knowledge Panel for a Medical Practice",
    metaDescription: "What a Knowledge Panel is, how it differs from a Business Profile, and how a practice or doctor can claim one. Call (561) 291-2681.",
    answer: "A Knowledge Panel is the information box Google shows for a person, organization, or topic it recognizes as a distinct entity. It is different from a Business Profile, which is the listing for a local place. A practice cannot buy a panel, but it can earn one and, once one exists, claim and suggest edits to it.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "Knowledge Panel versus Business Profile"
      },
      {
        "type": "p",
        "text": "Most practice owners have seen two kinds of boxes. A Business Profile appears for a local business, with a map, hours, reviews, and a call button, and you manage it in Google Business Profile Manager. A Knowledge Panel is built from Google's knowledge graph and shows facts about an entity, such as a physician, a hospital system, an association, or a well-known organization. Local practices usually show the first and not the second, and that is normal."
      },
      {
        "type": "p",
        "text": "The difference matters because the fixes differ. Wrong hours or a wrong phone number belong in your Business Profile. A wrong description or photo in a panel about a person or organization is handled through the panel's own feedback and claim process. Assistants and panels can disagree about the same practice, so our guide to [checking AI assistant answers](/guides/how-to-check-if-ai-assistants-mention-your-medical-practice) shows how to compare them."
      },
      {
        "type": "h2",
        "text": "How Google decides to show a panel"
      },
      {
        "type": "p",
        "text": "Google does not accept applications. Its systems assemble a panel when they find enough consistent, reliable information about an entity across the web, such as an official website, structured data, and independent sources that describe it. A new or small practice often has too little independent coverage for the systems to be confident, so no panel appears. That is a data problem, not a penalty. Other map products show their own place cards, and our guide on [Apple Maps and Bing Places](/guides/apple-maps-and-bing-places-for-a-medical-practice) explains how to claim them. Valid structured data on your own site is one of the consistent signals Google can use, so test it with the routine in [how to test and validate structured data](/guides/how-to-test-and-validate-structured-data-on-a-medical-practice-website)."
      },
      {
        "type": "h2",
        "text": "What you can do to make a panel more likely"
      },
      {
        "type": "ul",
        "items": [
          "Publish a clear About page with the practice's full name, address, phone, and the names and credentials of its licensed clinicians, each stated accurately.",
          "Add Organization or MedicalBusiness markup to the site, with sameAs links to your official profiles, as described in our guide to [schema markup for a medical practice website](/guides/schema-markup-for-a-medical-practice-website-explained).",
          "Keep the practice's details identical everywhere. See the [NAP consistency guide](/guides/nap-consistency-what-breaks-it-and-how-to-fix-it).",
          "Earn real mentions in the places that describe you independently, such as a hospital affiliation page, a medical society directory, or local news coverage. Our [press release guide](/guides/press-release-for-a-medical-practice-that-helps-seo) explains what is worth doing.",
          "Do not invent a Wikipedia article or a Wikidata entry for a practice that does not meet their notability rules. Entries that are created for promotion are usually deleted and can hurt trust."
        ]
      },
      {
        "type": "h2",
        "text": "If a panel already exists"
      },
      {
        "type": "p",
        "text": "If a panel appears for you or your practice, look for the option to verify and claim it, which Google's help documentation explains. Once you are verified, you can suggest changes to information, such as a corrected description or a better photo. Google reviews suggestions and decides what to show, so you can request but not dictate. A verified owner can also usually update the links to official profiles."
      },
      {
        "type": "p",
        "text": "If the panel shows something false, use the feedback link on the panel itself and provide a source that proves the correct fact. Medical claims about conditions or outcomes should never be added by a practice to promote itself. Use only accurate, verifiable facts about who you are and where you practice."
      }
    ],
    faqs: [
      {
        "q": "Is a Knowledge Panel the same as my Google Business Profile?",
        "a": "No. A Business Profile is the local listing for a place, managed in Business Profile Manager. A Knowledge Panel describes a person, organization, or topic Google recognizes as an entity. A practice can have a profile and no panel, which is common and not a problem."
      },
      {
        "q": "Can I pay Google for a Knowledge Panel?",
        "a": "No. Google does not sell panels or take applications. Panels are generated from information the systems find and trust across the web. You can improve the underlying signals, then claim and suggest edits to a panel once it exists. Keep your Business Profile accurate meanwhile, since that listing is the one patients use."
      },
      {
        "q": "Does an individual doctor get a Knowledge Panel?",
        "a": "Sometimes, when Google finds enough consistent, reliable information about the person, such as a faculty page, publications, or a professional listing. There is no guaranteed route. Accurate bios, markup, and independent coverage make recognition more likely, but nothing forces it."
      },
      {
        "q": "Do I need a Wikipedia page to get a panel?",
        "a": "No. Many panels draw on other sources, and most local practices do not meet Wikipedia's notability standards. Creating a page just to trigger a panel is a poor idea. Focus on a solid website, consistent listings, and genuine third-party mentions."
      },
      {
        "q": "How do I fix wrong information in a Knowledge Panel?",
        "a": "Use the feedback option on the panel, or the suggest-edit feature after you have verified and claimed it, and attach a source for the correction. Google makes the final call and changes can take time, so be specific and keep a record of what you submitted."
      }
    ],
    citations: [
      {
        "publisher": "Google Knowledge Panel Help",
        "label": "Get verified on Google",
        "href": "https://support.google.com/knowledgepanel/answer/7534842"
      },
      {
        "publisher": "Google Search Central",
        "label": "Organization structured data",
        "href": "https://developers.google.com/search/docs/appearance/structured-data/organization"
      }
    ],
    links: [
      {
        "href": "/guides/schema-markup-for-a-medical-practice-website-explained",
        "label": "Schema Markup for a Medical Practice Website",
        "description": "The markup that helps Google recognize your entity."
      },
      {
        "href": "/guides/nap-consistency-what-breaks-it-and-how-to-fix-it",
        "label": "NAP Consistency Guide",
        "description": "Consistent facts are the base of any panel."
      },
      {
        "href": "/guides/press-release-for-a-medical-practice-that-helps-seo",
        "label": "Press Release for a Medical Practice",
        "description": "Earn independent mentions the right way."
      },
      {
        "href": "/services/google-business-profile",
        "label": "Google Business Profile Management",
        "description": "The local listing you can control today."
      },
      {
        "href": "/locations/gbp-optimization-west-palm-beach",
        "label": "GBP Optimization in West Palm Beach",
        "description": "Listing management applied to one real market."
      },
      {
        "href": "/locations/gbp-optimization-florida",
        "label": "GBP Optimization in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "fix-wrong-information-about-your-practice-in-an-ai-chatbot-answer",
    keyword: "how to fix wrong information about your practice in an AI chatbot answer",
    category: "Playbook",
    title: "How to Fix Wrong Information About Your Practice in an AI Chatbot Answer",
    metaTitle: "Fix Wrong Practice Info in AI Chatbot Answers",
    metaDescription: "What to do when ChatGPT, Gemini, or another AI chatbot gets your practice's hours, services, or address wrong. Call (561) 291-2681.",
    answer: "You cannot edit an AI chatbot's answer directly, so fix the sources it draws from. First, document the error. Second, correct your website, Google Business Profile, and directory listings so they agree. Third, use the chatbot's built-in feedback option. Then recheck in a few weeks, because answers change as sources update.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "Why a chatbot gets your practice wrong"
      },
      {
        "type": "p",
        "text": "AI assistants build an answer from what they learned in training and, when they search the web, from pages they retrieve. If your old address is still on a directory, your site never states the services you offer, or another practice has a similar name, the assistant may repeat the wrong version with complete confidence. It is not reading your mind or your files. It is reflecting the weight of what is written about you online. To find those wrong answers in the first place, follow our guide to [checking whether AI assistants mention your medical practice](/guides/how-to-check-if-ai-assistants-mention-your-medical-practice)."
      },
      {
        "type": "p",
        "text": "That means the practical fix is rarely about the chatbot. It is about making the truth easy to find, consistent, and stated more clearly than the error."
      },
      {
        "type": "h2",
        "text": "Step one: document the problem"
      },
      {
        "type": "ol",
        "items": [
          "Ask the question the way a patient would, such as 'What are the hours of [practice name] in [city]?' Record the exact wording of the answer.",
          "Save a screenshot with the date, the tool, and the prompt. You will use it to measure progress.",
          "Test the same question in two or three other assistants and in Google, so you know whether it is one tool or the whole web.",
          "Note whether the wrong fact is a name, an address, a phone number, a service you do not offer, or a clinician who left."
        ]
      },
      {
        "type": "h2",
        "text": "Step two: fix the sources"
      },
      {
        "type": "p",
        "text": "Look for where the false fact lives. Search the wrong detail in quotes. Common culprits are old directory entries, a past website page, an outdated Google Business Profile service list, or a former provider's bio. Correct each one, starting with the sources you control. Our [NAP consistency guide](/guides/nap-consistency-what-breaks-it-and-how-to-fix-it) shows how to audit and correct listings. Update your [Google Business Profile services list](/guides/google-business-profile-services-list-optimization) too, since it is a widely used source."
      },
      {
        "type": "p",
        "text": "Then state the facts plainly on your own site. A page with your name, address, hours, accepted insurance, and services, written in short, direct sentences, gives any assistant a clean source. Use FAQ markup for the questions patients ask, as covered in our guide to [patient FAQs that answer AI search](/guides/how-to-write-patient-faqs-that-answer-ai-search)."
      },
      {
        "type": "h2",
        "text": "Step three: use the feedback tools, carefully"
      },
      {
        "type": "ul",
        "items": [
          "Use the thumbs-down or report option in the assistant, and describe the error and the correct fact in one or two sentences.",
          "For Google's AI features, use the feedback link on the result, and see Google's guidance on how those features draw on pages in its Search Central documentation.",
          "Do not paste patient information or anything clinical into a feedback form. State public business facts only.",
          "Do not try to hide or remove accurate negative reviews from your listings. Only correct false statements."
        ]
      },
      {
        "type": "h2",
        "text": "Recheck and keep it from coming back"
      },
      {
        "type": "p",
        "text": "Retest the same prompts after two to four weeks and again after a few months, and log the dates. Corrections can take a while to appear, and some assistants will not change at all until their data refreshes. Add this to your quarterly listing check so a new error is caught early. If AI-generated answers about you keep going wrong, the underlying issue is usually inconsistent or thin source data, which is the work described in [how to get a medical practice into AI search answers](/guides/get-a-medical-practice-into-ai-search-answers)."
      }
    ],
    faqs: [
      {
        "q": "Can I ask an AI company to remove wrong information about my practice?",
        "a": "You can submit feedback, and some providers have a process for reporting inaccurate information about a business. There is no guarantee of a quick change. The more reliable path is fixing the web sources the answer draws from and stating your facts clearly on your own site."
      },
      {
        "q": "Why does the chatbot still show the old address after I updated my site?",
        "a": "The assistant may rely on older training data or on directories that still show the old address. Update every listing you can find, wait for sources to refresh, and retest. Some answers lag by weeks or longer. Retest every few weeks and keep dated screenshots of each answer."
      },
      {
        "q": "Should I be worried about a chatbot giving medical advice that mentions my practice?",
        "a": "Do not rely on a chatbot for clinical guidance, and do not add clinical claims to your site to counter it. Keep your pages factual and clinician-reviewed, and report clearly false statements through the tool's feedback process. Report only public business facts, never patient details."
      },
      {
        "q": "Does structured data help a chatbot get my facts right?",
        "a": "It can help machines read your pages correctly, and Google documents using markup to describe an organization. It is not a switch that forces any assistant to repeat it, so use markup alongside consistent listings and clear page copy. Measure the results by retesting your key prompts."
      },
      {
        "q": "How often should I check what AI assistants say about us?",
        "a": "Test a short list of patient-style questions every quarter, and again after any move, name change, phone change, or provider change. Keep dated screenshots so you can see whether answers are improving or whether a new error appeared. Compare each result with your earlier screenshots."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "AI features and your website",
        "href": "https://developers.google.com/search/docs/appearance/ai-features"
      },
      {
        "publisher": "Google Search Central",
        "label": "Organization structured data",
        "href": "https://developers.google.com/search/docs/appearance/structured-data/organization"
      }
    ],
    links: [
      {
        "href": "/guides/get-a-medical-practice-into-ai-search-answers",
        "label": "Get a Medical Practice into AI Search Answers",
        "description": "The positive side of this topic."
      },
      {
        "href": "/guides/how-to-write-patient-faqs-that-answer-ai-search",
        "label": "How to Write Patient FAQs That Answer AI Search",
        "description": "Give assistants a clean source to quote."
      },
      {
        "href": "/guides/nap-consistency-what-breaks-it-and-how-to-fix-it",
        "label": "NAP Consistency Guide",
        "description": "Fix the listings that feed wrong answers."
      },
      {
        "href": "/services/ai-seo",
        "label": "AI SEO for Medical Practices",
        "description": "The service built around AI answer accuracy."
      },
      {
        "href": "/locations/ai-seo-west-palm-beach",
        "label": "AI SEO in West Palm Beach",
        "description": "AI answer visibility in one real market."
      },
      {
        "href": "/locations/ai-seo-florida",
        "label": "AI SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "how-often-to-update-old-content-on-a-medical-practice-website",
    keyword: "how often to update old content on a medical practice website to keep it ranking",
    category: "Playbook",
    title: "How Often to Update Old Content on a Medical Practice Website",
    metaTitle: "How Often to Refresh Medical Practice Web Content",
    metaDescription: "How often to review and update old pages on a medical practice site, which pages come first, and what a real update looks like. Call (561) 291-2681.",
    answer: "Review every page at least once a year, and your highest-value pages, such as service and location pages, every quarter. Update a page when the facts change, when its clicks decline, or when a clinician reviews it and finds something outdated. Change the date only when the content genuinely changed.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "Why old pages lose ground"
      },
      {
        "type": "p",
        "text": "Content decay is the slow loss of clicks as a page ages. The facts get stale, competing pages get fresher and more complete, and the page no longer answers the question as well as it once did. A practice website has an extra reason to care: outdated information is not only a ranking problem, it can be wrong. A page that lists a retired provider, an old insurance plan, a former address, or a discontinued service sends patients to the wrong place."
      },
      {
        "type": "p",
        "text": "Google's guidance on helpful content asks whether your content is accurate and kept up to date. That is a quality question, not a calendar trick, so a page refreshed for the sake of a new date helps nobody."
      },
      {
        "type": "h2",
        "text": "A cadence that fits a small practice"
      },
      {
        "type": "ul",
        "items": [
          "Quarterly: service pages, location pages, the About page, insurance and pricing information, and your contact page. Check providers, hours, phone, address, and services.",
          "Twice a year: your top ten pages by Search Console clicks, plus anything that shows a clear decline.",
          "Annually: every blog article and guide, with a clinician reading anything medical.",
          "Immediately: any page affected by a new provider, a departure, a move, a new service, a policy change, or a rule change."
        ]
      },
      {
        "type": "p",
        "text": "Put the dates on a shared calendar with a named owner. A refresh that belongs to everyone belongs to no one."
      },
      {
        "type": "h2",
        "text": "How to pick what to update first"
      },
      {
        "type": "ol",
        "items": [
          "In Search Console, compare the last three months to the prior three months by page, and sort by clicks lost.",
          "Mark pages whose average position slipped from the top five or ten, since those are the cheapest to win back.",
          "Keep the pages that earn appointments at the top of the list, ahead of articles that earn only visits.",
          "Skip pages with little traffic and no purpose. Merge or remove them, using the guidance in our [local SEO audit guide](/guides/how-to-run-a-local-seo-audit-for-a-medical-practice)."
        ]
      },
      {
        "type": "p",
        "text": "This keeps the work small and focused, and it ties updates to results instead of habit."
      },
      {
        "type": "h2",
        "text": "What counts as a real update"
      },
      {
        "type": "p",
        "text": "A real refresh fixes inaccurate facts, adds information a reader would now expect, tightens the answer at the top, adds or checks FAQs, updates citations to current sources, and checks that links still work. A clinician should read medical content and sign off. After that, update the visible date and the structured data's date together, as Google's guidance on publication dates recommends, and only when the page truly changed. Seasonal pages are a good example: update the same page each year rather than publishing a new one, as covered in [seasonal service pages for a medical practice](/guides/seasonal-service-pages-for-a-medical-practice-flu-shots-and-school-physicals)."
      },
      {
        "type": "p",
        "text": "Avoid two traps. Do not rewrite a page that ranks well just to change it, and do not republish near-identical text with a new date. Both waste time, and the second can look like manipulation. Pair this routine with your [content calendar](/guides/medical-practice-content-calendar-checklist), and read our view on [how often to blog](/guides/should-a-medical-practice-blog-and-how-often) so new publishing and updating share one plan."
      }
    ],
    faqs: [
      {
        "q": "Does changing the publish date improve rankings?",
        "a": "Not by itself. Google's guidance says to show dates accurately and update them when content is significantly updated. Changing a date without changing the page is misleading to readers and does not replace real improvements to accuracy and usefulness. Only update the date when the content truly changed."
      },
      {
        "q": "How do I know a page needs an update?",
        "a": "Look for falling clicks or impressions in Search Console, facts that have changed in your practice, broken links, outdated sources, or a competitor page that now answers the question more completely. Any one of these is a reason to review the page."
      },
      {
        "q": "Should a clinician review every update?",
        "a": "Yes for anything medical. Business facts like hours can be checked by staff, but statements about conditions or care should be reviewed by a licensed clinician at the practice. That also supports the expertise signals covered in our E-E-A-T guide."
      },
      {
        "q": "Is it better to update old posts or publish new ones?",
        "a": "Both matter, but updating an existing page that already has links and history is often the faster win. New pages cover topics you do not yet address. Use Search Console to decide which gap is bigger. Search Console shows which gap costs you more clicks."
      },
      {
        "q": "What should I do with outdated pages I do not want?",
        "a": "If a page has no traffic, no links, and no purpose, remove it with a redirect to the closest useful page, or merge its best parts into a stronger page. Do not leave thin, outdated pages sitting on the site."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Creating helpful, reliable, people-first content",
        "href": "https://developers.google.com/search/docs/fundamentals/creating-helpful-content"
      },
      {
        "publisher": "Google Search Central",
        "label": "Influence your byline dates in Google Search",
        "href": "https://developers.google.com/search/docs/appearance/publication-dates"
      }
    ],
    links: [
      {
        "href": "/guides/medical-practice-content-calendar-checklist",
        "label": "Medical Practice Content Calendar Checklist",
        "description": "Schedule updates next to new posts."
      },
      {
        "href": "/guides/should-a-medical-practice-blog-and-how-often",
        "label": "Should a Medical Practice Blog, and How Often",
        "description": "The new-content half of the plan."
      },
      {
        "href": "/guides/how-to-run-a-local-seo-audit-for-a-medical-practice",
        "label": "How to Run a Local SEO Audit",
        "description": "Find the pages that need work."
      },
      {
        "href": "/services/seo",
        "label": "Medical SEO Services",
        "description": "Ongoing content review and updates."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-lakeland",
        "label": "Medical SEO in Lakeland",
        "description": "SEO applied to a second real market."
      }
    ],
  },
  {
    slug: "local-pack-vs-organic-results-vs-google-ads-for-a-medical-practice",
    keyword: "local pack vs organic results vs Google Ads: where a limited budget should go first",
    category: "Comparison",
    title: "Local Pack vs Organic Results vs Google Ads: Where a Practice Budget Should Go First",
    metaTitle: "Local Pack vs Organic vs Google Ads for a Practice",
    metaDescription: "Where a limited marketing budget should go first for a medical practice: map pack, organic search, or Google Ads. Call (561) 291-2681.",
    answer: "For most single-location practices, spend first on the local pack by completing your Google Business Profile and earning reviews, because it costs the least and sits above organic results for nearby searches. Fix your service pages second. Add Google Ads third, when the foundation can convert the clicks you pay for.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 7,
    sections: [
      {
        "type": "h2",
        "text": "The three places a practice can show up"
      },
      {
        "type": "p",
        "text": "A search for a nearby provider can show three kinds of results. The local pack is the map and three listings pulled from Google Business Profiles. Organic results are the regular blue links to web pages. Ads sit at the top and bottom, labeled as sponsored, and you pay when someone clicks. Each has a different cost, a different speed, and a different job. Because results differ by location, a single manual search misleads, which our guide on [tracking local rankings](/guides/how-to-track-local-search-rankings-for-a-medical-practice) explains."
      },
      {
        "type": "h2",
        "text": "How they compare"
      },
      {
        "type": "table",
        "headers": [
          "Channel",
          "What it costs, how fast it works, and what it is best for"
        ],
        "rows": [
          [
            "Local pack",
            "Costs time, reviews, and profile upkeep. Works in weeks to months. Best for 'near me' and urgent searches."
          ],
          [
            "Organic results",
            "Costs content and technical work. Works over months. Best for questions, comparisons, and service research."
          ],
          [
            "Google Ads",
            "Costs money per click, ongoing. Works in days. Best for fast demand, new services, and new locations. Stops the day you stop paying."
          ]
        ]
      },
      {
        "type": "p",
        "text": "Cost and speed are why order matters. The pack and organic results are assets that compound, while ads are rented traffic. Neither is better in the abstract. Which one comes first depends on what is already in place. For the basics behind the pack, see [what local SEO for doctors involves](/blog/what-is-local-seo-for-doctors)."
      },
      {
        "type": "h2",
        "text": "A sensible order for a limited budget"
      },
      {
        "type": "ol",
        "items": [
          "Complete and verify your Google Business Profile, choose accurate categories, add services and photos, and ask real patients for reviews the compliant way. See [how to get more patients from your Google Business Profile](/guides/how-to-get-more-patients-from-google-business-profile).",
          "Make sure the website has one clear page per service, accurate contact details, and a booking path that works on a phone, per [how to write a medical service page that ranks](/guides/how-to-write-a-medical-service-page-that-ranks).",
          "Set up conversion tracking for calls and forms, so any later spending can be measured.",
          "Add Google Ads for specific, high-value services once the first three are working, starting with a small test budget and negative keywords."
        ]
      },
      {
        "type": "p",
        "text": "Google's own documentation on local ranking names relevance, distance, and prominence as the factors, and you can influence relevance and prominence directly through profile completeness and reviews. If your practice is not appearing in the pack at all, start with [why a practice isn't showing up on Google Maps](/blog/why-your-medical-practice-isnt-showing-up-on-google-maps). Searching your own key phrases and noting who holds the pack is the first step of a competitor comparison, described in [how to analyze local competitors for a medical practice](/guides/how-to-analyze-local-competitors-for-a-medical-practice)."
      },
      {
        "type": "h2",
        "text": "When ads should come first"
      },
      {
        "type": "p",
        "text": "There are real exceptions. A brand-new practice with no reviews and an empty calendar may need paid traffic to fill it while the slower channels build. A new service line or a second location may need an early push. In those cases, treat ads as a bridge, not a replacement, and keep building the assets underneath. Practices should also follow Google's healthcare advertising policy, which restricts some products and claims. Our [healthcare ad compliance checklist](/guides/healthcare-ad-compliance-checklist) lists what to check, and our [Google Ads cost guide](/guides/google-ads-cost-for-a-medical-practice) explains what to budget."
      },
      {
        "type": "h2",
        "text": "How to know it is working"
      },
      {
        "type": "p",
        "text": "Track calls, form submissions, direction requests, and booked appointments by source, not clicks alone. If the pack and organic channels bring in patients at a lower cost, shift ad spend toward the services where they are weakest. If ads are the only thing producing leads, the foundation needs work before you scale spending."
      }
    ],
    faqs: [
      {
        "q": "Is the local pack more valuable than organic results?",
        "a": "For nearby, urgent, and 'near me' searches, usually yes, because the map sits near the top and shows reviews, hours, and a call button. For research questions about conditions or comparisons, organic pages carry more weight. A practice needs both, with the pack first."
      },
      {
        "q": "Can I rely on Google Ads alone?",
        "a": "You can, but it is the most fragile choice. Traffic stops when spending stops, and you build no lasting asset. Ads work best when the profile, reviews, and website are strong enough to convert the clicks you buy. Build the foundation first, so paid clicks have somewhere good to land."
      },
      {
        "q": "How much should I spend on each channel?",
        "a": "There is no single split, since it depends on competition, services, and location. Start with the lowest-cost assets, which are mostly time, then test ads with a small, capped budget and measure cost per booked patient before scaling. Review the split every month against booked patients."
      },
      {
        "q": "Do Google Ads help my local pack ranking?",
        "a": "Google says it does not accept payment to rank local results higher, so advertising does not improve your listing's rank. Ads can add visibility alongside it, but they are not a substitute for managing your profile. Compete on relevance and prominence instead, which you can control."
      },
      {
        "q": "What should I measure to compare channels?",
        "a": "Measure booked appointments and tracked calls by source, plus cost per booked patient. Clicks and impressions can mislead. Set up call and form tracking before you spend, so the comparison is based on real patients and not guesses. Review the numbers monthly and adjust the budget from there."
      }
    ],
    citations: [
      {
        "publisher": "Google Business Profile Help",
        "label": "Tips to improve your local ranking on Google",
        "href": "https://support.google.com/business/answer/7091"
      },
      {
        "publisher": "Google Ads Policy Help",
        "label": "Healthcare and medicines policy",
        "href": "https://support.google.com/adspolicy/answer/176031"
      }
    ],
    links: [
      {
        "href": "/guides/how-to-get-more-patients-from-google-business-profile",
        "label": "How to Get More Patients from Google Business Profile",
        "description": "Start with the cheapest asset."
      },
      {
        "href": "/guides/google-ads-cost-for-a-medical-practice",
        "label": "Google Ads Cost for a Medical Practice",
        "description": "What to budget once the foundation is ready."
      },
      {
        "href": "/guides/seo-vs-meta-ads-for-a-med-spa",
        "label": "SEO vs Meta Ads for a Med Spa",
        "description": "Another channel comparison for a specific specialty."
      },
      {
        "href": "/services/google-ads",
        "label": "Google Ads for Medical Practices",
        "description": "Managed ads with tracking built in."
      },
      {
        "href": "/locations/google-ads-management-west-palm-beach",
        "label": "Google Ads Management in West Palm Beach",
        "description": "Paid search applied to one real market."
      },
      {
        "href": "/locations/google-ads-management-florida",
        "label": "Google Ads Management in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
];
