// ── Guides batch 11 — 2026-10-07 ───────────────────────────────────────────
// 4 guide/AEO rows from the Command Center queue (ids 698, 701, 703, 706), built by
// the daily page factory to ~/Primara-Clients/PAGE-STANDARD.md. Schema graph is
// generated by app/guides/[slug]/page.tsx. Citations: Google Search Central / Google help.
// Inbound links are inline [text](/guides/slug) links in existing guides' body prose.

import type { Guide } from "@/lib/guides";

export const guidesPartFourteen: Guide[] = [
  {
    "slug": "how-to-write-title-tags-for-a-medical-practice-website",
    "keyword": "how to write title tags for the pages of a medical practice website",
    "category": "How-to",
    "title": "How to Write Title Tags for a Medical Practice Website",
    "metaTitle": "How to Write Title Tags for a Medical Practice Site",
    "metaDescription": "A plain guide to title tags for medical practice pages: patterns by page type, length, examples, and mistakes to avoid. Call (561) 291-2681.",
    "answer": "A title tag is the clickable headline Google may show for your page. Give every page a unique title that puts what the page is about first, adds the city or provider where it fits, and ends with your practice name. Keep it readable, not stuffed, and check Google's rewrites in Search Console.",
    "author": "Gio LaRoche",
    "publishDate": "2026-10-07T09:00:00Z",
    "dateModified": "2026-10-07",
    "readMinutes": 6,
    "sections": [
      {
        "type": "h2",
        "text": "What a title tag does on a practice website"
      },
      {
        "type": "p",
        "text": "The title tag is the line of text in your page's HTML that tells browsers and search engines what the page is called. It appears on the browser tab, and Google often uses it as the blue headline in search results. For a patient scanning ten results on a phone, it is the first thing they read about your practice and frequently the only thing."
      },
      {
        "type": "p",
        "text": "Google calls this a title link and builds it mainly from your title element, then your visible headings and other signals. Google may rewrite a title it thinks is too long, empty, repeated across pages, or not a good match for the page. Writing a clear title yourself keeps more of that control. The details are in Google's [guidance on title links](https://developers.google.com/search/docs/appearance/title-link)."
      },
      {
        "type": "h2",
        "text": "The pattern that works for most pages"
      },
      {
        "type": "p",
        "text": "Lead with the thing the page is about, add the place or provider if it helps a patient choose, and finish with the practice name. Your most important words should come first because long titles get cut off at the end, and the cut-off point depends on pixel width rather than a fixed number of characters. A common rule of thumb is to keep titles to roughly 50 to 60 characters. Treat that as a working guide, not a Google rule."
      },
      {
        "type": "table",
        "headers": [
          "Page type",
          "Pattern and example"
        ],
        "rows": [
          [
            "Home page",
            "Practice type + city | Practice name. Example: Family Medicine in Wellington, FL | Example Medical"
          ],
          [
            "Service page",
            "Service + city | Practice name. Example: Sports Physicals in Wellington | Example Medical"
          ],
          [
            "Provider page",
            "Provider name, credential + specialty | Practice name. Example: Jane Rivera, MD, Internal Medicine | Example Medical"
          ],
          [
            "Location page",
            "Practice type + neighborhood or city | Practice name. Example: Urgent Care in Boynton Beach | Example Medical"
          ],
          [
            "Blog or guide",
            "The question or topic in plain words. Example: How to Prepare for Your First Visit | Example Medical"
          ]
        ]
      },
      {
        "type": "p",
        "text": "The practice and provider names above are placeholders. Use your own exact legal or public-facing names, spelled the same way as on your Google Business Profile."
      },
      {
        "type": "h2",
        "text": "Write one title per page, not one title per template"
      },
      {
        "type": "p",
        "text": "Duplicate titles are the most common problem we see on practice sites. A website platform often fills every page with the same default, such as the practice name alone or the page name plus the same suffix. Google then has no way to tell pages apart in a list. If your sixty pages share three titles, you are asking Google to guess."
      },
      {
        "type": "p",
        "text": "Give each page its own title based on the one question it answers. If two pages end up with nearly identical titles, that usually means they cover the same topic and one of them should be merged or retargeted. Our guide on [writing a service page that ranks](/guides/how-to-write-a-medical-service-page-that-ranks) covers how to choose one intent per page."
      },
      {
        "type": "h2",
        "text": "What to leave out"
      },
      {
        "type": "ul",
        "items": [
          "Keyword lists. A title such as Doctor, Physician, Clinic, Primary Care, Urgent Care Wellington reads as spam to patients and tends to get rewritten.",
          "The same phrase on every page. Repeating your city and specialty in all sixty titles makes them blur together.",
          "Claims you cannot support. Avoid best, top-rated, number one, guaranteed or outcome language. For healthcare, claims that sound clinical or promise results can also create compliance trouble.",
          "ALL CAPS and symbol strings. They are harder to read and add nothing.",
          "A title that disagrees with the page. If the title promises same-day appointments and the page does not mention them, patients leave and Google may ignore your wording."
        ]
      },
      {
        "type": "h2",
        "text": "How to check and fix your titles in an afternoon"
      },
      {
        "type": "ol",
        "items": [
          "Export a list of your pages and their titles. A site crawler or the page source of each page will show the title element.",
          "Sort by title and look for exact duplicates, empty titles, and titles that only contain your practice name.",
          "Rewrite the highest-value pages first: home, your main services, each location and each provider.",
          "Open Google Search Console, go to Performance, and look at which pages get impressions but few clicks. Those are candidates for a clearer title.",
          "Publish the changes and give Google a few weeks to recrawl before judging them. Change one group of pages at a time so you can see what moved."
        ]
      },
      {
        "type": "p",
        "text": "Titles work together with the snippet underneath. After you finish this pass, write matching descriptions using our [meta descriptions guide](/guides/meta-descriptions-that-get-clicks-for-a-medical-practice), and make sure each title agrees with the page's top heading, which our [Search Console guide](/guides/how-to-read-google-search-console-for-a-medical-practice-website) helps you monitor."
      }
    ],
    "faqs": [
      {
        "q": "How long should a title tag be?",
        "a": "There is no fixed limit, because Google cuts titles by pixel width rather than character count. Many practices aim for about 50 to 60 characters and put the most important words first. If a title runs long, the end is what gets cut, so keep the practice name last."
      },
      {
        "q": "Should every page title include the practice name?",
        "a": "Usually yes, at the end, so patients recognize you in a list of results. Put the page topic first. On very long titles, it is acceptable to shorten or drop the practice name so the main topic stays visible."
      },
      {
        "q": "Why does Google show a different title than the one I wrote?",
        "a": "Google may rewrite a title when it is too long, repeated across pages, stuffed with keywords or does not match the page. Make titles short, unique and consistent with the page's main heading, and Google will often keep them."
      },
      {
        "q": "Should I put my city in every title?",
        "a": "Include the city where the page is genuinely about that place, such as a location page or a local service page. Adding it to every page, including blog posts and provider bios, makes titles repetitive without helping patients."
      },
      {
        "q": "How soon will a new title show up in Google?",
        "a": "It depends on how soon Google recrawls the page, which can take from days to several weeks. You can request a recrawl of a single page in Search Console, though results are never instant and rankings are not promised."
      }
    ],
    "citations": [
      {
        "publisher": "Google Search Central",
        "label": "Influencing title links in Google Search",
        "href": "https://developers.google.com/search/docs/appearance/title-link"
      },
      {
        "publisher": "Google Search Central",
        "label": "SEO Starter Guide",
        "href": "https://developers.google.com/search/docs/fundamentals/seo-starter-guide"
      }
    ],
    "links": [
      {
        "href": "/guides/meta-descriptions-that-get-clicks-for-a-medical-practice",
        "label": "Meta Descriptions That Get Clicks",
        "description": "The snippet that sits under the title."
      },
      {
        "href": "/guides/how-to-write-a-medical-service-page-that-ranks",
        "label": "How to Write a Service Page That Ranks",
        "description": "One page, one intent, one title."
      },
      {
        "href": "/guides/how-to-write-a-doctor-bio-page-that-ranks",
        "label": "Doctor Bio Pages That Rank",
        "description": "Provider titles done right."
      },
      {
        "href": "/services/seo",
        "label": "Medical SEO Services",
        "description": "Page-level SEO as part of monthly work."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ]
  },
  {
    "slug": "how-to-write-a-google-business-profile-description-for-a-medical-practice",
    "keyword": "how to write a Google Business Profile description for a medical practice",
    "category": "How-to",
    "title": "How to Write a Google Business Profile Description for a Medical Practice",
    "metaTitle": "Google Business Profile Description for a Medical Practice",
    "metaDescription": "What to put in your Google Business Profile description, what to leave out, a fill-in outline and compliance cautions. Call (561) 291-2681.",
    "answer": "Your Google Business Profile description is a short text of up to 750 characters, shown in the From the business section. Say who you are, what you treat or offer, where you are and what is useful to know. Leave out links, prices, promotions, outcome claims and keyword lists.",
    "author": "Liam Costello",
    "publishDate": "2026-10-07T09:00:00Z",
    "dateModified": "2026-10-07",
    "readMinutes": 6,
    "sections": [
      {
        "type": "h2",
        "text": "What the description field is, and what it is not"
      },
      {
        "type": "p",
        "text": "The business description is a free-text field on your Google Business Profile. Google shows it in a From the business section, so patients who scroll your listing may read it while deciding whether to call. It is a plain summary of your practice, written for people, not a place to load search terms."
      },
      {
        "type": "p",
        "text": "Google's own instructions in its help page on [editing your Business Profile](https://support.google.com/business/answer/3039617) set the rules. The description must stay within 750 characters, must not contain URLs or HTML code, and should focus on details about the business rather than promotions, prices or sales. Google also suggests including what you offer, what makes you special, how long you have been in business and anything else helpful. Confirm those limits against that page before you publish, since Google updates its help pages."
      },
      {
        "type": "h2",
        "text": "A simple outline for four short sentences"
      },
      {
        "type": "p",
        "text": "Most practices do well with four plain sentences that each do one job. The order below puts the most useful facts first, since a reader may not scroll."
      },
      {
        "type": "ol",
        "items": [
          "Who you are: your practice type and where you are located, using the same name as on your profile.",
          "What you offer: the main services or specialties patients actually search for, in everyday words.",
          "What helps a patient decide: languages spoken, telehealth availability, accepted payment types, or how long the practice has operated, if true and current.",
          "How to start: a single plain line about calling or booking an appointment, without a link."
        ]
      },
      {
        "type": "p",
        "text": "A filled-in example, using placeholders: Example Family Medicine is an independent primary care practice in Wellington, Florida. We see adults and children for checkups, sick visits, vaccinations and ongoing care for common health conditions. We offer telehealth visits and speak English and Spanish. Call our office to schedule an appointment. That runs well under 750 characters and every statement is checkable."
      },
      {
        "type": "h2",
        "text": "What to leave out"
      },
      {
        "type": "ul",
        "items": [
          "Links, web addresses and HTML. Google says not to include URLs or code, and your website already has its own field.",
          "Prices, discounts and limited-time offers. Google asks that the description focus on the business, and offers go stale quickly. Use Google Posts for time-limited news instead.",
          "Outcome claims and promises such as best results, cures or guaranteed improvement. They are hard to support and risky in healthcare marketing.",
          "Keyword stuffing. A paragraph of repeated terms such as doctor, clinic, urgent care, near me reads badly and may be ignored.",
          "Patient stories, names or any detail that could identify a patient. Your description is public, and protected health information does not belong in it.",
          "Credentials you cannot verify. Name only licenses, boards and affiliations that you can document."
        ]
      },
      {
        "type": "h2",
        "text": "How it fits with the rest of your profile"
      },
      {
        "type": "p",
        "text": "The description is only one field. Your categories tell Google what kind of practice you are, your [services list](/guides/google-business-profile-services-list-optimization) names what you do, and your [attributes](/guides/google-business-profile-attributes-for-a-medical-practice) cover details like accessibility and languages. Use the description to say in a human voice what those structured fields cannot, and do not repeat the whole services list inside it."
      },
      {
        "type": "p",
        "text": "Treat it as an accuracy check too. If your description says you offer telehealth and your website does not, a patient or reviewer will notice. Match the description to the website, the hours and the services shown on the profile. Our [monthly profile maintenance checklist](/guides/monthly-google-business-profile-maintenance-checklist) has a quick review step for this."
      },
      {
        "type": "h2",
        "text": "When to update it"
      },
      {
        "type": "p",
        "text": "Revisit the description when you add a provider, add or drop a major service, move, change hours of operation in a lasting way or begin offering telehealth. A short, accurate description that you actually maintain beats a long one that went out of date a year ago."
      }
    ],
    "faqs": [
      {
        "q": "How long can a Google Business Profile description be?",
        "a": "Google's help page says to keep the description within 750 characters. Aim for roughly four short sentences, well below the limit, since a tight summary is easier to read. Check Google's current help page before you publish in case the limit has changed."
      },
      {
        "q": "Can I put my website link or phone number in the description?",
        "a": "Google says not to include URLs or HTML code. Your website and phone number have their own fields on the profile, so use those. A line telling people to call the office to schedule is acceptable without including a link."
      },
      {
        "q": "Does the description help me rank higher?",
        "a": "Google does not say that the description is a ranking factor, so write it for patients rather than for search engines. A clear, accurate description can still help a person decide to call, which is the real purpose of the field."
      },
      {
        "q": "Should I list every service in the description?",
        "a": "No. Use the services section of the profile for the full list and the description for a short overview of who you are and what matters most to a new patient. Repeating a long list makes the description harder to read."
      },
      {
        "q": "Can I mention insurance or prices in the description?",
        "a": "Google asks businesses to focus on their details rather than prices or promotions. Accepted insurance can change, so check what is allowed and keep it accurate on your website, which patients can verify, instead of relying on the description."
      }
    ],
    "citations": [
      {
        "publisher": "Google Business Profile Help",
        "label": "Edit your Business Profile",
        "href": "https://support.google.com/business/answer/3039617"
      },
      {
        "publisher": "Google Business Profile Help",
        "label": "Guidelines for representing your business on Google",
        "href": "https://support.google.com/business/answer/3038177"
      }
    ],
    "links": [
      {
        "href": "/guides/google-business-profile-services-list-optimization",
        "label": "Google Business Profile Services List",
        "description": "The structured field next to your description."
      },
      {
        "href": "/guides/google-business-profile-attributes-for-a-medical-practice",
        "label": "Google Business Profile Attributes",
        "description": "Details a description should not repeat."
      },
      {
        "href": "/guides/choosing-google-business-profile-categories-for-a-medical-practice",
        "label": "Choosing Profile Categories",
        "description": "The field that defines your practice type."
      },
      {
        "href": "/services/google-business-profile",
        "label": "Google Business Profile Optimization",
        "description": "Profile setup done for you."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ]
  },
  {
    "slug": "how-to-find-and-fix-broken-links-and-404-errors-on-a-medical-practice-website",
    "keyword": "finding and fixing broken links, 404 errors and retired pages on a medical practice website",
    "category": "Checklist",
    "title": "How to Find and Fix Broken Links and 404 Errors on a Medical Practice Website",
    "metaTitle": "Fix Broken Links and 404s on a Medical Practice Site",
    "metaDescription": "How to find broken links and 404 pages on a practice website, when to use a 301 redirect, and how to retire a page cleanly. Call (561) 291-2681.",
    "answer": "A broken link points to a page that no longer loads, usually returning a 404. Find them with Search Console and a site crawl, then fix each one by updating the link, redirecting a retired page with a 301 to its closest replacement, or letting a truly gone page return a real 404.",
    "author": "Gio LaRoche",
    "publishDate": "2026-10-07T09:00:00Z",
    "dateModified": "2026-10-07",
    "readMinutes": 6,
    "sections": [
      {
        "type": "h2",
        "text": "Why dead pages matter to a practice"
      },
      {
        "type": "p",
        "text": "Practice websites change constantly. A provider leaves, a service is dropped, a location closes, a plugin updates and rewrites an address. Each change can leave links pointing at pages that no longer exist. A patient who taps a Book now link and lands on an error page does not call; they search for the next practice."
      },
      {
        "type": "p",
        "text": "A 404 is the standard code a server returns when it cannot find a page. A few of them are normal, and Google says that 404 errors on their own do not hurt the rest of your site. The problems are broken links on pages patients actually use, important pages that quietly return errors, and old addresses that other sites still link to. Google explains how it treats each response code in its guide to [HTTP status codes](https://developers.google.com/search/docs/crawling-indexing/http-network-errors)."
      },
      {
        "type": "h2",
        "text": "Where to look first"
      },
      {
        "type": "ul",
        "items": [
          "Search Console, Page indexing report. Pages Google could not index are grouped by reason, including Not found (404). Open the list and look for URLs you still care about. The [report is explained in Google's help](https://support.google.com/webmasters/answer/7440203).",
          "A site crawler. Free and paid crawlers visit every internal link and list the ones that return 404 or redirect, along with the page that contains the link.",
          "Your own key paths. Click through the booking button, the phone link, the patient portal link, each provider page and each location page on a phone. Automated tools miss a link that works but points to the wrong place.",
          "Your sitemap. Every URL in the sitemap should return a normal page. A sitemap that lists dead addresses tells Google to keep trying them.",
          "Your Google Business Profile. Confirm the website and appointment links on the profile still load."
        ]
      },
      {
        "type": "h2",
        "text": "Pick the right fix for each broken link"
      },
      {
        "type": "table",
        "headers": [
          "Situation",
          "Fix"
        ],
        "rows": [
          [
            "The link has a typo or old address",
            "Edit the link on the page that contains it so it points to the live URL."
          ],
          [
            "A page moved to a new address",
            "Add a 301 redirect from the old address to the new one, then update internal links to the new address."
          ],
          [
            "A page was retired but a close replacement exists",
            "301 redirect to the closest matching page, such as a retired service to the broader service page."
          ],
          [
            "A page was retired with no real replacement",
            "Let it return a 404 or 410, and remove internal links to it. Do not redirect everything to the home page."
          ],
          [
            "A page shows an error message but returns a normal 200",
            "Fix it so the server returns a genuine 404. Google calls these soft 404s."
          ]
        ]
      },
      {
        "type": "h2",
        "text": "How to retire a page cleanly"
      },
      {
        "type": "ol",
        "items": [
          "Decide whether the page should go. If it still gets visits or has links from other sites, consider updating it instead of removing it.",
          "Find a real replacement. It should serve the same patient need: a retired provider bio could point to the practice's team page, for example.",
          "Set up a 301 redirect, which tells browsers and Google the move is permanent. Google describes the options in its guide to [redirects](https://developers.google.com/search/docs/crawling-indexing/301-redirects).",
          "Remove the old URL from your sitemap and add the new one.",
          "Update internal links, menus and your profile links so they point straight to the new address instead of passing through the redirect.",
          "Recheck in Search Console after a few weeks."
        ]
      },
      {
        "type": "p",
        "text": "Sending every retired page to the home page is a common shortcut and a poor one. A patient looking for a retired page about a specific service wants that service, and Google may treat an unrelated redirect as a soft 404. If nothing relevant exists, a clear 404 page with a link to your services and your phone number is the honest answer."
      },
      {
        "type": "h2",
        "text": "Make your 404 page useful"
      },
      {
        "type": "p",
        "text": "Even a well-kept site will occasionally serve a 404. Give that page a short message, a search box if your platform has one, links to your main services and locations, and your phone number. Make sure it returns a real 404 status and not a normal 200 page that merely looks like an error."
      },
      {
        "type": "h2",
        "text": "Keep it from piling up again"
      },
      {
        "type": "p",
        "text": "Run the crawl after every redesign, migration or provider change. Our [site migration guide](/guides/how-to-migrate-a-medical-practice-website-to-a-new-domain) covers redirect mapping at launch, and the [provider change checklist](/guides/what-to-update-when-a-provider-joins-or-leaves-a-medical-practice) lists the pages and links affected when someone leaves. Add a recurring calendar item to check Search Console once a month."
      }
    ],
    "faqs": [
      {
        "q": "Do 404 errors hurt my Google rankings?",
        "a": "Not on their own. Google says 404 errors for pages that no longer exist do not damage the rest of your site. What hurts patients is a broken link on a page they use or an important page that stops working, so fix those first."
      },
      {
        "q": "What is a 301 redirect?",
        "a": "A 301 is a server instruction saying a page has permanently moved to a new address. Browsers and Google follow it automatically. Use it when a page has a close replacement, and then update internal links so people reach the new page directly."
      },
      {
        "q": "Should I redirect deleted pages to my home page?",
        "a": "Usually not. A redirect should point to the closest equivalent page. When nothing relevant exists, let the old URL return a real 404 or 410 and give patients a helpful error page with your phone number and main links."
      },
      {
        "q": "What is a soft 404?",
        "a": "A soft 404 is a page that shows an error or empty message but tells Google the page loaded normally. Google may treat it as an error anyway. Fix it so the server returns a true 404 status, or restore real content."
      },
      {
        "q": "How often should I check for broken links?",
        "a": "Check Search Console monthly and run a full crawl after any redesign, domain move, plugin update or provider change. A short monthly review catches most problems before patients find them."
      }
    ],
    "citations": [
      {
        "publisher": "Google Search Central",
        "label": "How HTTP status codes affect Google's crawlers",
        "href": "https://developers.google.com/search/docs/crawling-indexing/http-network-errors"
      },
      {
        "publisher": "Google Search Central",
        "label": "Redirects and Google Search",
        "href": "https://developers.google.com/search/docs/crawling-indexing/301-redirects"
      },
      {
        "publisher": "Google Search Console Help",
        "label": "Page indexing report",
        "href": "https://support.google.com/webmasters/answer/7440203"
      }
    ],
    "links": [
      {
        "href": "/guides/how-to-migrate-a-medical-practice-website-to-a-new-domain",
        "label": "Migrating a Practice Website",
        "description": "Redirect mapping when a site moves."
      },
      {
        "href": "/guides/xml-sitemaps-and-robots-txt-for-a-medical-practice-website",
        "label": "XML Sitemaps and robots.txt",
        "description": "Keep dead URLs out of the sitemap."
      },
      {
        "href": "/guides/how-to-read-google-search-console-for-a-medical-practice-website",
        "label": "Reading Google Search Console",
        "description": "Where the Not found list lives."
      },
      {
        "href": "/services/seo",
        "label": "Medical SEO Services",
        "description": "Page-level SEO as part of monthly work."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ]
  },
  {
    "slug": "how-to-read-google-analytics-4-reports-each-month-for-a-medical-practice",
    "keyword": "how to read Google Analytics 4 reports each month for a medical practice",
    "category": "How-to",
    "title": "How to Read Google Analytics 4 Reports Each Month for a Medical Practice",
    "metaTitle": "Reading Google Analytics 4 Each Month for a Practice",
    "metaDescription": "A 20-minute monthly routine for reading GA4: which reports to open, what each number means, and what to ignore. Call (561) 291-2681.",
    "answer": "Once a month, open four things in Google Analytics 4: traffic acquisition to see where visitors came from, pages and screens to see what they read, engagement rate to see whether they stayed, and key events to see who called or submitted a form. Compare each to the prior month and write down what changed.",
    "author": "Gio LaRoche",
    "publishDate": "2026-10-07T09:00:00Z",
    "dateModified": "2026-10-07",
    "readMinutes": 6,
    "sections": [
      {
        "type": "h2",
        "text": "Set a 20-minute monthly routine"
      },
      {
        "type": "p",
        "text": "Google Analytics 4 can show hundreds of numbers, and most are noise for a medical practice. A short, repeatable routine works better than occasional deep dives. Pick the same day each month, set the date range to the previous full month, turn on the compare option for the month before, and look at four areas. If you have not yet installed GA4, start with our [GA4 setup guide](/guides/how-to-set-up-google-analytics-4-for-a-medical-practice)."
      },
      {
        "type": "p",
        "text": "Privacy comes first. Analytics tools can collect more than a medical site should, so confirm your setup follows our [HIPAA-safe tracking guide](/guides/hipaa-safe-tracking-for-a-medical-website) before you rely on any numbers. Nothing in a monthly review should require looking at an individual patient's activity."
      },
      {
        "type": "h2",
        "text": "Step 1: Where visitors came from"
      },
      {
        "type": "p",
        "text": "Open Reports, then Acquisition, then Traffic acquisition. The default grouping sorts sessions by channel, such as Organic Search, Direct, Referral, Organic Social and Paid Search. For a practice, Organic Search is the channel your local SEO work should grow, and Direct often includes people typing your address or opening a saved link. Note whether Organic Search grew or shrank against last month, and treat a small change in a low-traffic month as noise rather than a trend."
      },
      {
        "type": "h2",
        "text": "Step 2: What they looked at"
      },
      {
        "type": "p",
        "text": "Open Reports, then Engagement, then Pages and screens. Sort by views and look at the top ten pages. You are checking that the pages you want patients to see, such as services, providers, locations and the booking page, appear near the top. If the top pages are old blog posts and your main service pages are missing, that tells you where to add internal links or improve the page."
      },
      {
        "type": "h2",
        "text": "Step 3: Whether they stayed"
      },
      {
        "type": "p",
        "text": "GA4 reports engagement rate, which is the share of sessions that were engaged. Google's definition counts a session as engaged if it lasted longer than ten seconds, had a key event or had at least two page or screen views. Google explains this in its help on [engagement rate and bounce rate](https://support.google.com/analytics/answer/12195621). A falling engagement rate on an important page suggests the page is not meeting what visitors expected, though a single month is rarely conclusive."
      },
      {
        "type": "h2",
        "text": "Step 4: Who took action"
      },
      {
        "type": "p",
        "text": "Key events are the actions you care about, such as clicking a phone number, submitting an appointment request or reaching a thank-you page. GA4 used to call these conversions. Open Reports, then Engagement, then Events, and check how many key events happened and which channel they came from. If you track calls and forms, our guide to [tracking phone calls](/guides/tracking-phone-calls-from-a-medical-website) shows what to set up. Count contact requests, never anything about a patient's health."
      },
      {
        "type": "h2",
        "text": "What to write down each month"
      },
      {
        "type": "table",
        "headers": [
          "Measure (where to find it)",
          "What to note"
        ],
        "rows": [
          [
            "Sessions by channel (Traffic acquisition)",
            "Organic Search up, down or flat"
          ],
          [
            "Top pages (Pages and screens)",
            "Whether service and location pages are in the top ten"
          ],
          [
            "Engagement rate (Traffic acquisition or Pages)",
            "Any drop on a page that matters"
          ],
          [
            "Key events (Events)",
            "Calls and form submissions, and their channel"
          ]
        ]
      },
      {
        "type": "p",
        "text": "Keep these four lines in a simple log. After three or four months, the log shows direction far better than any single report. Pair it with your Search Console numbers, covered in our [Search Console guide](/guides/how-to-read-google-search-console-for-a-medical-practice-website), and with [return on marketing spend](/guides/how-to-measure-roi-on-medical-practice-marketing) when you compare against revenue."
      },
      {
        "type": "h2",
        "text": "What to ignore"
      },
      {
        "type": "ul",
        "items": [
          "Day-to-day swings. With the traffic a typical single-location practice gets, a bad Tuesday means little.",
          "Bounce rate on its own. GA4 reports it as the opposite of engagement rate, and it matters less than whether key events occurred.",
          "Vanity totals. Total sessions can rise because of bot traffic or a one-off referral without bringing any more patients.",
          "Demographic and device detail, unless you are making a specific design or advertising decision."
        ]
      }
    ],
    "faqs": [
      {
        "q": "How often should a practice look at Google Analytics?",
        "a": "Once a month is enough for most practices, using the previous full month compared with the month before. Daily checking encourages reacting to noise. If you launch a campaign or redesign, add a short check one and four weeks afterward."
      },
      {
        "q": "What is a key event in GA4?",
        "a": "A key event is an action you mark as important, such as a phone-number click, a form submission or reaching a thank-you page. GA4 previously called these conversions. They show whether visits turn into contact attempts, so they matter more than raw traffic."
      },
      {
        "q": "What is engagement rate in GA4?",
        "a": "It is the share of sessions that were engaged. Google counts a session as engaged if it lasted longer than ten seconds, included a key event or had two or more page or screen views. It replaced bounce rate as the main measure of whether visitors stayed."
      },
      {
        "q": "Why do my GA4 numbers differ from Search Console?",
        "a": "They measure different things. Search Console counts impressions and clicks in Google Search, while GA4 counts sessions on your site from all sources, and privacy settings or blockers can prevent some visits from appearing in GA4. Expect differences and compare trends instead of exact totals."
      },
      {
        "q": "Is Google Analytics safe for a medical practice website?",
        "a": "It can be used carefully, but a medical site should avoid sending anything that could identify a patient or reveal a health condition, such as health details in page addresses or form fields. Review your setup with a compliance advisor, and see our HIPAA-safe tracking guide before relying on it."
      }
    ],
    "citations": [
      {
        "publisher": "Google Analytics Help",
        "label": "[GA4] Engagement rate and bounce rate",
        "href": "https://support.google.com/analytics/answer/12195621"
      },
      {
        "publisher": "Google Analytics Help",
        "label": "Analytics dimensions and metrics",
        "href": "https://support.google.com/analytics/answer/9143382"
      }
    ],
    "links": [
      {
        "href": "/guides/how-to-set-up-google-analytics-4-for-a-medical-practice",
        "label": "Set Up Google Analytics 4",
        "description": "Install it before you read it."
      },
      {
        "href": "/guides/hipaa-safe-tracking-for-a-medical-website",
        "label": "HIPAA-Safe Tracking",
        "description": "Privacy limits for any analytics setup."
      },
      {
        "href": "/guides/how-to-measure-roi-on-medical-practice-marketing",
        "label": "Measuring Marketing ROI",
        "description": "Tie these numbers to revenue."
      },
      {
        "href": "/services/seo",
        "label": "Medical SEO Services",
        "description": "Page-level SEO as part of monthly work."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ]
  }
];
