// ── Guides batch 6 — 2026-10-01 ────────────────────────────────────────────
// 10 guide/AEO rows from the Command Center queue (ids 474, 505-514, minus
// 512 — see PIPELINE.md: 512 "how to set up call tracking" duplicates the
// existing /guides/tracking-phone-calls-from-a-medical-website intent and
// was skipped rather than built as a near-duplicate).
// Built to ~/Primara-Clients/PAGE-STANDARD.md: answer box, 4-6 FAQs at
// 40-80 words marked up FAQPage, Article/Service/Organization/BreadcrumbList/
// WebPage schema graph (all generated by app/guides/[slug]/page.tsx from this
// data), >=3 outbound links, 1-3 outbound citations (Google / FTC / FCC /
// HHS — never a competitor).

import type { Guide } from "@/lib/guides";

export const guidesPartNine: Guide[] = [
  // ── 474 ───────────────────────────────────────────────────────────────
  {
    slug: "meta-descriptions-that-get-clicks-for-a-medical-practice",
    keyword: "how to write meta descriptions that get clicks for a medical practice",
    category: "How-to",
    title: "How to Write Meta Descriptions That Get Clicks for a Medical Practice",
    metaTitle: "Meta Descriptions That Get Clicks for Medical Practices",
    metaDescription:
      "How to write a meta description a Florida patient actually clicks — length, what to include, and three real examples. Call (561) 291-2681.",
    answer:
      "A good meta description for a medical practice page is 140-155 characters, names the city and the specific service, and answers what the patient wants to know before they click — same-day availability, insurance accepted, or the fastest way to book. Google rewrites descriptions it judges unhelpful, so writing one well reduces how often that happens.",
    author: "Gio LaRoche",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 6,
    sections: [
      { type: "h2", text: "What a meta description actually does" },
      {
        type: "p",
        text: "A meta description is the one or two lines of gray text under your blue link in Google's results. It is not a ranking factor — Google has said this directly for years — but it is the single biggest lever you have over whether someone who already sees your result clicks it instead of the practice above or below you. For a local medical page, that click is the whole game: ranking third with a description that gets clicked beats ranking first with one that gets skipped.",
      },
      {
        type: "p",
        text: "Google does not always use the description you write. Its systems choose whichever text on the page (or in the meta tag) best matches what the searcher typed, and Google's own documentation says that can mean pulling a different sentence from your body copy instead. Writing a strong, specific meta description lowers how often that happens — a vague one gives Google nothing better to work with than a rewrite. Rewrite a description whenever you refresh the page itself, as described in [how often to update old content on a medical practice website](/guides/how-often-to-update-old-content-on-a-medical-practice-website).",
      },
      { type: "h2", text: "The four things that make a patient click" },
      {
        type: "ol",
        items: [
          "Lead with the service and the city, in that order or close to it — 'Family Medicine in Lakeland' reads faster than a clever opening line.",
          "Answer the next question the searcher has, not the one you want to answer. For most medical searches that is availability ('same-day appointments'), cost/insurance ('most major insurance accepted'), or proof ('board-certified, 500+ patients seen').",
          "Include a concrete action — 'Book online' or 'Call to schedule' — rather than ending on a noun phrase.",
          "Stay inside roughly 140-155 characters. Google's display width varies by device and query, but anything meaningfully longer gets cut mid-word, which reads as unfinished and unprofessional.",
        ],
      },
      { type: "h2", text: "Three real before-and-afters" },
      {
        type: "table",
        headers: ["Weak (generic)", "Strong (specific)"],
        rows: [
          [
            "Welcome to our family practice. We care about your health and look forward to serving you.",
            "Board-certified family medicine in Lakeland, FL. Same-day sick visits, most insurance accepted. Book online or call (561) 291-2681.",
          ],
          [
            "Our therapists help people work through life's challenges in a safe, supportive environment.",
            "Licensed therapists in West Palm Beach taking new clients this week. In-network with major insurers. See availability and book online.",
          ],
          [
            "We offer a wide range of aesthetic treatments to help you look and feel your best.",
            "Botox and filler in Miami from a licensed medical provider, not a spa tech. Free consult, same-week appointments available.",
          ],
        ],
      },
      { type: "h2", text: "One description per page, never duplicated" },
      {
        type: "p",
        text: "Google Search Console's Page Indexing report flags duplicate meta descriptions as a quality signal, and a practice with five city pages that all share one description is telling Google those pages are interchangeable — which makes it easier for Google to treat them that way when deciding which one, if any, to rank. Every page needs its own, built around what is actually different about it: the city, the specific service, or the specific provider.",
      },
      { type: "h2", text: "Where this fits with the rest of the page" },
      {
        type: "p",
        text: "A meta description that promises same-day availability only works if the page it points to actually shows that — a booking widget, a phone number, hours. We write these last, after the page's content and answer box are finished, specifically so the promise in the snippet matches what the patient finds when they land. A description that overpromises gets a quick bounce, which tells Google the page did not satisfy the search. Search Console's click-through rate shows which descriptions need work; see [how to read Google Search Console for a medical practice](/guides/how-to-read-google-search-console-for-a-medical-practice-website).",
      },
    ],
    faqs: [
      {
        q: "Does the meta description affect Google rankings?",
        a: "Not directly. Google has stated the meta description is not a ranking signal. What it affects is click-through rate — how many people who see your result in search actually choose it — which is a different lever, but one that changes how much traffic a given ranking position produces.",
      },
      {
        q: "Why does Google show a different description than the one I wrote?",
        a: "Google's systems generate a description for each individual search query, pulling from your written tag or your page content, whichever it judges best matches what was searched. A specific, well-written description is used more often than a vague or keyword-stuffed one, but neither guarantees it every time.",
      },
      {
        q: "How long should a meta description be?",
        a: "Aim for roughly 140-155 characters. Google's search results don't enforce a strict limit — display width depends on device and query — but descriptions much longer than that get truncated mid-sentence, which reads as unfinished.",
      },
      {
        q: "Should every location page have a different meta description?",
        a: "Yes. Duplicate descriptions across city or service pages are flagged in Search Console's indexing reports and signal to Google that the pages are interchangeable. Each one should reference its specific city and service, not a copy-pasted template line.",
      },
      {
        q: "Can I include a phone number in a meta description?",
        a: "Yes, and for a local medical practice it often helps — it gives mobile searchers who are ready to call a reason to tap the result instead of reading further. Keep it short: '(561) 291-2681' uses fewer characters than 'call us today at.'",
      },
    ],
    citations: [
      {
        publisher: "Google Search Central",
        label: "Control your snippets in search results",
        href: "https://developers.google.com/search/docs/appearance/snippet",
      },
      {
        publisher: "Google Search Central",
        label: "Meta tags that Google understands",
        href: "https://developers.google.com/search/docs/crawling-indexing/special-tags",
      },
    ],
    links: [
      {
        href: "/guides/how-to-write-a-medical-service-page-that-ranks",
        label: "How to Write a Medical Service Page That Ranks",
        description: "The page the meta description is selling — structure, headings, and what to put above the fold.",
      },
      {
        href: "/guides/how-to-write-patient-faqs-that-answer-ai-search",
        label: "How to Write Patient FAQs That Answer AI Search",
        description: "The other half of answer-engine visibility: getting quoted directly instead of just clicked.",
      },
      {
        href: "/guides/get-a-medical-practice-into-ai-search-answers",
        label: "Get a Medical Practice into AI Search Answers",
        description: "What changes when the reader is an AI summarizer instead of a person scanning results.",
      },
      {
        href: "/services/local-seo-for-medical-practices",
        label: "Local SEO for Medical Practices",
        description: "The monthly service this page-level work is part of.",
      },
      {
        href: "/locations/medical-seo-west-palm-beach",
        label: "Medical SEO in West Palm Beach",
        description: "What this looks like applied to one real market.",
      },
    ],
  },

  // ── 505 ───────────────────────────────────────────────────────────────
  {
    slug: "fix-duplicate-google-business-profile-listings",
    keyword: "how to fix duplicate Google Business Profile listings for a medical practice",
    category: "How-to",
    title: "How to Fix Duplicate Google Business Profile Listings for a Medical Practice",
    metaTitle: "Fix Duplicate Google Business Profile Listings (Medical)",
    metaDescription:
      "Duplicate GBP listings split your reviews and confuse Google Maps. How to find, merge, or request removal of the extra one. Call (561) 291-2681.",
    answer:
      "Duplicate Google Business Profile listings usually come from a past move, a rebrand, or a second signup by a different staff member. Find every listing for your practice name and address with a Maps search, verify which one is correct and has your reviews, then flag the duplicate for removal from inside that incorrect listing — never create a new one on top of it.",
    author: "Gio LaRoche",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 7,
    sections: [
      { type: "h2", text: "How a medical practice ends up with two listings" },
      {
        type: "p",
        text: "We see the same four causes on almost every practice that calls us about this. The practice moved address and a new listing got created instead of the old one being updated. A provider left a group practice and their old listing, tied to the old suite number, kept running on its own. A staff member tried to claim the business and, not seeing an existing listing in their own search, created a second one instead. Or a data aggregator (a service that feeds business info to GPS and directory apps) auto-generated a listing from an old phone book or insurance directory record that nobody at the practice ever touched.",
      },
      {
        type: "p",
        text: "Whatever the cause, the effect is the same: your reviews, your call history, and your Google Maps ranking signal are now split across two profiles instead of consolidated on one. A patient searching your practice name sometimes sees the wrong one — closed hours, old address, zero reviews — and picks a competitor instead. Many duplicates start as small mismatches in a name, suite, or phone number, which our [NAP consistency guide](/guides/nap-consistency-what-breaks-it-and-how-to-fix-it) shows how to audit.",
      },
      { type: "h2", text: "Find every listing first" },
      {
        type: "p",
        text: "Search your exact practice name in Google Maps, and separately in Google Search, from a browser that is not logged into your GBP manager account (an incognito window works). Also search the old address if you moved, and any previous practice name if you rebranded. Write down every result's name, address, phone number, and review count before touching anything — you need the full picture before deciding which one is the keeper.",
      },
      { type: "h2", text: "Decide which listing is the correct one" },
      {
        type: "p",
        text: "In almost every case, keep the listing with the most reviews and the longest history — that is where your reputation and ranking signal already live. The duplicate to remove is the newer or emptier one, even if it happens to have the more current address. If the current-address listing is the empty one, update the correct listing's address first, then remove the duplicate — never the reverse, or you risk losing the reviews.",
      },
    ],
    faqs: [
      {
        q: "How long does it take Google to remove a duplicate listing?",
        a: "Google's own guidance says most duplicate-marking requests process within about a week, though a contested case — where the duplicate also has reviews or a different owner claim — can take several weeks and sometimes requires a follow-up through the Business Profile support chat.",
      },
      {
        q: "What happens to the reviews on the listing that gets removed?",
        a: "They're generally lost, not merged. Google does not automatically transfer reviews from a flagged duplicate to the surviving listing, which is exactly why choosing the listing with more reviews as the one you keep matters more than choosing the one with the current address.",
      },
      {
        q: "Can I just delete the duplicate myself?",
        a: "Only if you have manager or owner access to it. If a former employee or an aggregator created it, you typically don't — in that case you mark it as a duplicate from inside the listing you do own and verified, and Google reviews the claim.",
      },
      {
        q: "Will having two listings get my practice suspended?",
        a: "Not automatically, but it raises the odds. Google's guidelines for representing a business prohibit creating more than one listing per physical location, and an unresolved duplicate is one of the more common triggers for a manual review that can lead to a suspension of both.",
      },
      {
        q: "What if the duplicate shows a different address because we moved?",
        a: "Update the address on the listing you're keeping first, confirm it reflects correctly in Maps (can take a few days), and only then flag the old listing as a duplicate or permanently closed — removing it before the move is reflected can leave you with no correct listing live in the gap.",
      },
    ],
    citations: [
      {
        publisher: "Google Business Profile Help",
        label: "Fix a duplicate Business Profile",
        href: "https://support.google.com/business/answer/4564454",
      },
      {
        publisher: "Google Business Profile Help",
        label: "Guidelines for representing your business",
        href: "https://support.google.com/business/answer/3038177",
      },
    ],
    links: [
      {
        href: "/guides/fix-a-suspended-google-business-profile",
        label: "Fix a Suspended Google Business Profile",
        description: "The more serious version of a listing problem — what triggers a suspension and how to appeal one.",
      },
      {
        href: "/guides/choosing-google-business-profile-categories-for-a-medical-practice",
        label: "Choosing GBP Categories for a Medical Practice",
        description: "Get the surviving listing's category set right while you're already in the dashboard.",
      },
      {
        href: "/guides/how-to-run-a-local-seo-audit-for-a-medical-practice",
        label: "How to Run a Local SEO Audit for a Medical Practice",
        description: "A duplicate listing is one of the first things a proper audit checks for.",
      },
      {
        href: "/services/google-business-profile",
        label: "Google Business Profile Management",
        description: "The monthly service that keeps one clean, verified listing instead of this happening again.",
      },
      {
        href: "/locations/gbp-optimization-west-palm-beach",
        label: "GBP Optimization in West Palm Beach",
        description: "What ongoing GBP management looks like applied to one real market.",
      },
    ],
    howTo: {
      name: "How to remove a duplicate Google Business Profile",
      steps: [
        {
          name: "Search for every version of the listing",
          text: "Search your exact practice name (and old name/address if applicable) in Maps and Search from a logged-out browser. Record every result's address, phone, and review count.",
        },
        {
          name: "Confirm you have access to the correct listing",
          text: "Sign into Google Business Profile Manager and confirm you are an owner or manager on the listing with the most reviews and history. Claim it first if you are not yet verified.",
        },
        {
          name: "Update the correct listing's details",
          text: "If address, phone, or hours are out of date on the correct listing, fix those first so the surviving profile is accurate before you touch the duplicate.",
        },
        {
          name: "Mark the duplicate",
          text: "Open the duplicate listing in Maps, select 'Suggest an edit,' and choose 'This place no longer exists' or use the duplicate-reporting flow in Business Profile support if you have partial access to it.",
        },
        {
          name: "Follow up if it doesn't resolve",
          text: "If the duplicate is still live after about two weeks, contact Google Business Profile support directly through the help chat with both listing URLs — this is faster than resubmitting the same edit repeatedly.",
        },
      ],
    },
  },

  // ── 506 ───────────────────────────────────────────────────────────────
  {
    slug: "how-long-does-local-seo-take-for-a-medical-practice",
    keyword: "how long does local SEO take for a medical practice",
    category: "How-to",
    title: "How Long Does Local SEO Take for a Medical Practice?",
    metaTitle: "How Long Does Local SEO Take for a Medical Practice?",
    metaDescription:
      "Realistic timelines for local SEO at a Florida medical practice — what moves in 30 days, 90 days, and 6+ months, and why. Call (561) 291-2681.",
    answer:
      "Most medical practices see Google Business Profile changes reflect within days to a few weeks, early call and website-visit lift within 60-90 days, and meaningful Google Maps and organic ranking movement at 4-6 months. A practice with a thin or inconsistent online presence to start usually takes longer than one that already has reviews and a working website.",
    author: "Gio LaRoche",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 7,
    sections: [
      { type: "h2", text: "Why this question doesn't have a single number" },
      {
        type: "p",
        text: "Google's own Search Central documentation is direct about this: there is no fixed timeline for ranking changes, because it depends on how often Google's systems crawl and reprocess a given page and how competitive the market already is. A solo practice in a smaller Florida city with little competition can see movement faster than a multi-provider practice competing against five established groups in Miami for the same keyword. Anyone who quotes you an exact number of days without knowing your market is guessing.",
      },
      {
        type: "p",
        text: "What we can give you instead is what tends to move, and roughly when, based on running this for medical practices across Florida. Progress can also be interrupted by a broad ranking update, and [how to tell if a core update hit your practice site](/guides/google-core-updates-how-to-tell-if-your-practice-site-was-hit) explains how to check.",
      },
      { type: "h2", text: "The realistic timeline, phase by phase" },
      {
        type: "table",
        headers: ["Timeframe", "What typically moves"],
        rows: [
          [
            "0-30 days",
            "Google Business Profile fixes (categories, hours, services, photos) reflect in Maps within days. New website pages get discovered and crawled, but rarely rank yet.",
          ],
          [
            "30-90 days",
            "First ranking movement for lower-competition, longer search phrases. Call and direction-request volume from GBP often ticks up before organic traffic does.",
          ],
          [
            "90-180 days",
            "Service and location pages start ranking for their intended terms if the on-page work and review growth have been consistent. This is usually when a practice first sees a real increase in new-patient calls traceable to search.",
          ],
          [
            "6+ months",
            "Competitive, high-value terms (the ones a hospital system or large group practice also wants) move here, if at all — these take sustained review growth, content, and sometimes paid search to support while organic catches up.",
          ],
        ],
      },
      { type: "h2", text: "What makes it faster or slower" },
      {
        type: "ul",
        items: [
          "Starting point matters most. A practice with zero GBP reviews and a five-year-old website takes longer than one with 40 reviews and a site that just needs restructuring.",
          "Review velocity is one of the strongest local-ranking signals Google has confirmed matters, and it's one of the few things a practice directly controls week to week.",
          "Competition in the specific city and specialty — therapy in a small town moves faster than dermatology in Miami.",
          "Technical health of the site (speed, mobile usability, broken pages) can stall everything else if it's bad enough that Google struggles to crawl it.",
          "Consistency of the work. SEO compounds; a burst of effort for one month followed by three months of nothing resets much of the progress.",
        ],
      },
      { type: "h2", text: "What \"it's working\" looks like before rankings move" },
      {
        type: "p",
        text: "The mistake we see most is a practice judging the first 60 days purely by Google ranking position, which is the slowest-moving signal. Watch Google Business Profile insights (calls, direction requests, website clicks from the listing) and Search Console impressions (how often your pages are shown, even before they're clicked) instead — both typically move weeks before rankings do, and both are early, honest evidence the work is taking hold.",
      },
      { type: "h2", text: "What to do if nothing has moved by month four" },
      {
        type: "p",
        text: "If GBP insights and Search Console impressions are both flat at the 90-day mark, the problem usually isn't patience — it's that one of the inputs above was never actually fixed. The three most common culprits we find on a stalled account: the technical health of the site is bad enough that Google can't crawl new or updated pages properly, the practice has fewer than 10-15 Google reviews so there's no local-ranking signal to work with yet, or the work itself was inconsistent (a strong first month, then nothing for the following two). Before extending the timeline further, re-run a basic audit of those three things rather than assuming more time alone will fix it. Track progress month to month in Search Console, using [this guide to reading its reports](/guides/how-to-read-google-search-console-for-a-medical-practice-website).",
      },
      {
        type: "p",
        text: "It's also worth separating a stalled Google Business Profile from a stalled website. A GBP listing with good reviews and complete information can show real Maps movement even while the website's organic rankings are still catching up — they run on different clocks, and conflating the two can make a practice think nothing is working when half the picture is actually fine.",
      },
    ],
    faqs: [
      {
        q: "How fast will my Google Business Profile changes show up?",
        a: "Most edits — hours, categories, services, photos — reflect in Google Maps within a few days to about two weeks. More significant changes, like a new address or a reinstated listing, can take longer and sometimes trigger a re-verification step.",
      },
      {
        q: "Can local SEO work faster with a bigger budget?",
        a: "To a point. More budget can fund faster content production and a parallel Google Ads campaign to cover the gap while organic builds, but it cannot make Google crawl and re-rank a page faster than its own systems choose to — there's no way to pay for instant ranking.",
      },
      {
        q: "Why did my rankings drop right after we started?",
        a: "A short dip after site changes is common and usually temporary — Google is re-crawling and re-evaluating updated pages, which can cause a brief fluctuation before the new, improved version settles into its ranking. It's one reason we don't judge results from the first 30 days alone.",
      },
      {
        q: "Does a brand-new practice take longer than an established one?",
        a: "Generally yes, mainly because a new practice also lacks the reviews and link history an established one has built up. The GBP and on-site work move at the same pace; the review and reputation signal is what takes longer to catch up from zero.",
      },
      {
        q: "Is 6 months a guarantee of results?",
        a: "No — it's a realistic point by which most well-run local SEO programs show measurable movement, not a guarantee. Market competitiveness and starting condition both affect the actual timeline, and anyone promising a guaranteed ranking by a specific date is not describing how Google's systems work.",
      },
    ],
    citations: [
      {
        publisher: "Google Search Central",
        label: "Ranking and how Search works",
        href: "https://developers.google.com/search/docs/essentials",
      },
      {
        publisher: "Google Search Central",
        label: "Understanding search results and ranking changes",
        href: "https://developers.google.com/search/docs/monitor-debug/understanding-rankings",
      },
    ],
    links: [
      {
        href: "/guides/how-to-run-a-local-seo-audit-for-a-medical-practice",
        label: "How to Run a Local SEO Audit for a Medical Practice",
        description: "The starting-point assessment that determines where a practice falls on this timeline.",
      },
      {
        href: "/guides/how-much-does-medical-seo-cost",
        label: "How Much Does Medical SEO Cost?",
        description: "The budget question that usually comes right after the timeline question.",
      },
      {
        href: "/guides/new-practice-marketing-checklist",
        label: "New Practice Marketing Checklist",
        description: "What to have in place in month one to start this timeline from the fastest possible point.",
      },
      {
        href: "/services/local-seo-for-medical-practices",
        label: "Local SEO for Medical Practices",
        description: "The monthly program that runs this timeline for a practice.",
      },
      {
        href: "/locations/medical-seo-florida",
        label: "Medical SEO in Florida",
        description: "What this looks like run across a statewide, multi-city practice.",
      },
    ],
  },

  // ── 507 ───────────────────────────────────────────────────────────────
  {
    slug: "core-web-vitals-checklist-for-a-medical-practice-website",
    keyword: "core web vitals checklist for a medical practice website",
    category: "Checklist",
    title: "Core Web Vitals Checklist for a Medical Practice Website",
    metaTitle: "Core Web Vitals Checklist for Medical Websites (2026)",
    metaDescription:
      "The Core Web Vitals checklist we run on every Florida medical practice site — what to test, the current pass thresholds, and common fixes. Call (561) 291-2681.",
    answer:
      "Core Web Vitals are three Google-defined measurements of real-world page experience — loading speed (LCP), visual stability (CLS), and responsiveness (INP) — and a medical practice site should test every page type (homepage, a service page, a location page) with Google's free PageSpeed Insights tool, since a slow or unstable page loses patients before they ever read it.",
    author: "Gio LaRoche",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 6,
    sections: [
      { type: "h2", text: "The three metrics, and the current pass/fail line" },
      {
        type: "table",
        headers: ["Metric", "What it measures / passing threshold"],
        rows: [
          ["LCP (Largest Contentful Paint)", "Time until the largest visible element (usually a hero image or headline) finishes loading. Google's threshold: 2.5 seconds or less is \"good.\""],
          ["CLS (Cumulative Layout Shift)", "How much visible content jumps around as the page loads (an image popping in and pushing the phone number down, for example). Threshold: 0.1 or less."],
          ["INP (Interaction to Next Paint)", "How quickly the page responds after a tap or click — booking a button, opening a menu. Threshold: 200 milliseconds or less. (INP replaced the older First Input Delay metric in 2024.)"],
        ],
      },
      {
        type: "p",
        text: "These are field metrics, meaning Google measures them from real visitors' browsers, not a lab simulation, through the Chrome User Experience Report. A page can look fast in a quick manual check and still fail Core Web Vitals if real visitors on real phones over real cellular connections experience it differently — which, for a medical practice, most of your patients are.",
      },
      { type: "h2", text: "Why this matters for a medical practice specifically" },
      {
        type: "p",
        text: "Google has confirmed page experience is one factor among many in ranking, smaller than content relevance, but it is also one of the only factors under your direct technical control. More immediately, a slow-loading page or one where the phone number shifts position mid-load costs you patients who simply leave — Google's own research on this consistently shows bounce rate climbing sharply as load time increases past a few seconds, and a patient looking for same-day care has the least patience of almost any searcher. Speed is only one half of mobile performance; the other is whether Google indexes your full phone version, covered in [mobile-first indexing explained for a practice website](/guides/mobile-first-indexing-explained-for-a-medical-practice-website).",
      },
      { type: "h2", text: "The checklist" },
      {
        type: "ul",
        items: [
          "Run the homepage, one service page, and one location page through PageSpeed Insights separately — a single site-wide average hides pages that are actually failing.",
          "Check the Mobile score first, not Desktop. Most medical-practice traffic is mobile, and Google's field data weights mobile and desktop separately.",
          "If LCP is slow, check image size before anything else — an unoptimized hero photo is the single most common cause on a practice site we've audited.",
          "If CLS is high, check for images and embeds (like a map or booking widget) that don't have a reserved width/height, which causes the page to jump as they load.",
          "If INP is slow, check for third-party scripts (chat widgets, old analytics tags, review-platform embeds) stacking up — each one adds processing time before the page can respond to a tap.",
          "Re-test after any theme, plugin, or redesign change. A vendor update can silently regress a metric that was previously passing.",
          "Set a quarterly recheck. Core Web Vitals thresholds and the metrics themselves have changed before (INP replacing FID in 2024) and will again.",
        ],
      },
      { type: "h2", text: "What we do not recommend" },
      {
        type: "p",
        text: "Chasing a perfect 100 PageSpeed score is not the goal and can cost more than it's worth — stripping out a genuinely useful booking widget or lazy-loading content a patient needs immediately in the name of a few tenths of a second is a bad trade. The goal is passing Google's \"good\" threshold on all three metrics, consistently, across your real page types — not a leaderboard score. After speed, confirm Google can crawl the site at all; see [XML sitemaps and robots.txt for a practice website](/guides/xml-sitemaps-and-robots-txt-for-a-medical-practice-website).",
      },
    ],
    faqs: [
      {
        q: "What is a good Core Web Vitals score for a medical website?",
        a: "Passing means LCP under 2.5 seconds, CLS under 0.1, and INP under 200 milliseconds, measured from real visitor data in Google's Chrome User Experience Report — not a one-time lab test. PageSpeed Insights shows both the field data (if your site has enough traffic to qualify) and a lab simulation.",
      },
      {
        q: "Do Core Web Vitals really affect Google rankings?",
        a: "Yes, but as a smaller factor than content quality and relevance, per Google's own statements. It mainly works as a tiebreaker between pages that are otherwise similarly relevant, and it directly affects how many visitors stay on the page regardless of ranking.",
      },
      {
        q: "My site passed last quarter and fails now — why?",
        a: "A plugin update, a new chat widget, a redesign, or even a new ad script added by a marketing vendor can silently push a previously passing page below threshold. This is why we recheck quarterly rather than treating a single pass as permanent.",
      },
      {
        q: "Is a slow site worse than having no site at all for local SEO?",
        a: "Not quite, but it comes close in practical terms — a slow site still gets crawled and indexed, but it both ranks worse on the margin and converts far fewer of the visitors it does get, which is often the bigger loss for a practice relying on it for new patients.",
      },
      {
        q: "Does a mobile-friendly design automatically pass Core Web Vitals?",
        a: "No. \"Mobile-friendly\" (responsive layout, readable text, tappable buttons) is a separate check from Core Web Vitals, which measures actual load speed and stability. A responsive site can still fail Vitals if it loads a heavy hero image or an unoptimized third-party script.",
      },
    ],
    citations: [
      { publisher: "web.dev (Google)", label: "Core Web Vitals", href: "https://web.dev/articles/vitals" },
      { publisher: "Google", label: "PageSpeed Insights", href: "https://pagespeed.web.dev/" },
    ],
    links: [
      {
        href: "/guides/medical-website-launch-seo-checklist",
        label: "Medical Website Launch SEO Checklist",
        description: "Core Web Vitals is one section of the full pre-launch checklist.",
      },
      {
        href: "/guides/medical-practice-website-cost",
        label: "Medical Practice Website Cost",
        description: "What it typically costs to fix the kind of performance issues this checklist surfaces.",
      },
      {
        href: "/guides/optimizing-a-medical-practice-website-for-voice-search",
        label: "Optimizing a Medical Website for Voice Search",
        description: "Another technical-SEO pass worth running alongside this one.",
      },
      {
        href: "/services/medical-practice-website-design",
        label: "Medical Practice Website Design",
        description: "The service that builds and fixes sites to pass these thresholds from the start.",
      },
      {
        href: "/locations/medical-website-design-west-palm-beach",
        label: "Medical Website Design in West Palm Beach",
        description: "What this work looks like applied to one real market.",
      },
      {
        href: "/guides/how-much-website-traffic-does-a-medical-practice-need",
        label: "How Much Website Traffic Does a Medical Practice Actually Need?",
        description: "Why page speed is a conversion-rate fix, not just a technical one.",
      },
    ],
  },

  // ── 508 ───────────────────────────────────────────────────────────────
  {
    slug: "schema-markup-for-a-medical-practice-website-explained",
    keyword: "schema markup for a medical practice website explained",
    category: "How-to",
    title: "Schema Markup for a Medical Practice Website, Explained",
    metaTitle: "Schema Markup for Medical Practice Websites, Explained",
    metaDescription:
      "What schema markup is, which types matter for a medical practice, and how to check if yours is working. Plain language. Call (561) 291-2681.",
    answer:
      "Schema markup is structured code added to a webpage that states facts directly to Google and AI search tools — your practice name, address, hours, services, and FAQ answers — instead of making them infer it from prose. A medical practice site should carry LocalBusiness or MedicalBusiness, Service, FAQPage, and BreadcrumbList schema at minimum, verified with Google's free Rich Results Test.",
    author: "Gio LaRoche",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 7,
    sections: [
      { type: "h2", text: "What schema markup actually is" },
      {
        type: "p",
        text: "Every page on your site has visible text a human reads, and it can also carry a separate block of code — usually JSON-LD, a specific format — that states the same facts in a structure a machine can parse without guessing. Instead of Google's systems inferring from a paragraph that your practice is open \"Monday through Thursday, 8 to 5, Friday mornings,\" the schema states openingHours: [\"Mo-Th 08:00-17:00\", \"Fr 08:00-13:00\"] directly. Schema.org is the shared vocabulary (jointly maintained by Google, Microsoft, Yahoo, and Yandex) that defines what these fields are called and what they mean, so every search engine reading it agrees on the interpretation.",
      },
      { type: "h2", text: "Why it matters more now than it used to" },
      {
        type: "p",
        text: "Schema has always helped traditional Google results — it's what produces star ratings, FAQ dropdowns, and breadcrumb trails directly in the search listing. What's changed is that AI-generated answers (Google's AI Overviews, ChatGPT browsing, Perplexity) lean on structured data even more heavily than traditional ranking does, because it's the fastest way for those systems to extract a clean, attributable fact without summarizing an entire paragraph and risking an error. A medical practice that wants to be the source an AI answer cites needs the facts stated in a format those systems can lift directly, which matters even more once you understand [what AI Overviews mean for a medical practice's organic traffic](/guides/what-ai-overviews-mean-for-medical-practice-organic-traffic) in the first place. Remember that markup must also exist on the mobile version of a page, which is the subject of [mobile-first indexing for a medical practice website](/guides/mobile-first-indexing-explained-for-a-medical-practice-website).",
      },
      { type: "h2", text: "The schema types a medical practice site needs" },
      {
        type: "table",
        headers: ["Schema type", "What it declares"],
        rows: [
          ["LocalBusiness / MedicalBusiness", "Your practice's name, address, phone, hours, and category — the core entity every other schema type on the site references back to."],
          ["Service", "Each specific service you offer (e.g. \"Family Medicine,\" \"Botox\") as its own named, describable thing, not just a heading in body text."],
          ["FAQPage", "Question-and-answer pairs that can surface as an expandable dropdown directly in Google results, and are the clearest format for an AI system to quote verbatim."],
          ["BreadcrumbList", "The page's position in your site's structure (Home > Services > Family Medicine), which both helps ranking and often renders directly in the search snippet."],
          ["Physician / Person", "Named providers with their credentials, when the page is about a specific provider rather than the practice generally — never invented or unverified."],
        ],
      },
      { type: "h2", text: "How to check if your schema is actually working" },
      {
        type: "p",
        text: "Having schema on the page and having valid schema are different things — a single typo in the JSON-LD can silently invalidate the entire block, and Google will simply ignore it with no visible error on the page itself. Paste any live URL into Google's Rich Results Test, and it will list every schema type it detected and flag specific errors or warnings. Run this after any site change, redesign, or platform migration — we've seen a working schema graph get wiped entirely by a theme update with nothing on the visible page indicating it happened. Organization markup also supports recognition by Google's knowledge graph, as described in [what a Knowledge Panel is and whether a practice can get one](/guides/google-knowledge-panel-for-a-medical-practice).",
      },
      { type: "h2", text: "What not to do" },
      {
        type: "p",
        text: "Never mark up a fact that isn't true to try to win a richer result — a review count you don't have, a credential a provider doesn't hold, aggregateRating without real, verifiable review data behind it. Google's structured data guidelines explicitly prohibit this, and the penalty for being caught is a structured-data-specific manual action that can strip rich results sitewide, which is a worse outcome than never having added the markup at all.",
      },
    ],
    faqs: [
      {
        q: "Does schema markup directly improve Google rankings?",
        a: "Not on its own — Google has said structured data is not a direct ranking factor. What it does is make your page eligible for richer search results (FAQ dropdowns, breadcrumbs, star ratings) and makes your facts easier for AI search tools to extract and cite accurately.",
      },
      {
        q: "Can I see my schema markup without any technical tools?",
        a: "Not in the normal page view — it's invisible to a visitor. The easiest free way is Google's Rich Results Test: paste in your URL and it lists every schema type detected plus any errors, without needing to view page source.",
      },
      {
        q: "Will adding schema make my page load slower?",
        a: "The effect is negligible — a JSON-LD block is typically a few kilobytes of text, far smaller than a single unoptimized image. It has no meaningful impact on Core Web Vitals or load time.",
      },
      {
        q: "What happens if my schema has an error in it?",
        a: "Google generally just ignores the invalid portion rather than penalizing the page, but it also means you lose whatever rich-result eligibility that schema type would have provided. Errors are common after redesigns, which is why checking with the Rich Results Test after any site change matters.",
      },
      {
        q: "Is FAQPage schema worth adding to every page?",
        a: "Only where the page has genuine, truthfully-answered questions — Google's guidelines are specific that FAQPage markup should reflect real content on the page, not be added purely to try to win the dropdown result. A service page with 4-6 real patient questions is a good fit; a generic page with none is not.",
      },
    ],
    citations: [
      { publisher: "Google Search Central", label: "Understand how structured data works", href: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data" },
      { publisher: "Schema.org", label: "Schema.org vocabulary", href: "https://schema.org/" },
    ],
    links: [
      {
        href: "/guides/how-to-write-patient-faqs-that-answer-ai-search",
        label: "How to Write Patient FAQs That Answer AI Search",
        description: "FAQPage schema needs real content behind it — this is how to write that content.",
      },
      {
        href: "/guides/get-a-medical-practice-into-ai-search-answers",
        label: "Get a Medical Practice into AI Search Answers",
        description: "Schema is one piece of a larger AI-visibility strategy — this guide covers the rest.",
      },
      {
        href: "/guides/how-to-write-a-doctor-bio-page-that-ranks",
        label: "How to Write a Doctor Bio Page That Ranks",
        description: "Where Physician/Person schema gets applied in practice.",
      },
      {
        href: "/services/ai-seo",
        label: "AI SEO",
        description: "The service that builds and maintains a practice's full schema graph.",
      },
      {
        href: "/services/seo",
        label: "SEO for Medical Practices",
        description: "The broader technical and content program schema sits inside.",
      },
    ],
  },

  // ── 509 ───────────────────────────────────────────────────────────────
  {
    slug: "google-ads-negative-keywords-checklist-for-a-medical-practice",
    keyword: "google ads negative keywords checklist for a medical practice",
    category: "Checklist",
    title: "Google Ads Negative Keywords Checklist for a Medical Practice",
    metaTitle: "Google Ads Negative Keywords Checklist for Medical Practices",
    metaDescription:
      "The negative keyword list every Florida medical practice running Google Ads should set on day one, and how to keep finding new ones. Call (561) 291-2681.",
    answer:
      "Negative keywords stop your Google Ads from showing on searches you don't want to pay for — \"jobs,\" \"salary,\" \"free,\" and a competitor's name, for example. A medical practice should load a standard exclusion list before the first dollar spends, then review the search terms report weekly for the first month to catch the waste a generic list can't predict.",
    author: "Gio LaRoche",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 6,
    sections: [
      { type: "h2", text: "What a negative keyword does" },
      {
        type: "p",
        text: "Google Ads matches your keywords to real searches using its own judgment about relevance, which means a campaign targeting \"family doctor near me\" can also show for \"family doctor salary,\" \"family doctor jobs,\" or \"family doctor vs internist\" if you haven't told it not to. A negative keyword is an explicit instruction: never show my ad for a search containing this term. Every dollar spent on a click from an irrelevant search is a dollar not spent reaching an actual patient.",
      },
      { type: "h2", text: "The standard list every medical practice needs on day one" },
      {
        type: "table",
        headers: ["Category", "Example negatives"],
        rows: [
          ["Employment searches", "jobs, hiring, careers, salary, resume, employment"],
          ["Free / DIY intent", "free, diy, home remedy, how to do it myself"],
          ["Education / research only", "definition, what is, symptoms of, course, certification, training program"],
          ["Wrong audience", "for sale, wholesale, supplier, manufacturer (common on medspa/aesthetics campaigns targeted by product suppliers)"],
          ["Competitor brand names", "Add specific competitor practice names — bidding on them is a separate, deliberate strategy decision, not something to do by accident"],
        ],
      },
      { type: "h2", text: "Specialty-specific additions" },
      {
        type: "ul",
        items: [
          "Therapy/mental health: \"hotline,\" \"crisis,\" \"emergency\" — searches for immediate crisis help are not booking-intent searches and routing that budget there helps no one, including the searcher, who needs a different resource.",
          "Aesthetics/medspa: \"at home,\" \"kit,\" \"amazon,\" \"diy\" — a large share of medspa search volume is people looking for consumer products, not a licensed provider.",
          "Urgent care: \"telehealth,\" \"online doctor\" — unless you specifically offer telehealth, these searchers want a different service than an in-person visit.",
          "Any practice taking insurance: \"cash only,\" \"no insurance needed\" if that's not your model, and the reverse if it is — mismatched intent here produces real wasted spend both directions.",
        ],
      },
      { type: "h2", text: "Where to find the ones a generic list misses" },
      {
        type: "p",
        text: "The starting list above catches the predictable waste. The search terms report — the literal list of what people typed before your ad showed — catches what's specific to your market and campaign. Pull it weekly for the first month of any new campaign, and monthly after that. Anything that got a click but clearly wasn't a real prospect (a city you don't serve, a service you don't offer, a question-only phrase with no booking intent) becomes a new negative.",
      },
      { type: "h2", text: "A mistake we see often: over-negating" },
      {
        type: "p",
        text: "It's possible to go too far — adding a negative keyword that's broader than intended can silently block legitimate searches too. \"Pain\" as a broad-match negative on a pain-management campaign, for instance, can exclude searches you actually want. Add negatives at the most specific match type that solves the problem, and review the list itself periodically, not just the search terms feeding it.",
      },
      { type: "h2", text: "Negative keyword lists at the account level vs. the campaign level" },
      {
        type: "p",
        text: "Google Ads lets you build a shared negative keyword list at the account level and apply it across every campaign, instead of re-adding the same standard exclusions (jobs, free, salary) one campaign at a time. For a practice running separate campaigns per service line — one for primary care, one for a specific procedure, one for a seasonal promotion — a shared list for the universal exclusions, plus a campaign-specific list for anything unique to that service, keeps the setup both faster to maintain and less likely to drift out of sync between campaigns.",
      },
      {
        type: "p",
        text: "This split also makes auditing easier. When a new campaign launches, you can see at a glance which negatives came from the shared baseline and which were added specifically for that campaign's own search terms report — useful six months later when deciding whether an exclusion still makes sense or was tied to a promotion that already ended.",
      },
    ],
    faqs: [
      {
        q: "How many negative keywords should a medical practice campaign have?",
        a: "There's no fixed number — a new campaign typically starts with 20-40 from a standard exclusion list and grows from there based on the search terms report. A mature, well-tuned campaign can carry several hundred, built up over months of real search data.",
      },
      {
        q: "Can negative keywords hurt my campaign if I add too many?",
        a: "Yes, if they're too broad. A negative keyword set at broad match can accidentally block searches you actually wanted. Check the specific match type, and periodically review the negative list itself for anything excluding real prospects.",
      },
      {
        q: "Do negative keywords cost anything to add?",
        a: "No — adding negative keywords is free and does not count against your budget. The entire point is reducing wasted spend, so there's no reason to hold back on the standard list once a problem term is identified.",
      },
      {
        q: "Should I add competitor names as negative keywords?",
        a: "Only if you don't want to bid on them at all. Many practices deliberately do bid on competitor names as a separate strategy to appear when someone searches a competitor directly — that's a conscious choice, not an oversight, and belongs in your keyword list, not your negative list.",
      },
      {
        q: "How often should the negative keyword list be reviewed?",
        a: "Weekly for the first month of a new campaign, when the biggest waste surfaces fastest, then monthly for an established campaign. Seasonal or promotional campaigns should get a fresh review each time they relaunch, since search behavior shifts with them.",
      },
    ],
    citations: [
      { publisher: "Google Ads Help", label: "Add negative keywords to your campaign", href: "https://support.google.com/google-ads/answer/2453972" },
      { publisher: "Google Ads Help", label: "About keyword matching options", href: "https://support.google.com/google-ads/answer/7478529" },
    ],
    links: [
      {
        href: "/guides/google-ads-cost-for-a-medical-practice",
        label: "Google Ads Cost for a Medical Practice",
        description: "Negative keywords are one of the cheapest ways to improve what that budget actually buys.",
      },
      {
        href: "/guides/seo-vs-google-ads-for-a-therapy-practice",
        label: "SEO vs Google Ads for a Therapy Practice",
        description: "Where paid search fits relative to organic for a practice weighing both.",
      },
      {
        href: "/guides/how-to-measure-roi-on-medical-practice-marketing",
        label: "How to Measure ROI on Medical Practice Marketing",
        description: "What to track once wasted spend is cut out — the real conversion numbers underneath.",
      },
      {
        href: "/services/google-ads",
        label: "Google Ads for Medical Practices",
        description: "The managed service that builds and maintains lists like this one.",
      },
      {
        href: "/locations/google-ads-management-west-palm-beach",
        label: "Google Ads Management in West Palm Beach",
        description: "What this work looks like applied to one real market.",
      },
      {
        href: "/guides/google-ads-quality-score-explained-for-a-medical-practice",
        label: "Google Ads Quality Score, Explained for a Medical Practice",
        description: "The other account-structure lever that works alongside negative keywords.",
      },
    ],
  },

  // ── 510 ───────────────────────────────────────────────────────────────
  {
    slug: "email-marketing-compliance-for-a-medical-practice",
    keyword: "email marketing compliance for a medical practice",
    category: "Checklist",
    title: "Email Marketing Compliance for a Medical Practice",
    metaTitle: "Email Marketing Compliance for Medical Practices (CAN-SPAM)",
    metaDescription:
      "What the CAN-SPAM Act and HIPAA require for medical-practice email marketing — consent, opt-out, PHI. Not legal advice. Call (561) 291-2681.",
    answer:
      "Commercial email from a medical practice is governed primarily by the federal CAN-SPAM Act — accurate sender info, a working unsubscribe link honored within 10 business days, and no deceptive subject lines — plus HIPAA if the email references a patient's specific condition or treatment. This is a plain-language summary of the requirements, not legal advice; confirm specifics with a healthcare attorney or compliance officer.",
    author: "Liam Costello",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 7,
    sections: [
      { type: "h2", text: "Two separate laws apply, and they cover different things" },
      {
        type: "p",
        text: "CAN-SPAM, enforced by the FTC, governs the mechanics of any commercial email — practice newsletters, promotional offers, appointment-reminder marketing — regardless of what kind of business sends it. HIPAA governs something different: whether the email's content discloses Protected Health Information, meaning information tied to an identifiable patient's health condition, treatment, or payment. A practice can violate either one independently of the other, so both need separate attention.",
      },
      { type: "h2", text: "CAN-SPAM: what every commercial email needs" },
      {
        type: "ul",
        items: [
          "Accurate \"From,\" \"To,\" and routing information — the sender name and reply-to address must genuinely be yours, not disguised.",
          "A subject line that doesn't mislead about the email's content — \"Your appointment is confirmed\" on a promotional email is a violation even if the email also happens to mention appointments.",
          "Identification as an advertisement, where the message is primarily promotional — this doesn't require the word \"ad\"; a reasonable recipient understanding it's marketing generally satisfies it.",
          "Your practice's valid physical postal address, somewhere in the email.",
          "A clear, conspicuous way to opt out of future email, and that request has to be honored within 10 business days of receiving it — not at the next newsletter cycle.",
          "No selling or transferring a recipient's email address to another company once they've opted out, ever.",
        ],
      },
      { type: "h2", text: "HIPAA: when a marketing email also becomes a PHI question" },
      {
        type: "p",
        text: "A general \"we're now offering Saturday appointments\" blast to your full patient list is marketing content, not PHI, because it doesn't reference anything specific to the individual recipient. It becomes a different situation the moment the content ties back to a specific patient's condition or treatment — a reminder referencing a specific diagnosis, or a segment list built by filtering patients by a condition. HHS's guidance on HIPAA and marketing communications is the authoritative source here, and when in doubt, the safer approach is to keep patient-list segmentation based on administrative facts (new patient vs. established, appointment type scheduled) rather than clinical ones.",
      },
      { type: "h2", text: "Where consent fits in" },
      {
        type: "p",
        text: "CAN-SPAM does not require opt-in consent before the first commercial email the way some international email laws do — it's an opt-out standard. But most medical-practice patient-management and email platforms have their own stricter terms of service requiring documented consent before adding someone to a marketing list, and a practice that collected an email address solely for appointment reminders should not assume that permission extends to a separate promotional newsletter without a clear, separate opt-in for that specific use.",
      },
      { type: "h2", text: "Practical setup for a practice starting this" },
      {
        type: "ol",
        items: [
          "Use a reputable email marketing platform (not a personal email account) — most handle the unsubscribe mechanics and sender authentication automatically, which removes a large share of the compliance risk.",
          "Keep the patient's clinical record and the marketing email list as separate systems with separate access, so a marketing send can never accidentally pull or reference clinical detail.",
          "Write a one-page internal policy — who can send, what gets reviewed before sending, how opt-outs get processed — so this isn't dependent on one person remembering the rules.",
          "When in doubt about a specific campaign, ask: would this email make sense to someone who isn't a patient yet, or does it only make sense because we know something about this specific person's health? The second case needs a HIPAA review before it goes out.",
        ],
      },
    ],
    faqs: [
      {
        q: "Is this page legal advice?",
        a: "No. This is a plain-language summary of CAN-SPAM and HIPAA marketing requirements for general awareness, not a substitute for review by a healthcare attorney or your practice's compliance officer, especially before launching a new type of campaign.",
      },
      {
        q: "Does CAN-SPAM apply to appointment reminder emails?",
        a: "Generally no — CAN-SPAM specifically exempts \"transactional or relationship\" messages, which includes appointment confirmations and reminders tied to an existing patient relationship, as long as the message doesn't also contain substantial promotional content.",
      },
      {
        q: "How fast do we have to honor an unsubscribe request?",
        a: "CAN-SPAM requires unsubscribe requests be processed within 10 business days. Most email marketing platforms handle this automatically and immediately, which is one reason to use one rather than sending bulk email manually.",
      },
      {
        q: "Can we email our full patient list about a new service we're offering?",
        a: "Generally yes, as a CAN-SPAM-compliant marketing email, as long as it doesn't reference anything specific to individual recipients' health conditions. If the list was segmented by a clinical factor to build that send, get a HIPAA compliance review first.",
      },
      {
        q: "Does a patient portal message count as marketing email?",
        a: "Typically not under CAN-SPAM if it's a secure, patient-initiated portal rather than open email, but portal messaging that includes promotional content still raises the same HIPAA question about what clinical information, if any, it's built around. Check with your EHR vendor's compliance documentation for your specific platform.",
      },
    ],
    citations: [
      { publisher: "Federal Trade Commission", label: "CAN-SPAM Act: A Compliance Guide for Business", href: "https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business" },
      { publisher: "U.S. Dept. of Health & Human Services, OCR", label: "Marketing and HIPAA", href: "https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/marketing/index.html" },
    ],
    links: [
      {
        href: "/guides/text-message-marketing-compliance-for-a-medical-practice",
        label: "Text Message Marketing Compliance for a Medical Practice",
        description: "The equivalent rules for SMS — a separate law (TCPA), stricter consent requirement.",
      },
      {
        href: "/guides/hipaa-safe-tracking-for-a-medical-website",
        label: "HIPAA-Safe Tracking for a Medical Website",
        description: "The same PHI question applied to website analytics and ad pixels instead of email.",
      },
      {
        href: "/guides/healthcare-ad-compliance-checklist",
        label: "Healthcare Ad Compliance Checklist",
        description: "The broader compliance checklist this email-specific guide sits inside.",
      },
      {
        href: "/services/digital-marketing-for-independent-medical-practices",
        label: "Digital Marketing for Independent Medical Practices",
        description: "The full-service program that includes compliant email and patient communication.",
      },
      {
        href: "/primary-care",
        label: "Primary Care Marketing",
        description: "How this fits the broader marketing program for a primary care practice.",
      },
    ],
  },

  // ── 511 ───────────────────────────────────────────────────────────────
  {
    slug: "text-message-marketing-compliance-for-a-medical-practice",
    keyword: "text message marketing compliance for a medical practice",
    category: "Checklist",
    title: "Text Message Marketing Compliance for a Medical Practice",
    metaTitle: "Text Message Marketing Compliance for Medical Practices (TCPA)",
    metaDescription:
      "What the TCPA requires before a medical practice texts patients for marketing — written consent, opt-out, and the HIPAA overlap. Call (561) 291-2681.",
    answer:
      "The Telephone Consumer Protection Act (TCPA) requires a medical practice to get prior express written consent before sending marketing text messages to a patient's cell phone — a higher bar than email's opt-out standard — plus a clear STOP opt-out honored immediately. This is a plain-language summary, not legal advice; confirm specifics with a healthcare attorney before launching a texting program.",
    author: "Liam Costello",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 7,
    sections: [
      { type: "h2", text: "Why text messaging is held to a higher bar than email" },
      {
        type: "p",
        text: "The TCPA, enforced by the FCC, treats a text message to a cell phone differently than a marketing email, largely because a text interrupts a device people carry constantly and often pay per-message or data-plan costs on. For marketing texts specifically, the law requires prior express written consent — meaning the patient affirmatively agreed, in writing (which can be an electronic signature or a clear checkbox, not a verbal mention), before you send anything promotional. This is stricter than CAN-SPAM's opt-out standard for email, where you can email first and let someone unsubscribe.",
      },
      { type: "h2", text: "What counts as \"marketing\" vs. what doesn't" },
      {
        type: "table",
        headers: ["Likely exempt (transactional)", "Requires written consent (marketing)"],
        rows: [
          ["\"Your appointment is confirmed for Tuesday at 2pm\"", "\"We're offering 20% off a new patient visit this month\""],
          ["\"Reply C to confirm or R to reschedule\"", "\"Refer a friend and get a free consult\""],
          ["A one-time password or account security code", "A seasonal promotion or service announcement blast"],
        ],
      },
      {
        type: "p",
        text: "The line isn't always obvious — a message that's mostly transactional but adds a promotional line (\"Your appointment is confirmed. Also, ask about our new Saturday hours!\") can push the whole message into marketing territory under TCPA's own interpretation of mixed-content messages. When a message blends both purposes, treat it as marketing and require the written consent.",
      },
      { type: "h2", text: "What written consent needs to include" },
      {
        type: "ul",
        items: [
          "Clear disclosure that the patient is agreeing to receive marketing/promotional text messages, not just appointment reminders.",
          "The practice's name as the sender.",
          "A statement that consent is not a condition of receiving care — a patient has to be free to decline texting without it affecting treatment.",
          "Message frequency expectations (e.g. \"up to 4 messages per month\") and that message/data rates may apply.",
          "The opt-out method, stated plainly — almost always \"reply STOP to opt out.\"",
          "A real signature or affirmative digital action (checking an unchecked box, not a pre-checked one) — not inferred from giving a phone number for a different purpose like scheduling.",
        ],
      },
      { type: "h2", text: "The opt-out has to work immediately, every time" },
      {
        type: "p",
        text: "Every marketing text needs a working STOP mechanism, and it has to actually stop future messages — not route to a queue someone processes weekly. Most practice texting platforms handle STOP/START keyword processing automatically; confirm yours does before sending anything, since manual processing is one of the more common ways a practice ends up out of compliance without intending to.",
      },
      { type: "h2", text: "Where HIPAA overlaps" },
      {
        type: "p",
        text: "Same principle as email: TCPA governs whether you can text at all and under what consent; HIPAA governs whether the content discloses PHI. A text referencing a specific diagnosis or treatment detail needs a HIPAA-compliant secure messaging channel, not standard SMS, regardless of whether TCPA consent was obtained. Standard, unencrypted SMS is generally fine for appointment logistics and general marketing — not for anything clinical.",
      },
    ],
    faqs: [
      {
        q: "Is this page legal advice?",
        a: "No. This is a plain-language summary of TCPA and HIPAA considerations for medical-practice text marketing, not a substitute for review by a healthcare attorney before launching or expanding a texting program.",
      },
      {
        q: "Can we text a patient who gave us their phone number for scheduling?",
        a: "Not for marketing purposes without separate, specific written consent. A phone number given for appointment scheduling covers transactional messages related to that purpose — it does not, by itself, authorize promotional texts under the TCPA's written-consent requirement.",
      },
      {
        q: "What's the penalty for a TCPA violation?",
        a: "TCPA violations carry statutory damages that can run from roughly $500 to $1,500 per message for willful violations, and claims are frequently brought as class actions given how many messages a single non-compliant campaign can involve. This is why written consent and a working opt-out matter more here than in most other marketing channels.",
      },
      {
        q: "Does Primara handle TCPA consent for review-request texts?",
        a: "Primara's review-request texts are sent only to patients who've already been seen and are request-only by design — name and phone, no promotional content, no sentiment pre-screening — built to the stricter standard this guide describes rather than relying on a looser transactional exemption.",
      },
      {
        q: "Can a patient re-consent after opting out?",
        a: "Yes, but it requires a fresh, affirmative opt-in — you cannot simply resume texting someone who replied STOP based on old consent. Most platforms require them to text START or complete a new consent action before marketing messages can resume.",
      },
    ],
    citations: [
      { publisher: "Federal Communications Commission", label: "Telephone Consumer Protection Act (TCPA) rules", href: "https://www.fcc.gov/general/telephone-consumer-protection-act-1991" },
      { publisher: "Federal Trade Commission", label: "Telemarketing Sales Rule", href: "https://www.ftc.gov/business-guidance/resources/telemarketing-sales-rule" },
    ],
    links: [
      {
        href: "/guides/email-marketing-compliance-for-a-medical-practice",
        label: "Email Marketing Compliance for a Medical Practice",
        description: "The equivalent rules for email — CAN-SPAM's opt-out standard, a lower bar than TCPA's written consent.",
      },
      {
        href: "/guides/hipaa-safe-tracking-for-a-medical-website",
        label: "HIPAA-Safe Tracking for a Medical Website",
        description: "The PHI question applied to website tracking rather than text content.",
      },
      {
        href: "/guides/healthcare-ad-compliance-checklist",
        label: "Healthcare Ad Compliance Checklist",
        description: "The broader compliance checklist this texting-specific guide sits inside.",
      },
      {
        href: "/services/patient-acquisition-ads",
        label: "Patient Acquisition Ads",
        description: "Where compliant texting fits into a broader patient-acquisition program.",
      },
      {
        href: "/services/digital-marketing-for-independent-medical-practices",
        label: "Digital Marketing for Independent Medical Practices",
        description: "The full-service program this compliance work supports.",
      },
    ],
  },

  // ── 513 ───────────────────────────────────────────────────────────────
  {
    slug: "should-a-medical-practice-blog-and-how-often",
    keyword: "should a medical practice blog and how often",
    category: "How-to",
    title: "Should a Medical Practice Blog, and How Often?",
    metaTitle: "Should a Medical Practice Blog? How Often, and Why",
    metaDescription:
      "When blogging actually helps a medical practice's SEO, when it's wasted effort, and a realistic publishing cadence. Call (561) 291-2681.",
    answer:
      "A medical practice should blog if it has real patient questions worth answering in depth and the capacity to publish consistently — one genuinely useful post every 2-4 weeks beats four rushed posts dumped in one month and nothing after. A practice with thin service pages should fix those first; a blog on top of weak core pages rarely moves the needle on its own.",
    author: "Liam Costello",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 6,
    sections: [
      { type: "h2", text: "What a blog is actually for, for a local practice" },
      {
        type: "p",
        text: "A service page (\"Family Medicine in Lakeland\") targets someone ready to book. A blog post (\"What to expect at your first annual physical\") targets someone a step earlier — researching, not yet ready to call, but typing a specific question into Google. Both matter, but they're different jobs, and conflating them is the most common mistake we see: a practice tries to make its service pages do blog-style educational work, which dilutes the page's actual job of converting a ready patient.",
      },
      { type: "h2", text: "When blogging is worth the effort" },
      {
        type: "ul",
        items: [
          "Your core service and location pages are already solid (700+ words, answering real patient questions, no stub pages) — a blog adds to a strong foundation, it doesn't substitute for one.",
          "You have real, specific patient questions worth a full answer — things your front desk actually gets asked, not generic topics copied from a content calendar template.",
          "Someone on your team (or a writer who works closely with your providers) can commit to a realistic, sustained cadence — inconsistent blogging produces weaker results than a smaller, steady output.",
          "You're targeting a condition or service area with real search volume behind the question, not just a topic you personally find interesting.",
        ],
      },
      { type: "h2", text: "When it's not the right next move" },
      {
        type: "p",
        text: "If your service pages themselves are thin or missing — a single paragraph where a real page should be — that's the higher-leverage fix. Those pages target people actively searching for your exact service, with buying intent a blog post about general wellness tips simply doesn't carry. We've measured this directly: a practice's weakest, most templated pages are consistently its lowest-ranking ones, and no amount of blog content elsewhere compensates for that gap. Fix the foundation first. Publishing is only half the plan; the other half is covered in [how often to update old content on a medical practice website](/guides/how-often-to-update-old-content-on-a-medical-practice-website).",
      },
      { type: "h2", text: "A realistic cadence" },
      {
        type: "table",
        headers: ["Cadence", "Who it fits"],
        rows: [
          ["1 post every 2-4 weeks", "Most independent practices — sustainable with a provider contributing topics and a writer doing the actual drafting."],
          ["1 post every 1-2 weeks", "Larger multi-provider practices with more topics and more hands available to review drafts for accuracy."],
          ["Quarterly, substantial pieces", "A smaller solo practice where consistency matters more than volume — four genuinely strong posts a year outperform twelve rushed ones."],
        ],
      },
      {
        type: "p",
        text: "Google's own guidance on helpful content doesn't reward frequency for its own sake — it rewards content that demonstrates real expertise and answers the question completely. A slower, accurate cadence a practice can actually sustain beats an aggressive one that collapses after two months, which is the single most common blogging failure pattern we see.",
      },
      { type: "h2", text: "What makes a medical blog post actually rank" },
      {
        type: "p",
        text: "The same bar as any other page on the site: a direct answer in the first few sentences, real specificity (your actual hours, your actual process, not generic advice available on a hundred other sites), and a named, credentialed author when the topic is clinical. A post written to \"hit a word count\" without a real question behind it reads as filler to both readers and Google's helpful-content systems, and tends to sit unindexed rather than rank.",
      },
    ],
    faqs: [
      {
        q: "Does blogging actually help SEO for a medical practice?",
        a: "It can, specifically for research-stage search terms your core service pages aren't built to target — but only when it's consistent and genuinely answers real patient questions. A sporadic blog on top of thin service pages produces little measurable effect either way.",
      },
      {
        q: "How long should a medical practice blog post be?",
        a: "Long enough to fully answer the question and nothing more — most useful medical blog posts land between 700 and 1,200 words. Padding a post past that to hit a target word count tends to hurt more than help, both for the reader and for how Google's helpful-content systems evaluate it.",
      },
      {
        q: "Who should write a medical practice's blog posts?",
        a: "A writer who works directly with your providers, pulling the actual clinical accuracy and specifics from them, generally produces better results than either a provider writing alone (time-constrained, often skips the SEO structure) or a generic freelance writer alone (misses the clinical accuracy).",
      },
      {
        q: "Should we blog before or after fixing our service pages?",
        a: "After, or at minimum alongside. Service pages target patients actively ready to book and carry the highest conversion intent on the site — if those are thin, that's the higher-leverage fix, and a blog built on top of weak core pages rarely moves new-patient numbers on its own.",
      },
      {
        q: "Is it bad to stop blogging after starting?",
        a: "It's not catastrophic, but an abandoned blog with a visible last-post date from a year ago can read as a red flag to a prospective patient researching your practice, and the inconsistent cadence limits how much ranking benefit the posts build in the first place. Better to commit to a slower, sustainable schedule than start fast and stop.",
      },
    ],
    citations: [
      { publisher: "Google Search Central", label: "Creating helpful, reliable, people-first content", href: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content" },
    ],
    links: [
      {
        href: "/guides/medical-practice-content-calendar-checklist",
        label: "Medical Practice Content Calendar Checklist",
        description: "Once the decision to blog is made, this is the cadence and planning checklist to run it on.",
      },
      {
        href: "/guides/how-to-write-a-medical-service-page-that-ranks",
        label: "How to Write a Medical Service Page That Ranks",
        description: "The higher-leverage fix for most practices, before or alongside starting a blog.",
      },
      {
        href: "/guides/how-to-measure-roi-on-medical-practice-marketing",
        label: "How to Measure ROI on Medical Practice Marketing",
        description: "How to tell if the blog is actually contributing, rather than guessing.",
      },
      {
        href: "/services/seo",
        label: "SEO for Medical Practices",
        description: "The broader content and ranking program a blog sits inside.",
      },
      {
        href: "/services/local-seo-for-medical-practices",
        label: "Local SEO for Medical Practices",
        description: "What usually matters more for a local practice than blog volume alone.",
      },
    ],
  },

  // ── 514 ───────────────────────────────────────────────────────────────
  {
    slug: "keyword-research-for-a-medical-practice-seo-campaign",
    keyword: "keyword research for a medical practice SEO campaign",
    category: "How-to",
    title: "Keyword Research for a Medical Practice SEO Campaign",
    metaTitle: "Keyword Research for a Medical Practice SEO Campaign",
    metaDescription:
      "How to find the search terms that actually bring new patients — tools, the service-times-city method, and what to ignore. Call (561) 291-2681.",
    answer:
      "Keyword research for a medical practice means listing every service you offer, crossing each one against every city or neighborhood you actually serve, and checking real search volume and competition for each combination with a tool like Google Keyword Planner — then prioritizing phrases with clear booking intent (\"therapist in Lakeland\") over purely informational ones (\"what is therapy\").",
    author: "Gio LaRoche",
    publishDate: "2026-10-01T09:00:00Z",
    dateModified: "2026-10-01",
    readMinutes: 7,
    sections: [
      { type: "h2", text: "Start with the service × city grid, not a brainstorm" },
      {
        type: "p",
        text: "The single most reliable keyword research method for a local medical practice isn't creative brainstorming — it's mechanical. List every service you offer in plain patient language (not clinical jargon; \"stomach pain\" gets searched far more than \"abdominal discomfort\"), then list every city, town, and neighborhood you genuinely serve. Cross every service against every location. A practice offering 5 services across 4 nearby cities already has 20 real keyword targets before any tool is involved.",
      },
      { type: "h2", text: "Then check real volume and competition" },
      {
        type: "p",
        text: "Google Keyword Planner (free with a Google Ads account, no ad spend required to use the research tool) gives you an actual search-volume range and a competition rating for each phrase. This step matters because intuition is often wrong — a city you assume has a lot of search volume sometimes has very little, and a neighborhood you'd never have guessed can carry a surprising amount. Don't build pages on assumption alone.",
      },
      { type: "h2", text: "Sort by intent, not just volume" },
      {
        type: "table",
        headers: ["Intent type", "Example and priority"],
        rows: [
          ["Transactional (ready to book)", "\"family doctor accepting new patients lakeland\" — highest priority, build a dedicated page"],
          ["Local-commercial (comparing options)", "\"best family doctor in lakeland\" — high priority, same page can target this alongside the above"],
          ["Informational (researching)", "\"what does a family doctor do\" — lower priority, good blog-post material"],
          ["Navigational (already know you)", "\"[your practice name] lakeland\" — handled by your Google Business Profile, not a new page"],
        ],
      },
      {
        type: "p",
        text: "A common mistake is chasing the highest-volume keyword regardless of intent. \"Doctor\" alone might show enormous volume, but it's so broad it converts almost nobody — you're competing with hospital systems, WebMD, and every practice in the country for a searcher who hasn't even decided what kind of doctor they need yet. A lower-volume, specific phrase with clear booking intent is worth more than a high-volume vague one.",
      },
      { type: "h2", text: "Where to find phrases a tool alone won't surface" },
      {
        type: "ul",
        items: [
          "Google's \"People also ask\" and autocomplete on your actual target searches — real phrasing patients use, in their own words.",
          "Your own front desk and intake staff — the actual questions patients ask on the phone before booking are often better keyword material than any tool.",
          "Google Search Console, once you have any traffic — the Performance report shows exactly what people typed to find pages you already have, including phrases you never explicitly targeted.",
          "Your Google Business Profile's existing search queries (visible in Business Profile insights) — a direct signal of what's already bringing people to your listing.",
        ],
      },
      { type: "h2", text: "What to do with the finished list" },
      {
        type: "p",
        text: "Group it by intent, not alphabetically. Transactional service × city phrases become dedicated pages. Related informational phrases that don't deserve their own page become FAQ sections or blog posts. Phrases with real volume but no clear match to anything you currently offer are worth a second look — sometimes they reveal a service patients want that isn't on the site yet at all, which is as valuable a finding as the keyword itself. Pages only rank if Google can crawl and index them; [XML sitemaps and robots.txt for a practice website](/guides/xml-sitemaps-and-robots-txt-for-a-medical-practice-website) covers the basics.",
      },
    ],
    faqs: [
      {
        q: "What's the best free tool for medical practice keyword research?",
        a: "Google Keyword Planner is the most reliable starting point — it's free with a Google Ads account (no ad spend required to use the planning tool) and pulls directly from Google's own search data rather than a third party's estimate.",
      },
      {
        q: "How many keywords should a medical practice target?",
        a: "There's no fixed number — it depends on how many services and locations you genuinely serve. A focused solo practice might have 15-20 real targets; a multi-location, multi-specialty group can have hundreds. The service-times-city grid method scales naturally either way.",
      },
      {
        q: "Should I target keywords with low search volume?",
        a: "Often yes, if the intent is strong. A specific, low-volume phrase like \"direct primary care physician west palm beach\" converts at a far higher rate than a broad, high-volume term like \"doctor,\" because the searcher already knows exactly what they want.",
      },
      {
        q: "How often should keyword research be redone?",
        a: "Revisit it roughly every 6-12 months, or any time you add a service or expand to a new location — search behavior and your own offering both shift, and a keyword list built two years ago is often missing newer phrasing patients have started using.",
      },
      {
        q: "Does keyword research matter for voice and AI search too?",
        a: "Yes, and increasingly — voice and AI search tend to favor longer, full-question phrasing (\"who's the best therapist near me taking new clients\") over the shorter fragments typed into a search box. Including a few full-question variants in your research alongside the shorter commercial phrases covers both.",
      },
    ],
    citations: [
      { publisher: "Google Ads Help", label: "About Keyword Planner", href: "https://support.google.com/google-ads/answer/2453986" },
      { publisher: "Google Search Central", label: "SEO Starter Guide", href: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide" },
    ],
    links: [
      {
        href: "/guides/how-to-run-a-local-seo-audit-for-a-medical-practice",
        label: "How to Run a Local SEO Audit for a Medical Practice",
        description: "Where keyword research fits in the full audit process.",
      },
      {
        href: "/guides/how-much-does-medical-seo-cost",
        label: "How Much Does Medical SEO Cost?",
        description: "What it typically costs to turn a finished keyword list into built, ranking pages.",
      },
      {
        href: "/guides/medical-practice-content-calendar-checklist",
        label: "Medical Practice Content Calendar Checklist",
        description: "Where the informational-intent half of a keyword list ends up — the blog plan.",
      },
      {
        href: "/services/seo",
        label: "SEO for Medical Practices",
        description: "The full program keyword research is the starting input for.",
      },
      {
        href: "/locations/medical-seo-florida",
        label: "Medical SEO in Florida",
        description: "What the service-times-city method looks like applied statewide.",
      },
      {
        href: "/guides/backlinks-for-a-medical-practice-safe-vs-penalized",
        label: "Backlinks for a Medical Practice: What's Safe and What Gets Penalized",
        description: "The off-page half of the SEO work keyword research points toward.",
      },
    ],
  },
];
