// ── Guides batch 9 — 2026-10-05 ────────────────────────────────────────────
// 5 guide/AEO rows from the Command Center queue (ids 658-662), built by the
// daily page factory. Built to ~/Primara-Clients/PAGE-STANDARD.md: answer box,
// 5 FAQs at 40-80 words marked up FAQPage, schema graph generated by
// app/guides/[slug]/page.tsx, outbound citations (Google / W3C / DOJ only).
// Inbound editorial links are planted as inline [text](/guides/slug) links in
// the body prose of existing guides (renderInline).

import type { Guide } from "@/lib/guides";

export const guidesPartTwelve: Guide[] = [
  {
    slug: "how-to-read-google-search-console-for-a-medical-practice-website",
    keyword: "how to read Google Search Console for a medical practice website",
    category: "How-to",
    title: "How to Read Google Search Console for a Medical Practice Website",
    metaTitle: "Reading Google Search Console for a Medical Practice",
    metaDescription: "The Search Console reports a medical practice should check, what each number means, and what to act on. Call (561) 291-2681.",
    answer: "Google Search Console is a free tool that shows how your website performs in Google Search. For a practice, check three things: the Performance report for clicks and impressions by page and query, the Pages report for what is indexed, and the Sitemaps report. Review monthly, and act on drops that last several weeks.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "What Search Console is, and what it is not"
      },
      {
        "type": "p",
        "text": "Search Console is a free service from Google that reports how your site appears in Google Search. It tells you which searches showed your pages, how often people clicked, whether Google can crawl and index each page, and whether anything is wrong, such as a security issue or a manual action. It is not a visitor tracker like Google Analytics, and it does not tell you who the patients are. It reports search behavior in aggregate. You prove ownership of the site once, usually through DNS or a file on your server, and the data starts accumulating from then. Pages that Search Console reports as not found are covered in [how to find and fix broken links and 404 errors](/guides/how-to-find-and-fix-broken-links-and-404-errors-on-a-medical-practice-website), and visitor behavior is covered in our [monthly Google Analytics 4 routine](/guides/how-to-read-google-analytics-4-reports-each-month-for-a-medical-practice)."
      },
      {
        "type": "h2",
        "text": "The Performance report: four numbers"
      },
      {
        "type": "ul",
        "items": [
          "Clicks: how many times someone clicked from Google to your site.",
          "Impressions: how many times a link to your site was shown in results, whether or not anyone clicked.",
          "Click-through rate: clicks divided by impressions.",
          "Average position: your typical ranking for the searches that showed your page. It is an average, so a page can rank first for one search and fortieth for another."
        ]
      },
      {
        "type": "p",
        "text": "Use the Pages tab to see which URLs earn clicks and the Queries tab to see the searches. Set the date range to compare the last three months to the prior three months, and choose a full-month view before drawing conclusions, because a single week is noise. Impressions rising with clicks flat means you are being seen more but not chosen, which usually points to titles and descriptions. Our guide on [meta descriptions that get clicks](/guides/meta-descriptions-that-get-clicks-for-a-medical-practice) covers that fix."
      },
      {
        "type": "h2",
        "text": "The Pages report: what is and is not indexed"
      },
      {
        "type": "p",
        "text": "The Pages report, under Indexing, lists URLs Google knows about and whether each is indexed. Not every URL belongs in the index, since login pages and thank-you pages are often excluded on purpose. Focus on the pages you want patients to find: service pages, location pages, and provider pages. If one of those appears under a status such as discovered but not indexed, or crawled but not indexed, treat it as a content or linking problem to investigate. The URL Inspection tool lets you test a single page and see what Google last crawled. Average position is one of several rank sources, and our guide on [tracking local search rankings for a practice](/guides/how-to-track-local-search-rankings-for-a-medical-practice) compares them. When the report shows duplicates, the URL Inspection tool can show which canonical Google chose; see [canonical tags and duplicate content on a medical practice website](/guides/canonical-tags-and-duplicate-content-on-a-medical-practice-website) for how to respond."
      },
      {
        "type": "h2",
        "text": "A monthly routine that takes twenty minutes"
      },
      {
        "type": "ol",
        "items": [
          "Open the Performance report and note total clicks and impressions for the month against the previous one.",
          "Sort pages by clicks and look for any service page that fell sharply.",
          "Open the Pages report and compare the indexed count with the number of pages in your sitemap.",
          "Open the Sitemaps report and confirm the last read date is recent and the status is successful.",
          "Check Security and manual actions, and the Core Web Vitals report if it appears, which our [Core Web Vitals checklist](/guides/core-web-vitals-checklist-for-a-medical-practice-website) explains."
        ]
      },
      {
        "type": "p",
        "text": "Keep private information out of your reasoning. Search Console data is aggregate and anonymous, and nothing in it should be tied to an individual patient. Note your findings in a simple log so you can compare month to month. If a broad drop appears across many pages, check whether it lines up with a [Google core update](/guides/google-core-updates-how-to-tell-if-your-practice-site-was-hit) before changing anything. The Business Profile has its own performance report for the listing; our guide on [reading Google Business Profile performance reports](/guides/how-to-read-google-business-profile-performance-reports-each-month) covers it the same way."
      }
    ],
    faqs: [
      {
        "q": "Is Google Search Console free?",
        "a": "Yes. Search Console is a free tool from Google. You verify ownership of your site, and Google then shows search performance, indexing status, and issue reports. You do not pay for the data, and it does not require a Google Ads account."
      },
      {
        "q": "What is the difference between Search Console and Google Analytics?",
        "a": "Search Console reports what happens in Google Search before a click, such as impressions, queries, and indexing. Analytics reports what visitors do after they arrive, such as pages viewed and form submissions. Practices benefit from using both together. Review it monthly and note what changed."
      },
      {
        "q": "Why do my clicks and impressions not match my Analytics sessions?",
        "a": "They measure different things. Search Console counts clicks from Google Search only, while Analytics counts all visits and applies its own rules for sessions. Small differences are normal, so compare trends in each tool rather than expecting identical totals. Review it monthly and note what changed."
      },
      {
        "q": "How often should a practice check Search Console?",
        "a": "Monthly is enough for most practices, with a quick look after any website change, launch, or domain move. Check sooner if you receive a Search Console email about a new issue, since Google sends alerts for serious problems. Review it monthly and note what changed."
      },
      {
        "q": "What does 'discovered, currently not indexed' mean?",
        "a": "It means Google knows the URL exists but has not crawled and indexed it yet. It can be temporary on new pages. If it persists on important pages, improve their content, add internal links from relevant pages, and make sure they are in your sitemap."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Console Help",
        "label": "Performance report (Search)",
        "href": "https://support.google.com/webmasters/answer/7576553"
      },
      {
        "publisher": "Google Search Console Help",
        "label": "Page indexing report",
        "href": "https://support.google.com/webmasters/answer/7440203"
      }
    ],
    links: [
      {
        "href": "/guides/how-to-run-a-local-seo-audit-for-a-medical-practice",
        "label": "How to Run a Local SEO Audit",
        "description": "Use Search Console data in a full audit."
      },
      {
        "href": "/guides/how-to-set-up-google-analytics-4-for-a-medical-practice",
        "label": "How to Set Up GA4",
        "description": "The other half of the measurement setup."
      },
      {
        "href": "/guides/how-to-measure-roi-on-medical-practice-marketing",
        "label": "How to Measure ROI",
        "description": "Tie search data to booked patients."
      },
      {
        "href": "/services/seo",
        "label": "Medical SEO Services",
        "description": "Monthly reporting and monitoring."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "online-appointment-scheduling-on-a-medical-practice-website-and-seo",
    keyword: "how to add online appointment scheduling to a medical practice website without hurting SEO",
    category: "How-to",
    title: "Online Appointment Scheduling on a Medical Practice Website, Without Hurting SEO",
    metaTitle: "Online Scheduling on a Practice Site and SEO",
    metaDescription: "How to add online booking to a medical practice website without losing SEO, tracking, or privacy. Call (561) 291-2681.",
    answer: "Add a clear booking button on every service page that links to your scheduler, and keep the page's own text, headings, and phone number in your site's HTML. An embedded scheduler is usually not read as your page's content, so it cannot carry your SEO. Track clicks, and confirm the vendor signs a Business Associate Agreement.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "Why scheduling tools can quietly hurt a page"
      },
      {
        "type": "p",
        "text": "Many online scheduling tools install as an embedded frame or a script that loads a form from the vendor's server. To a visitor it looks like part of your page. To a search engine, the content inside a frame generally belongs to the other source, not to your page. If your 'Book an appointment' page is only a heading and a widget, there is almost no text for Google to read, and the page has nothing to rank for. The scheduler solves a patient's problem but does nothing for search."
      },
      {
        "type": "h2",
        "text": "Build the page around the widget, not inside it"
      },
      {
        "type": "ul",
        "items": [
          "Keep real text on the page: the service, who it is for, what to expect, location, hours, and accepted insurance, written in your own HTML.",
          "Put the booking button above the fold and repeat it near the end of every service page, linking to your scheduler or opening it in a new view.",
          "Keep your phone number as a tappable link beside the button. Many patients still prefer to call, and calls need to remain a visible option.",
          "Give the scheduling page a real title and heading, such as 'Book an Appointment at [Practice Name] in [City],' and link to it from your main navigation using normal crawlable links.",
          "Offer a plain fallback link if the widget fails to load, so the page never shows a blank space."
        ]
      },
      {
        "type": "p",
        "text": "Google's guidance on links asks for real anchor elements with a destination, so a button that only works through a script can fail to pass signals or be followed. Our [guide to writing a medical service page](/guides/how-to-write-a-medical-service-page-that-ranks) shows how to structure the surrounding copy."
      },
      {
        "type": "h2",
        "text": "Track bookings the right way"
      },
      {
        "type": "p",
        "text": "Define a booking as a conversion. If the scheduler is on the vendor's domain, track the button click on your site with a GA4 event, and ask the vendor whether it can send a confirmation back to a thank-you page on your domain, which is a cleaner measure. Set up call tracking beside it, as covered in [tracking phone calls from a medical website](/guides/tracking-phone-calls-from-a-medical-website). Then compare booked appointments by source, rather than clicks alone. Seasonal booking pages for flu shots and school physicals need current dates and a working link; see [seasonal service pages for a medical practice](/guides/seasonal-service-pages-for-a-medical-practice-flu-shots-and-school-physicals)."
      },
      {
        "type": "h2",
        "text": "Privacy comes first"
      },
      {
        "type": "p",
        "text": "A scheduler can collect names, reasons for visit, and insurance details, which may be protected health information. Before you add one, confirm the vendor will sign a Business Associate Agreement and that it is configured to collect only what you need. Do not send form contents, appointment reasons, or identifiers to analytics or advertising tags. Review our guide to [HIPAA-safe tracking for a medical website](/guides/hipaa-safe-tracking-for-a-medical-website), and ask your compliance advisor to approve the setup."
      },
      {
        "type": "p",
        "text": "Finally, add your booking link to your Google Business Profile, where Google supports an appointment link, so patients can book from the map listing directly. See [how to get more patients from your Google Business Profile](/guides/how-to-get-more-patients-from-google-business-profile). Our guide on [adding an appointment or booking link to a Google Business Profile](/guides/how-to-add-an-appointment-or-booking-link-to-a-google-business-profile) walks through where to add it and how to test it on a phone."
      }
    ],
    faqs: [
      {
        "q": "Does an embedded scheduling widget count as my page's content?",
        "a": "Generally not. Content inside an embedded frame typically belongs to the source that serves it, so it will not help your page rank. Keep descriptive text, headings, and contact details in your own HTML around the widget. Confirm the setup with your compliance advisor before launch."
      },
      {
        "q": "Should I link to my scheduler or embed it?",
        "a": "Either can work. Linking to a hosted scheduling page is simpler and avoids loading problems. Embedding keeps visitors on your site. In both cases, put the useful text on your own page and make the booking button easy to find."
      },
      {
        "q": "How do I track online bookings?",
        "a": "Track the booking button click as a GA4 event, and where possible have the scheduler redirect to a thank-you page on your domain after a completed booking. Do not pass appointment details or identifiers into your analytics or ad tags."
      },
      {
        "q": "Do I need a Business Associate Agreement with my scheduling vendor?",
        "a": "If the tool collects or stores information that could be protected health information, yes, you generally need a signed agreement with that vendor. Ask before you sign up, and confirm the answer with your compliance advisor. Confirm the setup with your compliance advisor before launch."
      },
      {
        "q": "Can patients book from my Google Business Profile?",
        "a": "Where Google offers an appointment link field for your category, you can add your booking URL so patients can book from the listing. Availability varies by listing and category, so check what your profile's editor shows. Confirm the setup with your compliance advisor before launch."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Make your links crawlable",
        "href": "https://developers.google.com/search/docs/crawling-indexing/links-crawlable"
      },
      {
        "publisher": "U.S. Department of Health and Human Services",
        "label": "HIPAA Privacy Rule guidance",
        "href": "https://www.hhs.gov/hipaa/for-professionals/privacy/index.html"
      }
    ],
    links: [
      {
        "href": "/guides/tracking-phone-calls-from-a-medical-website",
        "label": "Tracking Phone Calls from a Medical Website",
        "description": "Keep call tracking beside the booking button."
      },
      {
        "href": "/guides/hipaa-safe-tracking-for-a-medical-website",
        "label": "HIPAA-Safe Tracking",
        "description": "Keep appointment details out of analytics."
      },
      {
        "href": "/guides/how-to-write-a-medical-service-page-that-ranks",
        "label": "How to Write a Medical Service Page",
        "description": "The text that surrounds the booking button."
      },
      {
        "href": "/services/medical-practice-website-design",
        "label": "Medical Practice Website Design",
        "description": "Booking built into the page template."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "what-to-put-on-a-medical-practice-about-page",
    keyword: "what to put on a medical practice About page",
    category: "Checklist",
    title: "What to Put on a Medical Practice About Page",
    metaTitle: "What to Put on a Medical Practice About Page",
    metaDescription: "A checklist for a medical practice About page that builds patient trust and gives Google clear facts. Call (561) 291-2681.",
    answer: "A practice About page should state who you are, where you are, who the licensed clinicians are, what you treat, and how to reach you, in plain language. Add each clinician's real credentials and a short, honest story of the practice. Leave out outcome promises, invented awards, and anything you cannot document.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "What the page is for"
      },
      {
        "type": "p",
        "text": "The About page is often one of the most visited pages on a practice website, because a new patient wants to know who they are trusting before they book. It is also a primary source for search engines and AI assistants that describe your practice. A thin page that says 'we are dedicated to compassionate care' gives readers and machines nothing to use. A page with concrete, checkable facts does both jobs."
      },
      {
        "type": "h2",
        "text": "What to include, in order"
      },
      {
        "type": "ol",
        "items": [
          "A plain statement in the first two sentences: the practice's full name, what kind of care it provides, and the city it serves.",
          "Your address, phone number, and hours, matching your Google Business Profile exactly.",
          "Each clinician by name, with their credentials exactly as licensed, such as MD, DO, NP, or PA-C, and a link to their bio page.",
          "The services you provide, using the same names as on your service pages and Google profile.",
          "A short, true account of how the practice started, why it serves this community, and what a first visit is like.",
          "Insurance accepted or payment options, if you can keep that accurate over time.",
          "Affiliations and memberships you can document, such as a hospital privileges or a professional society, with a link to the source where possible."
        ]
      },
      {
        "type": "h2",
        "text": "What to leave out"
      },
      {
        "type": "ul",
        "items": [
          "Claims about results, cure rates, or being the best. Medical advertising rules and Google's policies both restrict unsupported claims.",
          "Credentials, awards, or rankings you cannot prove. A fabricated credential is a license problem, not a style problem.",
          "Patient names, photos, stories, or testimonials without proper written authorization. See our [patient testimonial compliance checklist](/guides/patient-testimonial-compliance-checklist).",
          "Vague filler. If a sentence could appear on any practice's site, it adds nothing."
        ]
      },
      {
        "type": "h2",
        "text": "Make it readable by machines too"
      },
      {
        "type": "p",
        "text": "Add Organization or MedicalBusiness structured data to the page, with your name, address, phone, and links to your official profiles, as described in our guide to [schema markup for a medical practice website](/guides/schema-markup-for-a-medical-practice-website-explained). Link each clinician's name to a full bio, and build those pages using [how to write a doctor bio page that ranks](/guides/how-to-write-a-doctor-bio-page-that-ranks). Add a clear next step, a booking link and a tappable phone number, because trust is what gets a patient to act. The same clean outline applies here, with one H1 and short H2 sections as laid out in our guide to [heading structure from H1 to H3](/guides/heading-structure-h1-to-h3-for-a-medical-practice-web-page), so visitors and machines can both scan the page."
      },
      {
        "type": "p",
        "text": "Finally, keep the page current. A retired provider or old address on the About page misleads patients, so include it in your quarterly review, as covered in [how often to update old content](/guides/how-often-to-update-old-content-on-a-medical-practice-website)."
      },
      {
        "type": "p",
        "text": "One practical test: read the page as a new patient who knows nothing about you. Can you tell, in ten seconds, what kind of care is offered, where, by whom, and how to book? If any of those answers takes scrolling or guessing, rewrite the top of the page. Ask a front-desk team member to read it too, since they hear the questions patients actually ask and will spot any detail that no longer matches the office. Moving a provider between offices touches every listing, and our guide on [what to update when a provider joins or leaves](/guides/what-to-update-when-a-provider-joins-or-leaves-a-medical-practice) lists them. Reading the page aloud is a good plain-language check, and our guide on [plain language and reading level](/guides/plain-language-and-reading-level-for-patient-facing-web-content) adds a few more ways to test whether a patient can follow it."
      }
    ],
    faqs: [
      {
        "q": "How long should a medical practice About page be?",
        "a": "Long enough to state the facts above, usually a few hundred words plus provider links. Length is not the goal. Every sentence should tell a patient something specific, such as who you are, where you are, or what a first visit involves."
      },
      {
        "q": "Should every clinician be listed on the About page?",
        "a": "Yes, list each licensed clinician with their name and credentials, and link to a full bio. Make sure the credentials match their license exactly. Remove providers promptly when they leave, since outdated names mislead patients and confuse search engines. Review the page every quarter to keep it accurate."
      },
      {
        "q": "Can I include patient reviews on the About page?",
        "a": "You can show genuine reviews if you follow platform rules and advertising regulations, and never select or edit them to mislead. Do not offer incentives for positive reviews, and do not include patient information without proper written authorization. Review the page every quarter to keep it accurate."
      },
      {
        "q": "Does the About page help SEO?",
        "a": "It helps indirectly. It gives Google and AI assistants consistent facts about your practice and its clinicians, which supports recognition of your business and the expertise signals described in our E-E-A-T guide. It is not a ranking shortcut. Review the page every quarter to keep it accurate."
      },
      {
        "q": "Should the About page include my story?",
        "a": "A short, honest story helps patients connect, but keep it factual and brief. Say why the practice exists and who it serves. Skip anything you cannot verify, and keep clinical claims out of it entirely. Review the page every quarter to keep it accurate."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Creating helpful, reliable, people-first content",
        "href": "https://developers.google.com/search/docs/fundamentals/creating-helpful-content"
      },
      {
        "publisher": "Google Search Central",
        "label": "Organization structured data",
        "href": "https://developers.google.com/search/docs/appearance/structured-data/organization"
      }
    ],
    links: [
      {
        "href": "/guides/how-to-write-a-doctor-bio-page-that-ranks",
        "label": "How to Write a Doctor Bio Page",
        "description": "The clinician pages the About page links to."
      },
      {
        "href": "/guides/what-is-eeat-and-why-it-matters-for-medical-practices",
        "label": "What Is E-E-A-T",
        "description": "The trust signals the page should carry."
      },
      {
        "href": "/guides/what-to-put-on-a-medical-practice-contact-page",
        "label": "What to Put on a Contact Page",
        "description": "The companion page for reaching you."
      },
      {
        "href": "/services/medical-practice-website-design",
        "label": "Medical Practice Website Design",
        "description": "A site built around trust pages."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-lakeland",
        "label": "Medical SEO in Lakeland",
        "description": "SEO applied to a second real market."
      }
    ],
  },
  {
    slug: "xml-sitemaps-and-robots-txt-for-a-medical-practice-website",
    keyword: "XML sitemaps and robots.txt for a medical practice website",
    category: "Checklist",
    title: "XML Sitemaps and robots.txt for a Medical Practice Website",
    metaTitle: "XML Sitemap and robots.txt for a Practice Website",
    metaDescription: "What an XML sitemap and robots.txt do for a medical practice website, the common mistakes, and a quick check. Call (561) 291-2681.",
    answer: "An XML sitemap lists the pages you want Google to find, and robots.txt tells crawlers which areas not to crawl. Neither is a security tool. Your sitemap should list only live, indexable pages, and robots.txt must never block pages you want in search. To keep a page out of results, use a noindex tag instead.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "Two files, two different jobs"
      },
      {
        "type": "p",
        "text": "An XML sitemap is a file, usually at yoursite.com/sitemap.xml, that lists the URLs you want search engines to know about, optionally with the date each last changed. A robots.txt file sits at the root of your domain and gives crawlers instructions about which paths they should not request. One invites, the other asks crawlers to stay away. They work together, but they do not do the same thing, and mixing them up is behind many indexing problems on small practice sites. AI crawlers read the same file, and our guide on [allowing or blocking AI crawlers](/guides/should-a-medical-practice-allow-or-block-ai-crawlers) explains what to allow and what to block."
      },
      {
        "type": "h2",
        "text": "What a good sitemap contains"
      },
      {
        "type": "ul",
        "items": [
          "Only pages that return a normal, successful response and that you want indexed: service pages, location pages, provider bios, and guides.",
          "No redirected URLs, broken pages, thank-you pages, login pages, or duplicate versions of the same page.",
          "Accurate last-modified dates, set only when the page content truly changed. A sitemap that claims everything changed today teaches Google to ignore the date.",
          "Full, canonical URLs on the same domain and protocol, such as your https version.",
          "Reference in robots.txt, using a Sitemap line, and submission in Search Console."
        ]
      },
      {
        "type": "p",
        "text": "Most website platforms generate a sitemap for you, so the job is checking it. Open it in a browser, sample twenty URLs, and confirm they load. If you read [how to read Google Search Console](/guides/how-to-read-google-search-console-for-a-medical-practice-website), the Sitemaps report will show when Google last read yours. Also confirm that every listed address is the preferred version, with a matching canonical tag, as explained in [canonical tags and duplicate content on a medical practice website](/guides/canonical-tags-and-duplicate-content-on-a-medical-practice-website)."
      },
      {
        "type": "h2",
        "text": "What robots.txt can and cannot do"
      },
      {
        "type": "p",
        "text": "Robots.txt controls crawling, not indexing. A page you block can still appear in search results if other sites link to it, shown without a description. To keep a page out of search, leave it crawlable and add a noindex directive, or protect it behind a login. Google's documentation says robots.txt is not a way to hide a page. That matters for a practice: never treat robots.txt as protection for anything private, and never place patient information on a public URL at all. A sitemap does not replace links between pages, so read our guide on [internal linking for a practice site](/guides/internal-linking-for-a-medical-practice-website) as well."
      },
      {
        "type": "p",
        "text": "The most damaging mistake is a leftover 'disallow everything' rule from a staging site, which keeps Google away from the whole practice. It happens during launches and redesigns, so it belongs on your [website launch checklist](/guides/medical-website-launch-seo-checklist)."
      },
      {
        "type": "h2",
        "text": "A ten-minute check"
      },
      {
        "type": "ol",
        "items": [
          "Open yoursite.com/robots.txt and read every rule. Confirm there is no blanket disallow and no rule blocking service or location folders.",
          "Open your sitemap and confirm it lists your key pages and no error pages.",
          "In Search Console, confirm the sitemap status is successful and the discovered count roughly matches your real page count.",
          "Inspect one important page with the URL Inspection tool and confirm Google is allowed to crawl it."
        ]
      },
      {
        "type": "p",
        "text": "If your site has several sections, such as a blog or separate location folders, a single sitemap or a sitemap index file both work, as long as every important page appears once. For a small practice, one clean file is easiest to maintain. Whoever updates the website should know who owns these two files, because a plugin update or a platform migration can silently overwrite them, and the fix is much easier when the change is caught within days. If the sitemap lists addresses that now fail, follow [how to find and fix broken links and 404 errors](/guides/how-to-find-and-fix-broken-links-and-404-errors-on-a-medical-practice-website). Submit the sitemap in Search Console once you have verified the site, as described in [how to set up and verify Google Search Console](/guides/how-to-set-up-and-verify-google-search-console-for-a-medical-practice-website)."
      }
    ],
    faqs: [
      {
        "q": "Do I need an XML sitemap if my site is small?",
        "a": "It is not strictly required, since Google can find pages through links, but it is cheap insurance. A sitemap helps Google discover new and updated pages faster, and Search Console reports on it. Most platforms create one automatically, so just verify it."
      },
      {
        "q": "Does robots.txt keep a page out of Google?",
        "a": "No. It asks crawlers not to request the page, but the URL can still be listed if other sites link to it. Use a noindex directive on a crawlable page to keep it out of results, and use a login for anything private."
      },
      {
        "q": "Should thank-you pages be in my sitemap?",
        "a": "Usually not. Thank-you pages exist to confirm an action and do not need to rank. Leave them out of the sitemap and consider noindex. Keep the page accessible so conversion tracking can still fire when a form is submitted. Check the file again after any launch or redesign."
      },
      {
        "q": "How often should my sitemap update?",
        "a": "It should update whenever you add, remove, or significantly change a page, and most platforms do this automatically. Check that last-modified dates reflect real changes, not the date the file was generated. Check the file again after any launch or redesign."
      },
      {
        "q": "What is the most common robots.txt mistake?",
        "a": "Leaving a blanket disallow rule in place from a staging or development site. It tells every crawler to stay away from the whole domain. Check the file after every launch and every redesign. Check the file again after any launch or redesign."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Build and submit a sitemap",
        "href": "https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview"
      },
      {
        "publisher": "Google Search Central",
        "label": "Introduction to robots.txt",
        "href": "https://developers.google.com/search/docs/crawling-indexing/robots/intro"
      },
      {
        "publisher": "Google Search Central",
        "label": "Block search indexing with noindex",
        "href": "https://developers.google.com/search/docs/crawling-indexing/block-indexing"
      }
    ],
    links: [
      {
        "href": "/guides/medical-website-launch-seo-checklist",
        "label": "Medical Website Launch SEO Checklist",
        "description": "Add both files to your pre-launch checks."
      },
      {
        "href": "/guides/how-to-read-google-search-console-for-a-medical-practice-website",
        "label": "How to Read Google Search Console",
        "description": "Confirm Google reads your sitemap."
      },
      {
        "href": "/guides/how-to-migrate-a-medical-practice-website-to-a-new-domain",
        "label": "Migrate a Practice Website to a New Domain",
        "description": "Sitemaps are part of a domain move."
      },
      {
        "href": "/services/seo",
        "label": "Medical SEO Services",
        "description": "Technical SEO that includes crawl and index checks."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-florida",
        "label": "Medical SEO in Florida",
        "description": "The statewide version of the same work."
      }
    ],
  },
  {
    slug: "how-to-build-an-accepted-insurance-page-for-a-medical-practice",
    keyword: "how to build an accepted-insurance page for a medical practice that ranks",
    category: "How-to",
    title: "How to Build an Accepted-Insurance Page for a Medical Practice That Ranks",
    metaTitle: "Accepted Insurance Page for a Medical Practice",
    metaDescription: "How to build an accurate accepted-insurance page for a medical practice that patients trust and Google can read. Call (561) 291-2681.",
    answer: "List the insurance plans your practice currently participates in by exact plan name, grouped by carrier, and add the date you last verified it. Tell patients to confirm their specific plan by calling. Never write 'we accept all insurance.' An accurate, dated page answers a top patient question and avoids sending someone to a visit that is not covered.",
    author: "Gio LaRoche",
    publishDate: "2026-10-05T09:00:00Z",
    dateModified: "2026-10-05",
    readMinutes: 6,
    sections: [
      {
        "type": "h2",
        "text": "Why this page matters"
      },
      {
        "type": "p",
        "text": "'Do you take my insurance' is one of the first questions a new patient asks, and many of them leave a site if they cannot find the answer quickly. A clear insurance page also matches a common search, such as 'family doctor that accepts Aetna in Lakeland.' The risk is in accuracy. Plans change, networks differ by product, and an out-of-date list can cost a patient an unexpected bill and cost you their trust. Patients who pay on their own need a companion page, which we describe in our guide to [publishing self-pay prices](/guides/how-to-publish-self-pay-prices-on-a-medical-practice-website)."
      },
      {
        "type": "h2",
        "text": "What to put on the page"
      },
      {
        "type": "ul",
        "items": [
          "Carrier names with the specific plan products you participate in, since a carrier can offer many plans and you may be in network for only some.",
          "Medicare and Medicaid participation, stated exactly as true for your practice.",
          "Self-pay and payment options for patients without coverage, written plainly.",
          "The date the list was last verified, and a note to confirm coverage with your office and the insurer before the visit.",
          "A phone number and a booking link, tappable on a phone.",
          "A short explanation of what 'in network' and 'out of network' mean, in your own words."
        ]
      },
      {
        "type": "p",
        "text": "Do not describe coverage in a way that implies a guarantee. Say that your office will help verify benefits, and that final coverage depends on the patient's plan."
      },
      {
        "type": "h2",
        "text": "How to structure it so it ranks"
      },
      {
        "type": "p",
        "text": "Give the page a clear title, such as 'Insurance Accepted at [Practice Name] in [City],' and write real text, not only a logo wall. Logos with no text give Google little to read, so put each carrier's name in the HTML. A table with carrier and plan columns is easy for patients and for answer engines to quote. Add a few FAQs about billing and verification, and mark them up as described in our [patient FAQ guide](/guides/how-to-write-patient-faqs-that-answer-ai-search). Link to the page from your main navigation, your contact page, and relevant service pages, and use the same list on your Google Business Profile where it supports insurance details."
      },
      {
        "type": "h2",
        "text": "Keeping it accurate"
      },
      {
        "type": "ol",
        "items": [
          "Assign one person to own the list.",
          "Confirm participation with each payer's provider relations contact at least twice a year, and whenever you sign or end a contract.",
          "Update the page and the verification date together.",
          "Check that your Google profile, directories, and the page all match, using the steps in our [NAP consistency guide](/guides/nap-consistency-what-breaks-it-and-how-to-fix-it)."
        ]
      },
      {
        "type": "p",
        "text": "If you run several locations, give each one its own list, since participation can differ by site. For help structuring multi-site content, see our [multi-location SEO playbook](/guides/multi-location-medical-practice-seo-playbook)."
      },
      {
        "type": "p",
        "text": "A short note on tone helps. Write in plain language and avoid insurance jargon where a simpler word works, since patients are often reading in a stressful moment. If a plan is accepted only for some services, say which. If you are not in network with a plan but patients can still be seen, explain the self-pay or out-of-network process clearly, and never imply that coverage is guaranteed or that billing will be handled in a particular way unless your billing office confirms it. For more on keeping the wording simple, see our guide to [plain language and reading level for patient-facing web content](/guides/plain-language-and-reading-level-for-patient-facing-web-content), which includes a short list of word swaps."
      }
    ],
    faqs: [
      {
        "q": "Should I list every insurance plan I accept?",
        "a": "List the specific plans you participate in, grouped by carrier, as long as you can keep them accurate. If you cannot maintain the details, list carriers and tell patients to call to confirm their exact plan before booking. Confirm the details with each payer before publishing."
      },
      {
        "q": "Is it a problem to say we accept all insurance?",
        "a": "Yes. It is rarely true and can mislead patients into expecting coverage they do not have. Be specific, and tell patients that coverage depends on their individual plan and should be confirmed with your office and the insurer. Confirm the details with each payer before publishing."
      },
      {
        "q": "How often should the insurance page be updated?",
        "a": "Review it at least twice a year and whenever you sign or end a contract with a payer. Add the date of the last verification on the page, so patients can see how current the list is. Confirm the details with each payer before publishing."
      },
      {
        "q": "Can I use carrier logos on the page?",
        "a": "Be careful. Logos are trademarks, and some carriers have rules about their use. Text names are safer and also readable by search engines. If you want logos, check the carrier's brand guidelines first. Confirm the details with each payer before publishing."
      },
      {
        "q": "Does an insurance page help local SEO?",
        "a": "It supports it. It answers a high-intent question, matches searches that include carrier names, and gives consistent details for your listings. Keep it accurate, link to it from service pages, and measure calls and bookings it drives. Confirm the details with each payer before publishing."
      }
    ],
    citations: [
      {
        "publisher": "Google Search Central",
        "label": "Creating helpful, reliable, people-first content",
        "href": "https://developers.google.com/search/docs/fundamentals/creating-helpful-content"
      },
      {
        "publisher": "Google Business Profile Help",
        "label": "Tips to improve your local ranking on Google",
        "href": "https://support.google.com/business/answer/7091"
      }
    ],
    links: [
      {
        "href": "/guides/what-to-put-on-a-medical-practice-contact-page",
        "label": "What to Put on a Contact Page",
        "description": "Where patients go after the insurance page."
      },
      {
        "href": "/guides/how-to-write-a-medical-service-page-that-ranks",
        "label": "How to Write a Medical Service Page",
        "description": "Link insurance details into service pages."
      },
      {
        "href": "/guides/multi-location-medical-practice-seo-playbook",
        "label": "Multi-Location Medical Practice SEO Playbook",
        "description": "One accurate list per location."
      },
      {
        "href": "/services/local-seo-for-medical-practices",
        "label": "Local SEO for Medical Practices",
        "description": "The service that keeps details consistent."
      },
      {
        "href": "/locations/medical-seo-west-palm-beach",
        "label": "Medical SEO in West Palm Beach",
        "description": "SEO applied to one real market."
      },
      {
        "href": "/locations/medical-seo-lakeland",
        "label": "Medical SEO in Lakeland",
        "description": "SEO applied to a second real market."
      }
    ],
  },
];
