// FAQ blocks for hub / comparison / notice pages that had no FAQPage (2026-10-08).
// Rendered by components/FaqSection (visible Q&A + FAQPage JSON-LD from this same array).
// Every answer restates what the page it sits on already says - no new claims, no new numbers.
import type { Faq } from "@/components/FaqSection";

export const specialtiesFaqs: Faq[] = [
  { q: "Which kinds of practices does Primara market?", a: "Primara works with independent primary care practices (family medicine, internal medicine, pediatrics, geriatrics, concierge medicine and direct primary care). Each specialty card on this page links to a page written for that practice type." },
  { q: "Does Primara work with hospital systems or telehealth chains?", a: "No. Primara works exclusively with independent practices, not hospital systems, national telehealth franchises or urgent care chains. The marketing problems differ: an independent practice has to win local Google Maps visibility against those larger brands, and that is the work we are set up to do." },
  { q: "Why does marketing differ by specialty?", a: "Patients search differently for each specialty. Many adults search for an adult doctor or primary care rather than internist, parents rather than children do the searching for pediatrics, and adult children often search on behalf of their parents for geriatric care. A page and a Google Business Profile built for the wrong search habit will not be found." },
  { q: "How do I see what you would do for my specialty?", a: "Pick your practice type above and open its page. It explains the search habits and competitors for that specialty. If you want it applied to your own practice, request the free audit; it takes three to five business days and shows where your practice stands today." },
  { q: "Is my specialty missing from this list?", a: "This page covers primary care specialties. Mental health and counseling practices have their own page, linked from the locations hub. If your practice type is not named anywhere, call (561) 291-2681 and describe it, and we will tell you plainly whether we are a fit." },
];

export const locationsFaqs: Faq[] = [
  { q: "Which Florida markets does Primara cover?", a: "Primara covers South Florida, Tampa Bay, Orlando Metro and Jacksonville. Each market has its own city pages on this hub. More Florida markets are added only after we have done the same depth of homework there, so the list grows slowly and on purpose rather than all at once." },
  { q: "Which practice types are served in each market?", a: "Two specialties: independent primary care practices and independent mental health practices. The city pages below are organized by those two so you can go straight to the market and practice type that matches yours." },
  { q: "What is on a city page?", a: "Each city page describes the local competitive landscape for that vertical: which hospital systems or chains compete with independent practices, what patients in that city actually search, and the review count and review pace that define the local search leaderboard. It is local detail rather than a template with the city name swapped." },
  { q: "Why does Primara limit itself to a few markets?", a: "A search landscape that works in Boca Raton does not transfer to Fort Lauderdale, or to Tampa versus Clearwater. We take on a market only when we can bring real local knowledge, which is why coverage is limited to the four markets listed here today." },
  { q: "How do I get started in my city?", a: "Request the free audit or call (561) 291-2681. The audit looks at your Google Maps position, your Google Business Profile setup and your review count against a named local competitor, and is delivered in three to five business days." },
];

export const resultsFaqs: Faq[] = [
  { q: "Does Primara guarantee a ranking or a number of new patients?", a: "No. Every market is different, and anyone who promises a specific rank position on a specific date is selling a guarantee they cannot deliver. This page shows the milestones we hold ourselves to at 30, 60, 90 and 180 days instead of a promised outcome." },
  { q: "What is finished in the first 30 days?", a: "The foundation: a fully configured Google Business Profile, a 12-month posting calendar, the review request system with tap cards and QR codes, a baseline rank grid for your main keyword, and a first monthly report. The first 30 days are set-up work, so you should not expect ranking movement yet." },
  { q: "When does movement usually show up?", a: "On the page's own timeline, first movement on secondary keywords appears around 60 days, more documented movement at 90 days, and the clearest picture at 180 days. Highly competitive terms in Miami or Fort Lauderdale take additional months. These are patterns, not promises." },
  { q: "How are results measured?", a: "With Local Falcon grid rankings, Google Business Profile Insights impression and call counts, review velocity, and Google Search Console organic traffic. Each monthly report compares against your starting baseline, and the 90-day analysis adds a side-by-side against a named local competitor." },
  { q: "Why does review pace matter more than total reviews?", a: "The page states that practices adding two to four new reviews a month consistently tend to outrank practices with more total reviews but stagnant acquisition. That is why the review request system is installed in the first 30 days rather than later." },
];

export const therapistSeoFaqs: Faq[] = [
  { q: "Why is SEO for therapists different from other healthcare SEO?", a: "HIPAA rules keep therapists from using patient stories and testimonials as proof. Clients also search by symptom, therapy type and population, such as anxiety therapist or EMDR therapist, rather than just therapist near me. Therapist SEO has to build trust and match those searches without the usual proof tools." },
  { q: "Can a private practice outrank Psychology Today?", a: "For many broad searches, not directly: the directory's domain is far stronger. The page's approach is to compete where directories are weaker: a fully optimized Google Business Profile in the local 3-pack, searches tied to a city, and long-tail searches by therapy type and population." },
  { q: "Which keywords should a Florida therapist target?", a: "Four groups: high-urgency searches such as therapist near me accepting new patients, specialty searches such as EMDR therapist or couples counselor, location searches tied to a city or neighborhood, and private-pay searches such as out of network therapist. Which group matters most depends on your practice model." },
  { q: "How should a therapist's Google Business Profile be set up?", a: "The page recommends six to eight relevant categories, 30 or more services written in the words clients search, weekly posts, steady review pace and every attribute completed. A typical therapy listing has one category and no service list, so the gap is large." },
  { q: "How long does a new therapist SEO program take?", a: "The first 30 days build the foundation: profile, posting calendar and review system. The page says a well-configured profile can move from outside the local pack to inside it within about 90 days in moderately competitive markets. It is a possible timeline, not a guarantee." },
];

export const vsWebptFaqs: Faq[] = [
  { q: "Does Primara work with physical therapy practices?", a: "No. Primara serves independent primary care and mental health practices exclusively. WebPT is a physical therapy EHR, and if you run a PT practice this comparison is not for you. We would encourage you to find an agency that specializes in PT marketing." },
  { q: "Who is this comparison for?", a: "Primary care or mental health practices that use WebPT for billing and are weighing its marketing add-on as an extra purchase. For that reader the question is whether an EHR add-on is enough or whether a dedicated marketing agency is the better fit." },
  { q: "What marketing does WebPT include?", a: "WebPT's marketing features are add-ons to its EHR subscription: patient engagement emails, appointment reminders, basic online scheduling and a web presence tool. As described on this page, they do not include competitive local SEO, Google Business Profile category work, rank-grid tracking or review-response management." },
  { q: "When is the WebPT marketing add-on enough?", a: "When you only need appointment reminders and patient communication, already use WebPT and want everything in one platform, or work in a market with very low local search competition. It is less suited to practices trying to rank above competitors in Google Maps." },
  { q: "How do contract terms compare?", a: "Per the comparison table, Primara is month-to-month after the first three months, with the website, content, Google Business Profile and review system owned by the practice. WebPT's marketing module is tied to the terms of the EHR subscription." },
];

export const vsDoctorlogicFaqs: Faq[] = [
  { q: "What is DoctorLogic?", a: "A website and SEO platform for medical practices across many specialties, including cosmetic surgery, dermatology, orthopedics and primary care. Its core product is AI-assisted generation of condition and procedure pages inside a templated website platform." },
  { q: "How is Primara different from DoctorLogic?", a: "Primara is a boutique agency with no software product and no automated content generation. We serve primary care and mental health practices only, and each page is written for a specific market, competitor set and local search intent by the founders." },
  { q: "Can AI-generated content rank in a competitive local market?", a: "It may meet Google's quality threshold by being unique and substantial enough. This page argues that is not the same as the local signals that move rankings in a competitive city, such as knowing which hospital systems and neighborhoods shape the market." },
  { q: "When might DoctorLogic be the better choice?", a: "If you need a specialty Primara does not serve, such as cosmetic surgery, dermatology or orthopedics, if your market has low to moderate local search competition, or if you prefer AI-assisted content volume and an account-management model." },
  { q: "What do I keep if I leave?", a: "Per the comparison table, Primara clients keep the website, content, Google Business Profile and review system. On DoctorLogic's platform, content is tied to the platform. Contract terms also differ: Primara is month-to-month after three months, and DoctorLogic contracts are typically annual." },
];

export const guidesHubFaqs: Faq[] = [
  { q: "What do the Primara guides cover?", a: "Pricing, comparisons and how-to work for independent practices: what medical SEO, websites, ads and Google Business Profile management cost, how channels compare, and step-by-step guides for tasks such as tracking calls, responding to reviews and fixing a suspended listing." },
  { q: "Are the guides written for each city?", a: "No. Each guide covers one question once and is not cloned with a city swapped in. For geography, the location pages cover the Florida markets we serve, and the guides link to the matching service and city pages." },
  { q: "Do the guides give legal or medical advice?", a: "No. They give marketing guidance. Guides that touch HIPAA, accessibility or advertising rules explain how the rules affect marketing and cite the regulator's own guidance, and they tell you to confirm specifics with a qualified attorney or your compliance advisor." },
  { q: "How current are the guides?", a: "Each guide shows an Updated date on the page and cites its sources, mostly Google's own documentation and U.S. government agencies. Costs and platform features change over time, so check that date before you rely on a specific number or a step in a platform's settings." },
  { q: "What if my question is not covered?", a: "Ask us directly. Call (561) 291-2681 or request the free audit, which looks at your own Google Maps position, your profile setup and your reviews against a named local competitor, and is delivered in three to five business days." },
];

export const blogHubFaqs: Faq[] = [
  { q: "Who writes the Primara blog?", a: "Liam Costello and Gio LaRoche, the founders of Primara. Each post carries the author's name and date, and the benchmarks and tactics come from campaigns they run for independent practices in West Palm Beach, Fort Lauderdale, Boca Raton and Miami." },
  { q: "What does the blog cover?", a: "Hospital-system competition, Google Maps ranking, Google Business Profile categories, HIPAA limits on review requests and the slow, compounding timeline of local SEO. The audience is independent primary care physicians and private practice therapists in Florida." },
  { q: "How is the blog different from the guides?", a: "Blog posts are the founders' field notes on a specific problem they see in live campaigns. The guides are answer-first pages on a single question, such as what something costs or how to do a task, with the sources cited on the page." },
  { q: "How do I apply a post to my own practice?", a: "Start with the free online presence audit. It maps your Google Maps rank, Google Business Profile gaps and review pace against your top three competitors, so you can see which post applies to you first." },
];

export const hipaaFaqs: Faq[] = [
  { q: "Is Primara a HIPAA covered entity?", a: "No. Primara is a digital marketing agency, not a healthcare provider, health plan or healthcare clearinghouse. When our work involves protected health information for a covered entity client, we may qualify as a Business Associate, as this notice explains." },
  { q: "Does primara365.com collect patient information?", a: "No. The forms and contact channels on this website are for business inquiries from practice owners and administrators, not patients. We do not collect or store medical records, diagnoses, treatment details or insurance data through this site." },
  { q: "What happens before Primara handles protected health information?", a: "A Business Associate Agreement is signed with the practice first. After that, we use and disclose PHI only as the agreement and the law allow, apply the minimum necessary standard, and report any known breach to the practice without unreasonable delay." },
  { q: "Do Primara's marketing services normally involve patient records?", a: "Typically no. Managing a Google Business Profile, responding to public reviews, writing website content and local SEO do not usually require access to individual patient records. Where a program does involve patient data, such as a review request program, it runs under a signed agreement." },
  { q: "How can a practice request a Business Associate Agreement?", a: "Ask before the engagement begins. Primara is prepared to sign one and can provide its standard agreement on request. Use the contact details at the bottom of this notice or call (561) 291-2681. This notice is not legal advice, so have your own counsel review it." },
];
